### DISCUSSION TITLE
OTPL->OTLP: How to work with nested attributes (rewrite_tag)

### DISCUSSION THREAD

**Discussion by nortenorte** [fluent/fluent-bit#10076] [Q&A]
How does the syntax for nested OTLP look like.

We want to set a tag based on which service sent the data. We think rewrite_tag would be the easiest way to accomplish this. We want to look at service.name and if it is my.service set a TAG.

{"resource_logs":[{"resource":{"attributes":[{"key":"service.name", "value":{"string_value":"my.service"}}]},

However we don't know how the syntax for this would work. Below is an example how it work if we look in a field in the "first level".  See our example below

fluent-bit_stdout_otlp.yaml

```
service:
    flush: 1
    log_level: trace
 
pipeline:
    inputs:
        - name: opentelemetry
          listen: 0.0.0.0
          port: 4318
          tag: test_tag
          tag_from_uri: false
          successful_response_code: 200
    filters:
        - name: rewrite_tag
          match: test_tag
          rule: $message "^(Example log record)$" test_tag2 true
    outputs:
        - name: stdout
          match: '*'
        - name: opentelemetry
          match: test_tag2
          host: 127.0.0.1
          port: 4319
```

1. Start fluent-bit 3.2.6:

```
docker run -v $(pwd):$(pwd) -w $(pwd) --rm -it -p 4318:4318 --network host fluent/fluent-bit:3.2.6 /fluent-bit/bin/fluent-bit -c fluent-bit_stdout_otlp.yaml
```

2. Install protocurl: https://github.com/qaware/protocurl

3. Use protocurl to send example standard otlp metric message. (https://github.com/open-telemetry/opentelemetry-proto)

```
opentelemetry-proto > protocurl \
-i opentelemetry.proto.collector.logs.v1.ExportLogsServiceRequest \
-o opentelemetry.proto.collector.logs.v1.ExportLogsServiceResponse \
-u http://localhost:4318/v1/logs \
-d @examples/logs_simple.json \
-I .
```

4. We can see that both tags are visible as we want to. How would the syntax be to check service.name instead?

Start of the example (full example opentelemetry-proto/examples/logs.json )
```
{
  "resource_logs": [
    { 
      "resource":
        {
          "attributes":[
            {
              "key":"service.name", "value":
                {
                    "string_value":"my.service"
                 }
              }]
          },
.....
```
