### DISCUSSION TITLE
YAML configuration upstream_servers

### DISCUSSION THREAD

**Discussion by gourabh09** [fluent/fluent-bit#10269] [General]
I am trying to configure Fluent Bit to use upstream servers in YAML configuration, and I want to understand both ways of defining the upstream_servers:

Defining the Upstream Server in a Separate File:
I want to declare the upstream server and its configuration (such as tls, tls_verify, tls_ca_file, etc.) in a separate file. However, when I do this, it doesn't work as expected.

Defining the Upstream Server Inline in the Same YAML File:
I have also tried defining the upstream server and its configuration directly within the same YAML configuration file under the outputs section, which works but only without the upstream_servers section.

`upstream_servers:
  - name: primary-forward-balancing
    nodes:
      - name: example-server-1
        host: example-host-1.com
        port: 24224
        tls: true
        tls_verify: true
        tls_ca_file: /path/to/ca/certificate/ca.pem
        tls_cert_file: /path/to/client/certificate/client-cert.pem
        tls_key_file: /path/to/client/key/client-key.pem
`
example I put this in fluent-upstream.yml

and in output
 upstream: filepath
this works in classic format but not working in yaml giving 

- name: example-server-1
        host: example-host-1.com
        port: 24224
        tls: true
        tls_verify: true
        tls_ca_file: /path/to/ca/certificate/ca.pem
        tls_cert_file: /path/to/client/certificate/client-cert.pem
        tls_key_file: /path/to/client/key/client-key.pem
        in output this is working

**Comment by patrick-stephens** [comment]
Does the example in https://github.com/fluent/fluent-bit/pull/9513 not work?

**Comment by gourabh09** [comment]
use_tls works

**Reply by patrick-stephens** [reply]
Can you send a PR to update the docs?

**Reply by Gourabh7** [reply]
this use_tls also not working. I Tried  tls , tls_enabled , use_tls this are not working any input would be helpful

**Reply by patrick-stephens** [reply]
What are you actually trying?
Does the example in #9513 work?
```
upstream_servers:
  - name: forward-balancing
    nodes:
      - name: node-1
        host: 127.0.0.1
        port: 43000

      - name: node-2
        host: 127.0.0.1
        port: 44000

      - name: node-3
        host: 127.0.0.1
        port: 45000
        tls: true
        tls_verify: false
        shared_key: secret

  - name: forward-balancing-2
    nodes:
      - name: node-A
        host: 192.168.1.10
        port: 50000

      - name: node-B
        host: 192.168.1.11
        port: 51000
```
