### DISCUSSION TITLE
FluentBit Performance for persistent TCP connection

### DISCUSSION THREAD

**Discussion by brunodeoliveiramacedo** [fluent/fluent-bit#8460] [Q&A] [answered]
I'm not able to reach the full CPU/MEM capacity of my fluent bit.

I'm using Fluentbit to forward some messages to Kafka. I can see the performance degradation when I start to forward more messages to Fluentbit.

This is my current configuration:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
data:
  fluent-bit.conf: |
    [INPUT]
        Name         tcp
        Listen       0.0.0.0
        Port         24224
        Format       none

    [INPUT]
        Name         tcp
        Listen       0.0.0.0
        Port         514
        Format       none
        Buffer_Size  1024KB   
        Chunk_Size   512KB

    [INPUT]
        Name         udp
        Listen       0.0.0.0
        Port         514
        Format       none
        Buffer_Size  1024KB   
        Chunk_Size   512KB

    [SERVICE]
        Flush        1 
        Daemon       Off
        Log_Level    info
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020
        Health_Check On
        Mem_Buf_Limit 2GB 
    
        
    [OUTPUT]
        Name         kafka
        Match        *
        Brokers      kafka-broker:9200
        Topics       syslogs
        Retry_Limit  False
        Format       json
        rdkafka.queue.buffering.max.ms 100  
        rdkafka.request.required.acks 1     
        rdkafka.message.send.max.retries 5  
        rdkafka.retry.backoff.ms 100
```

```
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.2.1-debug
          securityContext:
            runAsUser: 0
          command: ["/fluent-bit/bin/fluent-bit"]
          args: ["-c", "/fluent-bit/etc/fluent-bit.conf"]
          resources:
            requests:
              memory: "524Mi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "2000m"
```

![image](https://github.com/fluent/fluent-bit/assets/157141852/6a8d27b6-ddfc-4cf0-9731-106068ab7532)

I also have persistent TCP connections. So I would have for example two connections forwarding all the messages for a single FluentBit pod.

I would need to handle:
~ 70MB per sec
~ 700 bytes per message
110.000 messages per sec

Would you have any configuration ideas that could improve my performance for these persistent TCP connections?
