### DISCUSSION TITLE
@INCLUDE options question

### DISCUSSION THREAD

**Discussion by fulldeck** [fluent/fluent-bit#8485] [Q&A]
1.
I want to create a sub folder for all my conf files.
Does this look correct:

fluent-bit.conf 
`@INCLUDE ./inputs_d/input*.conf`

In the inputs_d folder I would have files
```
input_1.conf
input_2.conf
```

2.
Is there an option to re-read the configurations in the `@INCLUDE` folder every 60sec  for example?
I would like to emulate what filebeats does:

```
filebeat.config.inputs:
  enabled: true
  path: configs/*.yml
  reload.enabled: true
  reload.period: 10s
```
