### DISCUSSION TITLE
Issues with Fluent Bit Monitoring Host System (Linux) Metrics in a Docker Container

### DISCUSSION THREAD

**Discussion by zRaphi** [fluent/fluent-bit#8947] [Q&A]
Hello everyone,

I installed Fluent Bit as a Docker container to monitor the metrics of the host system (Linux System), not just the metrics of the container. I added /proc, /run/systemd, /sys, and / as volumes. However, it seems like the container is only monitoring itself.

There are also two errors in the logs:
`[input:node_exporter_metrics:node_exporter_metrics.0] systemd init failed `
`[input:node_exporter_metrics:node_exporter_metrics.0] could not set systemd collector for Node Exporter Metrics plugin`

Any Ideas?

**Comment by patrick-stephens** [comment]
Provide the full config and command you used to run it along with the versions, etc. used.

**Comment by zRaphi** [comment]
FluentBit Version 3.0.7

Docker-Compose Part:
```yaml
  fluentbit:
    image: ${fluentbit_version}
    container_name: fluentbit
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    command:
      - '--config=/fluent-bit/etc/fluent-bit.yml'
    privileged: true
    ports:
      - 2021
    networks:
       - observability
    volumes:
      - /proc:/host/proc:ro
      - /run/systemd:/run/systemd:ro
      - /sys:/host/sys:ro
      - /:/host/root:ro
      - /observability/fluent-bit.yml:/fluent-bit/etc/fluent-bit.yml:ro
      - /:/host:ro,rslave
    pid: host
```

fluent-bit.yml
```yaml
service:
    flush: 1
    log_level: info
#    parsers_file: parsers.conf
pipeline:
    inputs:
        - name: node_exporter_metrics
          tag:  node_metrics
          scrape_interval: 2
    outputs:
        - name: prometheus_exporter
          match: node_metrics
          host: 0.0.0.0
          port: 2021
          # add user-defined labels
          add_label:
            - app fluent-bit
            - color blue
 #   inputs:
 #       - name: systemd
 #         tag:  host.*
 #         systemd_filter: _SYSTEMD_UNIT=docker.service
 #   outputs:
 #       - name: stdout
 #         match: "*"
```

I think that should be everything
