### DISCUSSION TITLE
User input to lua function

### DISCUSSION THREAD

**Discussion by allewell** [fluent/fluent-bit#9694] [General]
Is it possible to provide user input to Lua functions inside the lua filter? 

For example, I have in the pipeline:
```
    - name: lua
      match: index_queues
      call: somefunction
      script: helpers.lua
```

helpers.lua:
```
function somefunction(tag, timestamp, record)
    local key = 'putCounterByThreadTopN'
    local value = record[key]
    ...
end
```

#### My desire
maybe i want to re-use that function across the pipeline:
```
    - name: lua
      match: index_queues
      call: somefunction
      script: helpers.lua
      args: 
        key: putCounterByThreadTopN
```

and somewhere else:

```
    - name: lua
      match: cache
      call: somefunction
      script: helpers.lua
      args: 
        key: someOtherKey
```

helpers.lua:
```
function somefunction(tag, timestamp, record, args)
    local key = args['key']
    local value = record[key]
    ...
end
```

Does anyone know if this can be done now, or would it be a feature request?

The goal here is code re-use, not want to duplicate functions across the pipeline.
