### DISCUSSION TITLE
Multiple Decode_Field_as in Parser in YAML format config

### DISCUSSION THREAD

**Discussion by vkshn** [fluent/fluent-bit#9717] [Q&A] [answered]
Hi, I'm trying to convert the "classic mode" configuration to YAML and I have a problem with the fact that I need to convert this config to YAML:
```
Decode_Field_as escaped message try_next
Decode_Field_as json message 
```
 I didn't find in the documentation how to do this. I tried to understand from the source code, but nothing works either.

I tried to do this 
```yaml
      decode_field_as: 
      - type: escaped
        field: message
        action: try_next
      - type: json
        field: message
```
and that
```yaml
decode_field_as:
  - escaped message try_next
  - json message 

```
also,
```yaml
      rules: 
      - backend: decode_field_as
        type: escaped
        field: message
        action: try_next
      - backend: decode_field_as
        type: json
        field: message
```

but nothing works either, I get error 
```
[2024/12/12 15:09:24] [error] [config] YAML error found in file "/.../config/parsers/parsers.yaml", line 9, column 6: unexpected event 'sequence-start-event' (7) in state 'unknown' (25).
```

**Comment by allewell** [comment, marked as answer]
I'm not sure, but have you tried duplicating it? :
```yaml
decode_field_as: escaped message try_next 
decode_field_as: json message 
```

That works in some places (eg rewrite_tag filter:)
```yaml
    - name: rewrite_tag
      match: something
      rule: '$log  "java\.lang\.OutOfMemoryError"  critical_events_temp_1  true'
      rule: '$log  "java\.lang\.StackOverflowError"  critical_events_temp_2  true'
```

But not let's say in tail input path, which is comma delimited:
```yaml
  inputs:
    - name: tail
      path: >-
        some_path/atlassian-jira.log*,
        some_path/atlassian-jira-stats.log*
```
