### ISSUE TITLE
How is prometheus_remote_write add_label supposed to be configured in YAML?

### ISSUE THREAD

**Issue by GlassBil** [fluent/fluent-bit#10027]
How am I supposed to add multiple labels with add_label when using YAML?

```
pipeline:
  outputs:
    - name: prometheus_remote_write
      add_label: ...
```

I've tried multiple variants but none seem to work. I can't find anything in the documentation on how to do this. I've tried:
```
add_label:
  foo: bar
  baz: qux
```
```
add_label:
  - foo bar
  - baz qux
```
```
add_label:
  - key: foo
     value: bar
  - key: baz
    value: qux
```
