### ISSUE TITLE
Forward input partially missing data: getting Error "could not write forward header"

### ISSUE THREAD

**Issue by vpshibin** [fluent/fluent-bit#10079]
## Bug Report

**Describe the bug**
I'm using fluent-bit in a forwarder-aggregator pattern. Data is being collected from Windows VMs, and aggregator is Linux VM (2 of them behind a load balancer).

In the source fluent-bit (forwarder) logs, I'm seeing the below error. And data is missing partially (about 70% of the data is not reaching destination).

[2025/03/14 15:45:40] [debug] [output:forward:forward.1] task_id=15 assigned to thread #0
[2025/03/14 15:45:40] [debug] [output:forward:forward.1] request 424 bytes to flush
[2025/03/14 15:45:40] [debug] [retry] re-using retry for task_id=15 attempts=5
[2025/03/14 15:45:40] [debug] [upstream] KA connection #4476 to 10.14.114.180:5174 has been assigned (recycled)
[2025/03/14 15:45:40] [ warn] [engine] failed to flush chunk '3096-1741927459.414588600.flb', retry in 71 seconds: task_id=15, input=tail.1 > output=forward.1 (out_id=1)
[2025/03/14 15:45:40] [error] [output:forward:forward.1] could not write forward header

I have a very high (1000s) number of VMs sending data to each aggregator. However there is no saturation in aggregator CPU (about 10% used usually) or Memory (about 30% free memory during peak times also). 

My retry_limit is 5, so after 5 attempts the chunk is dropped.
[2025/03/14 15:45:40] [debug] [upstream] KA connection #4476 to 10.14.114.180:5174 is now available
[2025/03/14 15:45:40] [debug] [out flush] cb_destroy coro_id=3337
[2025/03/14 15:45:41] [debug] [output:forward:forward.1] task_id=18 assigned to thread #1
[2025/03/14 15:45:41] [debug] [task] task_id=18 reached retry-attempts limit 5/5

On the aggregator (receiving) side, I see the below errors, but not sure if they are related.
[2025/03/14 16:07:34] [error] [input:forward:forward.1] could not enqueue records into the ring buffer

**To Reproduce**
- Use fluent bit in a forwarder/aggregator pattern using forward input/output. About 1000 forwarder instances connected to fluent bit acting as aggregator.
```

```
- Steps to reproduce the problem:

**Expected behavior**
The forward outputs should be working to send the data to the aggregator.

**Screenshots**

**Your Environment**
* Version used: Forwarder (3.1.7), Aggregator (3.2.1)
* Configuration:
Forwarder:
[OUTPUT]
    Name                            Forward
    Match                           EdgeClient
    # masked ip below
    Host                            x.x.x.x 
    Port                            5174
    storage.total_limit_size        5M
    tls                             Off
    net.connect_timeout             5
    net.keepalive                   On
    net.keepalive_idle_timeout      30
    net.max_worker_connections      1
    Retry_Limit                     5

Aggregator:
    - name: forward
      listen: 0.0.0.0
      port: 5174
      Tag_Prefix: Logs-
      Threaded: true
      storage.type: filesystem
      tls: off
      tls.verify: off

      processors:
        logs:
          - name: content_modifier
            action: insert
            key: AggNbr
            value: ${AGG_NBR}

* Environment name and version (e.g. Kubernetes? What version?):
Application logs from VMs.

* Server type and version:
  Virtual machines, forwarders (on-prem)
  Aggregators (Azure cloud) - 2* Standard_B4s_v2 (4 vCPUs, 16 GB RAM each)

* Operating System and version:
  Forwarders: Windows 10 Enterprise LTSC 2019
  Aggregators: Linux RedHat 8.10
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
Initially the first thing to check is step up to latest versions and confirm it is not already fixed.

**Comment by patrick-stephens** [comment]
Also I'd check the network loading to see if that is saturated and leading to the backpressure or error

**Comment by vpshibin** [comment]
hi @patrick-stephens - on your second point. 

I don't see any backpressure. Attached is the comparison of input vs output records, and there are no failed records in the output. 

About network loading - is there any specific metrics to be checked in fluentbit or the aggregator VM. I can see both my aggregator VMs have about 12000 incoming connections from the source VM.

![Image](https://github.com/user-attachments/assets/00e676c0-4908-4c9d-be1b-fbf140e89e41)
![Image](https://github.com/user-attachments/assets/39c5510b-92f7-43ba-bb7a-aaa9cb5314af)

**Comment by chrko** [comment]
We also observed a similar issue and spent quite some time in investigation. It seems that the keepalive on Windows is somehow broken / not correctly working and we remediated this by setting `net.keepalive: false` within the Windows fluent-bit configuration.

Version:
- v1.31.1 on Azure Kubernetes Service
- tested fluent-bit 3.2.0 & 4.0.1 with upstream images and custom linux image having SIMD enabled

fluent-bit config files:

```yaml
# linux configuration
service:
  flush: 1
  logLevel: info

  httpServer: true
  hotReload: true

  storage.metrics: true
  storage.backlog.memLimit: 20M

pipeline:
  inputs:
    - name: forward
      threaded: true
      alias: lin-in-forward
      memBufLimit: 100MB
      bufferMaxSize: 50M
      bufferChunkSize: 5M

  outputs:
    - name: null
      alias: lin-out
      match: '*'
```

```yaml
service:
  flush: 1
  logLevel: info

  httpServer: true
  hotReload: true

  storage.metrics: true
  storage.backlog.memLimit: 20M

pipeline:
  inputs:
    - name: dummy
      alias: win-in-dummy-1
      rate: 50
      threaded: true
      copies: 1000
      # source: head on keyboard (to get a little bit more bytes)
      dummy: '{"message": "custom dummy with a lot of data csldfakjskl jasdfukhlcbhsad ikjhsad fkjn kljashfdkljhas iu kjthkalshfd kjsadhfk hsadklj hfklsahdjrfikut hykljdfhas kldfkltua fsdhkaskdfjh klsaut kuasdkfh sakljfh utuksadhf laskdrfu kwearjfklsd hfasiuifwhraejfhks dhfklasj dhksalfj hlaweikhfskljhasdklf hsailueh fklasjdhf lksjdhf lkuhsajf kjlsadhf kljsadfhilu asjhtfkluasdj hfasdlkfuusadhf kljsdhf lkuasdhfklsjfdh lksau dshklasjfh asklj"}'

  filters:
    - name: grep
      match: '*'
      exclude: "log .*ply from ::1:.*"

  outputs:
    - name: forward
      alias: win-out-forward
      host: slp-4664-lin-svc-col
      match: '*'
      net.keepalive: false
```

and some k8s files to get pods & services up and running.

Removing `net.keepalive: false` from the Windows configuration leads to reproducible issues:
```
...
[2025/04/25 13:28:26] [error] [output:forward:win-out-forward] could not write forward header
[2025/04/25 13:28:26] [ warn] [engine] failed to flush chunk '8212-1745587705.841032800.flb', retry in 9 seconds: task_id=3, input=win-in-dummy-1 > output=win-out-forward (out_id=0)
[2025/04/25 13:28:28] [error] [output:forward:win-out-forward] could not write forward header
[2025/04/25 13:28:28] [error] [engine] chunk '8212-1745587697.858492500.flb' cannot be retried: task_id=1, input=win-in-dummy-1 > output=win-out-forward
[2025/04/25 13:28:29] [error] [output:forward:win-out-forward] could not write forward header
[2025/04/25 13:28:29] [ warn] [engine] failed to flush chunk '8212-1745587708.864932200.flb', retry in 6 seconds: task_id=1, input=win-in-dummy-1 > output=win-out-forward (out_id=0)
...
```
