### ISSUE TITLE
out_gelf: crash after messages without short_message key

### ISSUE THREAD

**Issue by bpetermannS11** [fluent/fluent-bit#10086]
## Bug Report

**Describe the bug**
Tested with fluent-bit v3.2.8. Fluent-bit may crash due to a problem in the gelf output plugin.
If there are messages that don't have the `short_message` key, some `flb_sds_destroy(s);` may be called with an non-initialised pointer which corrupts the memory management and can lead to a crash.

Running fluent-bit in valgrind will show the problem.

**To Reproduce**
- Example log message if applicable:
```
==2764851== Thread 2 flb-pipeline:
==2764851== Conditional jump or move depends on uninitialised value(s)
==2764851==    at 0x290D87: flb_sds_destroy (flb_sds.c:393)
==2764851==    by 0x3D411B: cb_gelf_flush (gelf.c:380)
==2764851==    by 0x88212A: co_init (amd64.c:117)
```
- Steps to reproduce the problem:

Run fluent-bit with the following config
```
pipeline:
  inputs:
    - name: tail
      path: /home/username/somefile.txt
      db: /tmp/somefile.db
      tag: sometag
  outputs:
    - name: gelf
      match: sometag
      host: some-graylog.domain.com
      port: 12201
      mode: tls
      tls.verify: true
      gelf_short_message_key: message
      gelf_host_key: hostname
      gelf_tag_key: tag
      net.max_worker_connections: 5
```

then append some lines to the file /home/username/somefile.txt.

The `tail` input will convey the log messages in the key `log`. The gelf output will expect the short-message key `message` which isn't set. That's why the gelf output will complain about the missing `short_message` key, which is expected.
But what's not expected is that it will subsequently access an uninitialised pointer which may later lead to a crash.

**Expected behavior**
The gelf output should properly handle the missing short_message key and not work on uninitialised variables.

**Screenshots**
N/A

**Your Environment**

* Version used: v3.2.8
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): plain ubuntu
* Server type and version: linux
* Operating System and version: ubuntu 22.04
* Filters and plugins: gelf output

**Additional context**
