### ISSUE TITLE
Add support to disable `db` while still setting the path

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#10198]
**Is your feature request related to a problem? Please describe.**

I want to be able to only enable the DB functionality when I've configured writable storage on a host, as it currently stands I need to write custom logic into the Helm chart to remove the `db` config key is the host storage isn't writable.

**Describe the solution you'd like**

The `db` and related keys aren't currently YAML native so ideally a nested YAML format can be adopted along the lines of

```yaml
env:
  STORAGE_ENABLED: "true"

pipeline:
  inputs:
    - name: tail   
      path: /var/log/containers/*.log
      db:
        enabled: ${STORAGE_ENABLED}
        path: /fluent-bit/data/tail.db
```

**Describe alternatives you've considered**

I remove the key in the Helm chart.

**Additional context**

The whole config pattern needs to be aligned to idiomatic YAML and at the same time the config should allow keys to be present and use guard flags (like `enabled` above) to control conditional logic.
