### ISSUE TITLE
Splunk_token from in_splunk overwrites splunk_token from out_splunk

### ISSUE THREAD

**Issue by edinel** [fluent/fluent-bit#10208]
## Bug Report

**Describe the bug**
When running both Splunk HEC plugins (in and out), if the value from the option splunk_token is different from the one in the output splunk plugin, the Splunk endpoint will complain about the token.  This appears to be because the token used for the input is overwriting the token used for the output.

For many reasons, including security roles, we need the option to set both.

**To Reproduce**
Details here: https://github.com/chronosphereio/calyptia-issue-repro/tree/ZD-4587/repros/BigId/ZD-4587

``` 
service:
  log_level: debug
pipeline:
  inputs:
    - name: splunk
      alias: splunk_hec
      listen: 0.0.0.0
      port: "9880"
      buffer_max_size: 4M
      buffer_chunk_size: 512K
      splunk_token: tokenabcd1234
      tls.verify: on
      tls.debug: "1"
      #store_token_in_metadata: false
      tag: splunk.bcc34ef6-12ad-4689-a436-733a616b2723
  outputs:
    - name: splunk
      alias: splunk_obs
      log_level: debug
      host: 10.128.0.56
      port: "8088"
      compress: none
      tls: true
      tls.verify: "off"
      splunk_token: tokenabcd1234
      Match_Regex: ^(?!.*_calyptia_cloud).*$
```
With the above config and the below curl, it works, becasue the tokens are the same:

``` curl -v http://10.128.0.48:9880/services/collector      -H "Content-Type: application/json" -d '{"event": "Hello fluent"}'  -H  "Authorization: Splunk tokenabcd1234"```

Essentially this combination works:
```-H  "Authorization: Splunk tokenabcd1234"
Out: tokenabcd1234
IN: tokenabcd1234
```
This one doesn't (OUT splunk complains):
```
-H  "Authorization: Splunk tokenabcd1234A"
Out: tokenabcd1234
IN: tokenabcd1234A
GOT: [2025/04/02 20:06:35] [ warn] [output:splunk:splunk_obs] http_status=403:
{"text":"Invalid token","code":4}
```

This one doesn't (IN splunk complains):
```-H  "Authorization: Splunk tokenabcd1234"
Out: tokenabcd1234
IN: tokenabcd1234A
GOT:  A 401 with Curl and in fluent: [2025/04/02 20:08:14] [ warn] [input:splunk:splunk_hec] wrong credentials in request headers. 
```

**Expected behavior**
We need the ability to have different authentication tokens for input and output of Splunk.  

**Your Environment**
This appears to be happening with a minimal deployment.
