### ISSUE TITLE
Allow nested yaml lists in input plugin config

### ISSUE THREAD

**Issue by fredrik-jansson-se** [fluent/fluent-bit#10206]
I would like to configure our input plugin with some nested yaml lists.

Example:
```
inputs:
  - name: avassa_logs
    applications:
        - name: app-1
        - name: app-2
          containers:
            - c1
            - c2
```

**Describe the solution you'd like**
Possibility to declare the above in the `flb_config_map` somehow. If I try now I get
```
 {
     FLB_CONFIG_MAP_VARIANT, "applications", NULL,
     0, FLB_FALSE, 0,
     "List of applications to follow"
   },
```
```
[2025/04/11 14:21:07] [error] [config] YAML error found in file "fluent-bit.yaml", line 23, column 10: unexpected event 'mapping-start-event' (9) in state 'plugin-values' (17).
```

**Describe alternatives you've considered**
Another possibility would be to declare that I want access to the yaml below `applications`:
```
applications:
     - name: app-1
     - name: app-2
        containers:
          - c1
          - c2
```
In that case I could parse the yaml myself.

**Additional context**
This would be a nicer way for our customers to configure the input plugin.

Other alternatives that (I believe) would work today would be a space separated list:
`applications: app-1 app-2(c1,c2)`

But that is not as extensible (in case we need more fields in the future) nor what you'd expect in a yaml config file.
