### ISSUE TITLE
outputs[name=opensearch].aws_auth in YAML config is not evaluated as a boolean

### ISSUE THREAD

**Issue by filip-zyzniewski** [fluent/fluent-bit#10228]
## Bug Report

**Describe the bug**

such a YAML configuration:

```yaml
pipeline:
  outputs:
    - name: opensearch
      aws_auth: true
```

does NOT cause fluent-bit to sign the OpenSearch requests.
It's because of https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_opensearch/os_conf.c#L247 ,
where `strncasecmp` is used to check the value of `aws_auth` instead of the usual approach for other boolean properties like
https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_opensearch/os_conf.c#L79 .

**To Reproduce**

running fluent-bit with:

```yaml
service:
  log_level: debug

pipeline:
  outputs:
    - name: opensearch
      aws_auth: true
```

does not print anything about AWS.
Running it with:

```yaml
service:
  log_level: debug

pipeline:
  outputs:
    - name: opensearch
      aws_auth: on
```

prints (https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_opensearch/os_conf.c#L249 should probably be `s/out_es/out_opensearch/` BTW):

```
[2025/04/18 07:59:08] [debug] [out_es] Enabled AWS Auth
[...]
[2025/04/18 07:59:08] [debug] [aws_credentials] Initialized Env Provider in standard chain
```

**Expected behavior**

I expected `true` to be treated as enabled.

**Your Environment**
* Version used: v4.0.0
* Operating System and version: `Darwin JFYYQW9DJ7 24.3.0 Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:16 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6000 arm64` 
* Filters and plugins: opensearch

**Additional context**

Per https://yaml.org/type/bool.html `true` should be an equivalent of `on`.
`out_es` seems to be suffering from the same issue: https://github.com/fluent/fluent-bit/blob/v4.0.0/plugins/out_es/es_conf.c#L372 .
