### ISSUE TITLE
Tail sampling crashing fluentbit

### ISSUE THREAD

**Issue by henrikrexed** [fluent/fluent-bit#10248]
## Bug Report

**Describe the bug**

When using tail sampling with various rules, fluentbit keeps crashing .
This issue is making fluentbit not usable in k8S environment.

**To Reproduce**
- Rubular link if applicable:
Here is a repo with all the instruction to reproduce the bug. this environment will deploy the OpenTelemetry demo that will export traces using olp grpc and otlp http.
https://github.com/isItObservable/fluentbit-vs-collector/tree/fluentbitv4.0

- Example log message if applicable:
```
[2025/04/23 16:01:42] [engine] caught signal (SIGSEGV)
#0 0x58eb007b7f1a   in pack_instrumentation_scope() at lib/ctraces/src/ctr_encode_msgpack.c:150
#1 0x58eb007b7f1a   in pack_scope_spans() at lib/ctraces/src/ctr_encode_msgpack.c:445
#2 0x58eb007b7f1a   in ctr_encode_msgpack_create() at lib/ctraces/src/ctr_encode_msgpack.c:534
#3 0x58eb007877bd   in input_trace_append() at src/flb_input_trace.c:83
#4 0x58eb006c6ae8   in reconcile_and_dispatch_traces() at plugins/processor_sampling/sampling_tail.c:327
#5 0x58eb006c6ae8   in cb_timer_flush() at plugins/processor_sampling/sampling_tail.c:347
#6 0x58eb00601215   in flb_sched_event_handler() at src/flb_scheduler.c:624
#7 0x58eb005fd3a7   in flb_engine_start() at src/flb_engine.c:1058
#8 0x58eb005d6793   in flb_lib_worker() at src/flb_lib.c:835
#9 0x7ff5e873b1f4   in ???() at ???:0
#10 0x7ff5e87bb89b   in ???() at ???:0
#11 0xffffffffffffffff in ???() at ???:0
```
- Steps to reproduce the problem:

**Expected behavior**

Configure a tail sampling processor and send otlp traces to fluentbit.
example of configuraiton:
 - name: sampling
    type: tail
    sampling_settings:
      decision_wait: 5s
    conditions:
      - type: latency
        threshold_ms_high: 200
      - type: status_code
        status_codes: [ "ERROR" , "UNSET" ]

**Your Environment**

* Version used: fluentbit 4.0
* Configuration: deployed as a daemonset
* Environment name and version : GKE with 2 nodes
* Filters and plugins: tail, kubernetes, nest, lift, 

**Additional context**
This issue is not allowing us to use Fluentbit to manage our traces

**Comment by edsiper** [comment]
@henrikrexed thanks for the report. Is there a way to run this locally ?

**Comment by henrikrexed** [comment]
The best way is to run the openTelemtry demo using docker. but you will need logs of customization to replace the OpenTelemetry collector with Fluentbit.
Let me know i could help resolving this issue?

**Comment by edsiper** [comment]
@henrikrexed is there a way with a standalone tool that generate traces be able to repro the problem ? (looking for a way to isolate the issue and make it easy to repro)

**Comment by henrikrexed** [comment]
I just tested the new release. 
So by leaving my initial settings :
```yaml 
  - name: sampling
                type: tail
                sampling_settings:
                  decision_wait: 5s
                conditions:
                  - type: latency
                    threshold_ms_high: 20
                - type: status_code
                    status_codes: [ "ERROR" , "UNSET" ]
```
I had no crash from fluent bit but I did not get any traces, because of the sampling decision.


To be able to see traces going out of fluent bit I changed the sampling decisions to
```yaml
  - name: sampling
                type: tail
                sampling_settings:
                  decision_wait: 5s
                conditions:
                  - type: latency
                    threshold_ms_high: 20
                  - type: status_code
                    status_codes: [ "ERROR" , "UNSET" ]
```

And fluent bit is now crashing and  I'm getting the following error: 

```
[2025/05/26 12:36:17] [engine] caught signal (SIGSEGV)
#0  0x57979094dfc2      in  pack_kvlist() at lib/ctraces/src/ctr_encode_msgpack.c:83
#1  0x57979094e0df      in  pack_attributes() at lib/ctraces/src/ctr_encode_msgpack.c:134
#2  0x57979094e0df      in  ctr_encode_msgpack_create() at lib/ctraces/src/ctr_encode_msgpack.c:512
#3  0x57979091da9d      in  input_trace_append() at src/flb_input_trace.c:83
#4  0x579790857aff      in  reconcile_and_dispatch_traces() at plugins/processor_sampling/sampling_tail.c:344
#5  0x579790857aff      in  cb_timer_flush() at plugins/processor_sampling/sampling_tail.c:364
#6  0x579790792475      in  flb_sched_event_handler() at src/flb_scheduler.c:624
#7  0x57979078e607      in  flb_engine_start() at src/flb_engine.c:1070
#8  0x579790767813      in  flb_lib_worker() at src/flb_lib.c:835
#9  0x790eaa8761f4      in  start_thread() at reate.c:442
#10 0x790eaa8f689b      in  clone3() at sysv/linux/x86_64/clone3.S:81
#11 0xffffffffffffffff  in  ???() at ???:0
```
