### ISSUE TITLE
JSON-formatted HTTP output generated from OTLP input is incorrect

### ISSUE THREAD

**Issue by nbroyles** [fluent/fluent-bit#10258]
## Bug Report

**Describe the bug**

Log data sent via the `opentelemetry` input plugin and output as json via the `http` output plugin is formatted incorrectly on output. OTLP input data is split across multiple JSON log records.

**To Reproduce**
- Use this FB config
```
service:
    flush: 0.2
pipeline:
    inputs:
        - name: opentelemetry
          listen: 0.0.0.0
          port: 4318
    outputs:
        - name: http
          match: '*'
          # replace host.docker.internal with 0.0.0.0 if not using docker
          host: host.docker.internal
          port: 8080
          format: json
```
- **(Optional, can just use config above directly)** Spin up a Docker container:
```
docker run -ti   -v <path/to/config/above>:/fluent-bit/etc/config.yaml:ro  -p 4318:4318 -p 2020:2020 fluent/fluent-bit:3.2.10   -c /fluent-bit/etc/config.yaml
```
-  Listen on port 8080 to dump output data from FluentBit:
```
$ while true; do nc -l 8080; done
```

- curl with [log.json](https://github.com/user-attachments/files/19917290/log.json)
```
$ curl -X POST http://localhost:4318/v1/logs -H "Content-Type: application/json" -d @log.json
```

**Expected behavior**
Single JSON recording containing OTLP metadata + log record

_Actual behavior_  (prettified output from `nc` command)
```
[
  {
    "date": 4294967295,
    "resource": {
      "attributes": {
        "service.name": "my.service"
      }
    },
    "scope": {
      "name": "my.library",
      "version": "1.0.0",
      "attributes": {
        "my.scope.attribute": "some scope attribute"
      }
    }
  },
  {
    "date": 1544712662.569566,
    "log": "Example log record"
  },
  {
    "date": 4294967294
  }
]
```
Notice that metadata/attributes are in one JSON record with an incorrect time, `logRecords[0].body` is in the next JSON record with the correct time but missing the rest of `logRecords[0]`, and the last JSON record is empty with an incorrect time.

**Screenshots**

**Your Environment**

* Version used: Tested on 3.2.10 and 4.0.0
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): Docker
* Server type and version:
* Operating System and version: MacOS
* Filters and plugins:

**Additional context**
