### ISSUE TITLE
Allow env tokens to have refresh interval

### ISSUE THREAD

**Issue by agup006** [fluent/fluent-bit#10307]
When defining a new token as an environment variable we may have situations where the env variable is updated. However the only way for Fluent Bit to get this updated value is by restarting or hot_reloading the process.

Ideally each environment variable can set it's own refresh_interval which can then be used to re-read the file or token path.

Example configuration where we create multiple environment variables
```
env:
  - name: FLUSH_INTERVAL
     value: 1
  - name: TOKEN
     path: file://mysecret.txt
     refresh_interval: 5m
```
