### ISSUE TITLE
YAML configuration not possible for Windows Exporter Metrics

### ISSUE THREAD

**Issue by alanbrito** [fluent/fluent-bit#10300]
## Bug Report

**Describe the bug**
When I try to configure the Windows Exporter Metrics with yaml configuration, it fails. According to the fluent-bit docs, the old-style configuration format is deprecated, and will not be supported by end of 2025.

**To Reproduce**
I use the following configuration (trimmed for brevity):
```
inputs:
  - name: windows_exporter_metrics
    tag: metrics_node
    scrape_interval: 15
    metrics: "cpu,cpufreq,meminfo,diskstats,filesystem,uname,stat,time,loadavg,vmstat,netdev,filefd"
    we.service.include: {"Name":"service_prefix%"}
```

- Example log message:
```
[2025/05/06 11:28:51] [error] [config] could not configure property 'we.service.include' on input plugin with section name 'windows_exporter_metrics'
```

This works fine using the old style configuration

**Expected behavior**
I would expect that since the old style configuration format is already deprecated, all plugins would support the new yaml format.

**Your Environment**

* Version used: 4.0.1
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Windows Server 2016
* Filters and plugins:

**Additional context**
