### ISSUE TITLE
SIGABRT in_systemd

### ISSUE THREAD

**Issue by tonobo** [fluent/fluent-bit#10359]
I encountered the following SIGABRT only a single time, so probably there is a race condition. Fluent-bit version provided below, one of your builds. If you need further information, the coredump still exists and I can provide further details from the actual frames, but I don't want to share the whole coredump due to possible secrete leakage

```
/opt/fluent-bit/bin/fluent-bit --version
Fluent Bit v4.0.1
```

```yaml
service:
  log_level: info
  parsers_file: ...

  http_server: true
  http_listen: 127.0.0.1
  http_port: 55139
 
  hot_reload: true

  flush: 2
  storage.type: filesystem
  storage.path: ...
  storage.metrics: true
  storage.delete_irrecoverable_chunks: true
  storage.backlog.mem_limit: 50M
  storage.total_limit_size: 200M

pipeline:
  inputs:
    - name: systemd
      db: ...
      threaded: true
      read_from_tail: true
      lowercase: true
      strip_underscores: true
      mem_buf_limit: 50m
```

```gdb
(gdb) bt
#0  0x00007faf3d3239fc in pthread_kill () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007faf3d2cf476 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007faf3d2b57f3 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007faf3de7d2e7 in log_assert_failed (text=text@entry=0x7faf3deac546 "close_nointr(fd) != -EBADF", file=file@entry=0x7faf3deac532 "src/basic/fd-util.c", line=line@entry=74, func=func@entry=0x7faf3dead038 <__PRETTY_FUNCTION__.21.lto_priv.7> "safe_close") at ../src/basic/log.c:862
#4  0x00007faf3de7ec8f in safe_close (fd=<optimized out>) at ../src/basic/fd-util.c:74
#5  safe_close (fd=125) at ../src/basic/fd-util.c:56
#6  0x00007faf3de6daed in add_any_file (j=0x7faf39a0f000, fd=<optimized out>, path=0x7faf3a7f7270 "/var/log/journal/a1cd81c0b2ca4e329a931ae64b2f9304/system.journal") at ../src/libsystemd/sd-journal/sd-journal.c:1371
#7  0x00007faf3de955ea in add_file_by_name.isra.0 (j=j@entry=0x7faf39a0f000, prefix=0x7faf39a14040 "/var/log/journal/a1cd81c0b2ca4e329a931ae64b2f9304", filename=<optimized out>) at ../src/libsystemd/sd-journal/sd-journal.c:1400
#8  0x00007faf3de6c890 in process_inotify_event (e=0x7faf3a7f7410, j=0x7faf39a0f000) at ../src/libsystemd/sd-journal/sd-journal.c:2647
#9  sd_journal_process (j=0x7faf39a0f000) at ../src/libsystemd/sd-journal/sd-journal.c:2714
#10 0x000056194b0a0c2d in in_systemd_collect (ins=ins@entry=0x7faf3c2bfa00, config=config@entry=0x7faf3c257000, in_context=in_context@entry=0x7faf39a07140) at /tmp/fluent-bit/plugins/in_systemd/systemd.c:289
#11 0x000056194b0a0f24 in in_systemd_collect_archive (ins=0x7faf3c2bfa00, config=0x7faf3c257000, in_context=0x7faf39a07140) at /tmp/fluent-bit/plugins/in_systemd/systemd.c:512
#12 0x000056194b0300eb in input_collector_fd (ins=<optimized out>, fd=<optimized out>) at /tmp/fluent-bit/src/flb_input_thread.c:166
#13 engine_handle_event (config=<optimized out>, ins=<optimized out>, mask=<optimized out>, fd=<optimized out>) at /tmp/fluent-bit/src/flb_input_thread.c:181
#14 input_thread (data=0x7faf3b0a0000) at /tmp/fluent-bit/src/flb_input_thread.c:410
#15 0x000056194b053142 in step_callback (data=0x7faf3b029180) at /tmp/fluent-bit/src/flb_worker.c:43
#16 0x00007faf3d321ac3 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#17 0x00007faf3d3b3850 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
```
