### ISSUE TITLE
Lua filter removes Resource and Scope Metadata

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-bit#10442]
## Bug Report

**Describe the bug**

When running the Lua filter - Resource and Scope Metadata, from "opentelemetry" input - is getting stripped.

**To Reproduce**

Try this code:
```
service:
  flush: 1
  daemon: "off"
  log_level: "warn"
  http_server: "off"

pipeline:
  inputs:
    - name: "opentelemetry"
      port: 4318
      logs_body_key: "message"
  filters:
    - name: "lua"
      match: "*"
      time_as_table: "true"
      script: "scripts/noop.lua"
      call: "noop"
  outputs:
    - name: "stdout"
      match: "*"
      format: json_lines
    - name: "opentelemetry"
      match: "*"
      host: otel-collector
      port: 4318
      retry_limit: false
      log_response_payload: false
      tls: "off"
      tls.verify: "off"
      logs_body_key: "message"
      logs_body_key_attributes: false
```

noop is defined as:
```
function noop(tag, timestamp, record)
    -- Return the record unmodified
    return 0, timestamp, record
end
```

When not using the Lua filter - the stdout and opentelemetry outputs show resource and scope metadata

**Expected behavior**
 Resource and Scope Metadata should not get stripped

**Your Environment**

* Version used: 4.0.3
* Configuration: See above
* Environment name and version (e.g. Kubernetes? What version?): N/A
* Server type and version: N/A
* Operating System and version: N/A
* Filters and plugins: Lua

**Additional context**
