### ISSUE TITLE
opentelemetry output - logs_body_key_attributes does not append to existing log attributes

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-bit#10445]
## Bug Report

**Describe the bug**
When using opentelemetry output, the option logs_body_key_attributes does not append to existing log attributes

**To Reproduce**
Try this config:

```
service:
  flush: 1
  daemon: off
  log_level: warn
  http_server: off

pipeline:
  inputs:
    - name: opentelemetry
      port: 4318
      logs_body_key: body
      processors:
        logs:
          - name: lua
            match: "*"
            time_as_table: true
            script: scripts/add_test_field.lua
            call: add_test_field
  outputs:
    - name: stdout
      match: "*"
      format: json_lines
    - name: opentelemetry
      match: "*"
      host: otel-collector
      port: 4318
      retry_limit: false
      log_response_payload: false
      tls: off
      tls.verify: off
      logs_body_key: body
      logs_body_key_attributes: true
```

add_test_field is defined as:
```
function add_test_field(tag, timestamp, record)
    record["new_field"] = "This is a new field from Lua"
    return 1, timestamp, record
end
```

The output to std-out shows the new_field being created.
The output to the upstream otel collector is not getting new_field appended to the log attributes

**Expected behavior**
The output to the upstream otel collector should get new_field appended to the log attributes

**Your Environment**

Version used: 4.0.4 / Branch: lua-add-group-metadata-support
Configuration: See above
Environment name and version (e.g. Kubernetes? What version?): N/A
Server type and version: N/A
Operating System and version: N/A
Filters and plugins: Lua

**Additional context**

**Comment by ryn9** [comment]
My hacky work around for now...

nest all the fields under 'body' and then under the OTEL collector sort it out.

As 'nest' is currently has issues with retaining the metadata, I will perform a nesting operation with lua using the 'lua-add-group-metadata-support' branch. I am not sure when the fix to lua (or other filters) will make it to release.
reference: https://github.com/fluent/fluent-bit/issues/10442#issuecomment-2950161595

the lua function:
```
function nest_under_body(tag, timestamp, record)
    local new_record = {}
    new_record["body"] = record
    return 1, timestamp, new_record
end

```

on the OTEL collector side:
```
  transform/nested_body_and_attributes:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(cache["body"], log.body["body"])
          - delete_key(log.body, "body")
          - merge_maps(attributes, log.body, "upsert")
          - set(log.body, cache["body"])
          - delete_key(cache, "body")
```
