### ISSUE TITLE
Support dynamic input for building up OLTP Resource Attributes (possible Lua use case?)

### ISSUE THREAD

**Issue by nefilim** [fluent/fluent-bit#10475]
For context, consider a host running: 
* Docker 
  * configured with the Fluentd logging driver
* multiple containerized services 
* Fluent Bit
  * Enriches the log with contextual information of the local environment (eg container_id)
  * full pipeline configuration at the end 

Of interest are the containerized services producing logs with log4j/logback to stdout. 

Here is an example of data flowing from service to docker and through the Fluent Bit pipeline and where the area of opportunity is. Initial log message produced by a service:

```json
{
    "@timestamp": "2025-06-13T17:23:19.876365974-06:00",
    "@version": "1",
    "message": "latency is 3ms",
    "logger": "org.home4s.lutron.leap.LutronLEAPStream",
    "thread": "io-compute-0",
    "severity": "INFO",
    "level_value": 20000,
    "home4s.bridge": "Lutron",
    "service.name": "home4s",
    "service.version": "0.10",
    "service.namespace": "homelab"
}
```

Docker Fluentd driver [restructures](https://docs.docker.com/engine/logging/drivers/fluentd/) and decorates the log:

```json
{
    "log": "{\"@timestamp\":\"2025-06-03T04:34:16.179429011Z\",\"@version\":\"1\",\"message\":\"latency is 3ms\",\"logger\":\"org.home4s.lutron.leap.LutronLEAPStream\",\"thread\":\"io-compute-0\",\"severity\":\"INFO\",\"level_value\":20000}",
    "container_id": "3286f4562f95063a7ead6b3ca46c895c2eabded97e1d81c5ed52fd545fd5828e",
    "container_name": "/home4s",
    "source": "stdout"
}
```

In the Fluent Bit pipeline use a JSON parser as processor with `Key_Name` "log" to parse the Event, along with `Reserve_Data: true` to maintain container metadata (`modify` to remove `source`). 

```json
{
    "@timestamp": "2025-06-13T17:23:19.876365974-06:00",
    "@version": "1",
    "message": "latency is 3ms",
    "logger": "org.home4s.lutron.leap.LutronLEAPStream",
    "thread": "io-compute-0",
    "severity": "INFO",
    "level_value": 20000,
    "home4s.bridge": "Lutron",
    "service.name": "home4s",
    "service.version": "0.10",
    "service.namespace": "homelab",
    "container_id": "3286f4562f95063a7ead6b3ca46c895c2eabded97e1d81c5ed52fd545fd5828e",
    "container_name": "/home4s"
}
```

Next use the `opentelemetry_envelope` processor to restructure into OTLP structure along with the `content_modifier` to populate the OTLP Resource Attributes:

```yaml
  - name: opentelemetry_envelope
  - name: content_modifier
    context: otel_resource_attributes
    action: upsert
    key: service.name
    value: event.attributes.service.name # <===== THIS IS THE PROBLEM
```

and then finally out through the `opentelemetry` output, resulting in the following (Fluent format):

```
Jun 14 21:08:18 home4s fluent-bit[3898584]: GROUP METADATA :
Jun 14 21:08:18 home4s fluent-bit[3898584]: {"schema"=>"otlp", "resource_id"=>0, "scope_id"=>0}
Jun 14 21:08:18 home4s fluent-bit[3898584]: GROUP ATTRIBUTES :
Jun 14 21:08:18 home4s fluent-bit[3898584]: {"resource"=>{"attributes"=>{"service.name"=>"event.attributes.service.name"}}, "scope"=>{}}
Jun 14 21:08:18 home4s fluent-bit[3898584]: [25] home4s:0.10: [[1749935298.081045245, {}], {"@timestamp"=>"2025-06-13T17:23:19.876365974-06:00", "@version"=>"1", "message"=>"latency is 3ms", "logger"=>"org.home4s.lutron.leap.LutronLEAPStream", "thread"=>"io-compute-1", "severity"=>"INFO", "level_value"=>20000, "home4s.bridge"=>"Lutron", "service.name"=>"home4s", "service.version"=>"0.10", "service.namespace"=>"homelab", "container_id"=>"3286f4562f95063a7ead6b3ca46c895c2eabded97e1d81c5ed52fd545fd5828e", "container_name"=>"/home4s"}]
```

The feature request centres around allowing support for a dynamic lookup for the value of `content_modifier`, in this case, specifically from the Log Attributes (supplied in the original log). 

Another possible approach would be to create a Tag for each service in the docker logging driver config and a corresponding `content_modifier  + match` for each one. 

This is not ideal because the configuration needs to manually adjusted every time a service is added or removed. More ideally, Fluent Bit could be configured once and dynamically scale as containerized services are added and removed.  Allowing dynamic lookups in the `value` for `content_modifier` should make this possible. 

Finally just a question, I never see any `metadata` in the output records, how is metadata populated in the pipeline? 

complete pipeline:

```yaml
service:
  flush: 1
  log_level: info
  parsers_file: parsers.conf

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224

      processors:
        logs:
          - name: parser
            match: '*'
            parser: log4j_json
            key_name: log
            reserve_data: 'true' # keep the docker log driver fields like 'container_id', 'container_name'
          - name: modify
            match: '*'
            Remove: source # .. but remove 'source', it's always 'stdout'
          - name: opentelemetry_envelope

          - name: content_modifier
            context: otel_resource_attributes
            action: upsert
            key: service.name
            value: log_record.attributes.service.name # <===== THIS IS THE PROBLEM

  outputs:
    - name: opentelemetry
      match: '*'
      host: otel-collector.saxonmt.casa
      port: 443
      tls: 'On'
      log_response_payload: true
      logs_body_key: message
      logs_severity_text_message_key: severity
      logs_severity_number_message_key: level_value
      logs_body_key_attributes: true
    - name: stdout
#      format: json_lines
      match: '*'
```

**Comment by ryn9** [comment]
@nefilim - Have you seen this due in 4.0.4? https://github.com/fluent/fluent-bit/pull/10457

While this would not yet take care of your use case, which looks to modify 'group' information (that is resource or scope information), it should be able to modify specific log entry information (such as log attributes,  severity text, etc..)

Perhaps provide feedback on your use case - where you are looking to alter 'group' information from log entry information.

I will note that altering 'group' information from log entry information can get a little tricky, just like when processing things with the OTEL collector, because you often deal with payloads that have multiple resource+scope contexts (what fluentbit is calling a 'group') and introducing processors that alter resource+scope information from log entry information means you need to think about how different log entry information could cause additional resource+scope combinations, forcing you to manage additional groups.  For example - in your example -  if you have 2 different logs under a resource+scope combination in a payload and they have different 'service.name' log attributes, how should this be handled? 

As I may be doing a poor job of explaining this - maybe this explains it better: https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor#transformflattenlogs

**Comment by nefilim** [comment]
@ryn9 - I believe @edsiper said during the community call that `group` will be read-only 🤷 

This transformation is really to bridge the non OTEL world into OTLP compliance - I was hoping that fluent-bit could do buffering and collapse multiple events into a single event with multiple logRecords basically by doing `windowing` + `group by resource`. Maybe this is not a realistic scenario (at scale) and it's better to just restructure (and enrich) the structured input into whatever is most efficient by the log storage system. 

Either way, I've moved on to use Vector instead and was able to do this quite easily with it's VRL DSL.

**Comment by edsiper** [comment]
@nefilim re: the primary question about being able to modify the record metadata, this is now possible in v4.0.4 through the changes done in https://github.com/fluent/fluent-bit/pull/10457, you can use the new Lua function prototype for that (more details in the PR):

```lua
function cb_metadata(tag, ts, group, metadata, record)
    -- first record with its metadata
    m1 = {foo = "meta1"}
    r1 = {msg = "first log", old_record = record}

    -- second record with its metadata
    m2 = {foo = "meta2"}
    r2 = {msg = "second log", old_record = record}

    return 1, ts, {m1, m2}, {r1, r2}
end
```

@nefilim for groups which are the way to connect with resources and scopes, this is read only in Lua since Lua today is mostly focused on records modification, however you can use [Content Modified with the OpenTelemetry contexts](https://docs.fluentbit.io/manual/pipeline/processors/content-modifier#opentelemetry-contexts) to modify those if needed.

I don't discard having a specific Lua function to mimic what is done by Content Modifier, but happy to engage in the conversation in a new issue so we can learn more about the use case

**Comment by junzebao** [comment]
I'm having similar issues here. I'm trying to use content_modifier to enrich the OTLP resource attributes with information from either tag, log itself or log attributes. It would be cool if `content_modifier` processor can support RecordAccessor syntax.

**Comment by ErmakovDmitriy** [comment]
Hi! I think that the issue should be reopened.

I have a similar use-case:

```  
inputs:
      # Receiving forwarded
      # messages from a remote
      # FluentBit which has input "systemd"
    - name: forward
      listen: 0.0.0.0
      port: 24224

      processors:
        logs:
          - name: opentelemetry_envelope
          - name: lua
            # Some LUA record modifications
            # which will define additional resource.resource_attributes
            # data based on information from the Log message.
          - name: content_modifier
            context: otel_resource_attributes
            # Here it would be really nice not only extract
            # the data using RecordAccessor
            # but also "upsert" (or replace) the whole 
            # otel_resource_attributes context data.
            action: upsert
            value: log_record.resource_attributes
```

An alternative option is to somehow allow modification of `otel_resource_attributes` from LUA.

Thank you in advance.
