### ISSUE TITLE
out_opentelemetry - group information getting mangled

### ISSUE THREAD

**Issue by ryn9** [fluent/fluent-bit#10485]
## Bug Report

**Describe the bug**
With minimal fluentbit configuration - we are seeing resource/scope group information get mangled for groups of messages

**To Reproduce**
Take input messages from OTEL collector with mixed resource/scope group information.
Output message to OTEL collector and view records.
resource/scope group information will get mangled.

**Expected behavior**
would expect resource/scope group information to work correcty.

**Your Environment**

* Version used: 4.0.4 (branch lua-add-group-metadata-support)
* Configuration:
```
service:
  flush: 1
  daemon: off
  log_level: warn
  http_server: off

pipeline:
  inputs:
    - name: opentelemetry
      port: ${FLUENTBIT_PORT}
      buffer_chunk_size: 1MB
      buffer_max_size: 10MB
      logs_body_key: body
  outputs:
    - name: stdout
      match: "*"
      format: json_lines
    - name: opentelemetry
      match: "*"
      host: otel-collector
      port: 8218
      retry_limit: false
      log_response_payload: false
      tls: off
      tls.verify: off
      logs_body_key: body
      logs_body_key_attributes: true
```

**Additional context**
Note - the json_lines output to stdout does not shows mangled group data. 
As such - I suspect the issue is with out_opentelemetry
