### ISSUE TITLE
statsd metrics incorrectly sent to influxdb

### ISSUE THREAD

**Issue by dernasherbrezon** [fluent/fluent-bit#10493]
## Bug Report

**Describe the bug**
When configuring statsd as input and influxdb as output, metrics incorrectly sent to influxdb.

**To Reproduce**

Configure pipeline:

```
pipeline:
  inputs:
    - name: statsd
      listen: localhost
      port: 8125
      metrics: On
      processors:
        metrics:
          - name: labels
            insert: hostname ${HOSTNAME}

  outputs:
    - name: stdout
      match: '*'
    - name: influxdb
      match: '*'
      host: somehost
      database: fluentbit
      org: someorg
      http_user: user
      http_passwd: password
      tag_keys: hostname
```

Send test data:

```
echo "active:10|g"  | nc -q0 -u localhost 8125
```

Stdout will output correct metric:

```
2025-06-18T15:52:25.723442810Z active{hostname="rasp-spain"} = 10
```

However influxdb now has invalid measurement:

<img width="479" alt="Image" src="https://github.com/user-attachments/assets/fea227dc-4dfd-40c3-af47-a00c2cfbe9ba" />

If I remove hostname key from labels, then fluent-bit output error:

```
2025-06-18T16:00:22.605150182Z active = 10
[2025/06/18 17:00:22] [error] [output:influxdb:influxdb.1] http_status=400
{"code":"invalid","message":"unable to parse 'active=10 1750262422605150182': invalid field format"}
```

**Expected behavior**

Take measurement name from the metric name.

**Your Environment**
* Version used: v4.0.3
* Operating System and version: raspberry pi bookworm
* Filters and plugins:

**Additional context**
