### ISSUE TITLE
Unable to limit Filesystem storage

### ISSUE THREAD

**Issue by Arunprasath2207** [fluent/fluent-bit#10494]
## Bug Report

**Describe the bug**
As mentioned [here](https://docs.fluentbit.io/manual/administration/buffering-and-storage#:~:text=Default-,storage.total_limit_size,-Limit%20the%20maximum), `storage.total_limit_size`  is intended to limit the filesystem storage, but it is not limiting the storage as expected.

**Sample Configuration file:-**

```
service:
    flush: 5
    daemon: off
    http_server: on
    http_listen: 0.0.0.0
    http_port: 2020
    log_level: debug
    scheduler.base: 3
    scheduler.cap: 30
    storage.path: /fluentbit-storage
    storage.sync: full
    storage.checksum: on
 inputs:
      - name: http
        listen: 0.0.0.0
        port: xxxx
        successful_response_code: 200
 filters:
    - name: rewrite_tag
      match: "*xyz*"
      rule: "$xyz .*xyz.* xyz.rt true"
      emitter_name: xyz_rt
      emitter_storage.type: filesystem

 outputs:
      - name: http
        match: "*xyz"
        tls: on
        tls.verify: on
        retry_limit: False
        storage.total_limit_size: 2M

```

**Space occupied by filesystem storage**

```
root@ip-xx-xxx-xxx-xxx:/fluentbit-storage/emitter.2# du -sh .
2.3M	.
```

**Steps to reproduce the problem:**

1. Deploy Fluent Bit in Kubernetes setting `storage.total_limit_size: xM` for the output.
2. Start Fluent Bit and send enough data to exceed the xMB storage limit.
3. Observe the storage usage in the path mentioned.
4. Notice that the storage usage exceeds the configured limit.

**Expected behavior**

The storage used by Fluent Bit on the filesystem should not exceed the value set in `storage.total_limit_size`. In this case, it should not exceed `2MB`, but it grows beyond this limit.

**Your Environment**

- Version used:
   Fluent Bit v3.1.7
- Environment name:
   Kubernetes 
- Filters and plugins:
1. Input: http
2. Filter: rewrite_tag
3. Output: http (with filesystem storage)

**Additional context**
This issue affects our ability to control disk usage on production systems. We rely on storage.total_limit_size to prevent Fluent Bit from consuming excessive disk space, but the current behavior allows storage to exceed the configured limit. This could lead to disk exhaustion and service disruption.
