### ISSUE TITLE
Some fluent bit internal metrics are missing / only generating sporadically

### ISSUE THREAD

**Issue by ejs-tgt** [fluent/fluent-bit#10507]
## Bug Report

I've noticed that many of the metrics fluent-bit provides from the fluentbit_metrics input are not being consistently generated and can be missing for long periods of time despite evidence that there should be.

For example `fluentbit_input_bytes_total` and `fluentbit_input_records_total` will not generate any data at all, despite numerous records printing via the output plugins successfully that came through input plugins

I am outputting these via both the `prometheus_remote_write` and `opentelemetry` plugins but appear to observe the same result from both. 

**To Reproduce**

Use `fluentbit_metrics` plugin. 

**Expected behavior**

All `fluentbit_metrics` fields generating data at each interval

**Your Environment**
* Version used: 4.0.1 
* Configuration: 

```
pipeline:
    inputs:
        - name: fluentbit_metrics
          tag: internal_metrics
          scrape_interval: 10

        - name: http
          listen: 0.0.0.0
          port: 443
          tag: redfish

    outputs:
        - name: prometheus_remote_write
          match: 'internal_metrics'
          host: '[REDACTED]'
          port: 443
          uri: "[REDACTED]"
          log_response_payload: true

        - name: opentelemetry
          match: internal_metrics
          host: [REDACTED]
          port: [REDACTED]

        - name: 'stdout'
          match: 'redfish'
          format: 'json'
```
* Environment name and version

?

* Server type and version:

Docker 24.0.7

* Operating System and version:

Official fluent-bit provided docker image (amd64)

* Filters and plugins:

input: fluentbit_metrics, http
output: prometheus_remote_write, opentelemetry, stdout

**Additional context**

The lack of metrics makes it impossible to see the traffic load and health of the http input plugin.

* All `fluentbit_input_*`, `fluentbit_filter_*`, and `fluentbit_output_*` metrics are only generated sporadically, and are often missing for *long* periods of time
* With exception of: 
  * `fluentbit_input_metrics_scrapes_total` which is generating without issue every interval
  * `fluentbit_filter_*` and `fluentbit_output_*` are generating `records_total`/`bytes_total` metrics at every interval without issue
