### ISSUE TITLE
fluentbit.io/exclude works only on newly created pods

### ISSUE THREAD

**Issue by ialidzhikov** [fluent/fluent-bit#1142]
## Bug Report

**Describe the bug**

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
1. Start fluent-bit as daemon set.
2. Apply the following pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: logger
  namespace: default
spec:
  containers:
      - name: logger
        image: k8s.gcr.io/logs-generator:v0.1.1
        args:
          - /bin/sh
          - -c
          - |-
            /logs-generator --logtostderr --log-lines-total=${LOGS_GENERATOR_LINES_TOTAL} --run-duration=${LOGS_GENERATOR_DURATION}

            # Sleep forever to prevent restarts
            while true; do
              sleep 3600;
            done
        env:
        - name: LOGS_GENERATOR_LINES_TOTAL
          value: 100000
        - name: LOGS_GENERATOR_DURATION
          value: 600s
```
3. Annotate the pod to exclude logs:
```bash
$ kubectl annotate po logger fluentbit.io/exclude=true
```
4. Ensure that fluent-bit local cache is not invalidated and the newly added `fluentbit.io/exclude=true` is ignored => fluent-bit continues to stream logs from this pod. This is because `kubectl annotate` does not lead to pod restart. This behaviour also is not described in the docs, a warning could be added.

**Expected behavior**

Fluent-bit to stop process logs from the pod once after it is annotated.

**Screenshots**

**Your Environment**

* Version used: 1.0.4
* Configuration:
```
[SERVICE]
        Flush           30
        Daemon          Off
        Log_Level       warn
        Parsers_File    parsers.conf

[INPUT]
        Name              tail
        Tag               kubernetes.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     12MB
        Refresh_Interval  10
        ignore_older      1800s

[OUTPUT]
        Name            stdout
        Match           *

[FILTER]
        Name                kubernetes
        Match               kubernetes.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Buffer_Size         1M
        Merge_Log           On
        K8S-Logging.Parser  On
        K8S-Logging.Exclude On
        Annotations         Off
        tls.verify          Off
```
* Environment name and version (e.g. Kubernetes? What version?): K8S version 1.12.5
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by ialidzhikov** [comment]
Also `fluentbit.io/exclude` is unusable with `StatefulSet`s:
1. Apply the following sts:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: logger
  namespace: default
spec:
  serviceName: logger
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      nodeSelector:
        kubernetes.io/hostname: #put a node name here
      containers:
      - name: logger
        image: k8s.gcr.io/logs-generator:v0.1.1
        args:
          - /bin/sh
          - -c
          - |-
            /logs-generator --logtostderr --log-lines-total=${LOGS_GENERATOR_LINES_TOTAL} --run-duration=${LOGS_GENERATOR_DURATION}

            # Sleep forever to prevent restarts
            while true; do
              sleep 3600;
            done
        env:
        - name: LOGS_GENERATOR_LINES_TOTAL
          value: "100000"
        - name: LOGS_GENERATOR_DURATION
          value: "600s"
```

2. Ensure that fluent-bit does not exclude the sts pod `logger-0`
3. Edit the sts and add `fluentbit.io/exclude: "true"`:
```bash
$ kubectl edit sts logger
statefulset.apps/logger edited
```

4. Ensure that `fluentbit.io/exclude: "true"` is ignored and fluent-bit continues to receive events from the newly created pod `logger-0`. Note that the sts has a `nodeSelector` that makes it easy to spawn the pod in the same node (=> fluent-bit) to reproduce more clearly this issue.
