### ISSUE TITLE
[DOC] Rejecting mapping

### ISSUE THREAD

**Issue by BentCoder** [fluent/fluent-bit#1377]
Hi,

Sorry this is not a bug. The doc is not clear so I had to bring this up here.

As you can see below, I have two indexes (`hello_php` and `hello_nginx`). I actually want to use one index for both of them (`hello`). However, when I do that I get error below. Is there a solution to this? Also duplicated output blocks look ugly so if there is clever way then please suggest otherwise I can live with it.

Thanks

> {"took":22,"errors":true,"items":[{"index":{"_index":"hello","_type":"php","_id":"tmsgSGsBl0rRw1WbjCMM","status":400,"error":{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [hello] as the final mapping would have more than 1 type: [nginx, php]"}}}]}

**fluent-bit.conf**
```conf
[SERVICE]
    Flush     5
    Daemon    Off
    Log_Level debug

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

# PHP
[OUTPUT]
    Name  es
    Match hello_php
    Host  elasticsearch
    Port  9200
    Index hello_php
    Type  php

# NGINX
[OUTPUT]
    Name  es
    Match hello_nginx
    Host  elasticsearch
    Port  9200
    Index hello_nginx
    Type  nginx

```

**docker-compose.yaml**

```yaml
version: "3.4"

services:

    hello_php:
      image: ...
      hostname: "hello-php"
      ...
      logging:
        driver: "fluentd"
        options:
          tag: "hello_php"
          mode: "non-blocking"
          max-buffer-size: "2m"

    hello_nginx:
      image: ...
      hostname: "hello-nginx"
      ...
      logging:
        driver: "fluentd"
        options:
          tag: "hello_nginx"
          mode: "non-blocking"
          max-buffer-size: "2m"
```
