### ISSUE TITLE
Append DeviceIP to Syslog Input

### ISSUE THREAD

**Issue by kkniffin** [fluent/fluent-bit#1413]
**Is your feature request related to a problem? Please describe.**
Sorry if this is already a feature and I am unaware. 

In FluentD there was the ability that if HostA was sending syslog data to FluentD it would add the IP of HostA to the record upon connection. I do not see a similar option with Fluentbit. I found the record_modifier ${Hostname} but that simply adds the hostname of the server that Fluentbit is running on and not the connecting device.

**Describe the solution you'd like**
Ability to have Fluentbit add the IP of the sending device to the stream.

**Comment by ntavares** [comment]
What a timing eheh. I just came across a bunch of devices with a poor syslog implementation, that does not include the hostname (among other stuff)... which means I get a lot of messages and I have no way to know which device they belong tooo (do I?). @edsiper is there any similar feature, or any chance we get this implemented?

**Comment by agup006** [comment]
closing out some old issues, we do have the ability to add hostname via `record_modifier`
```
[FILTER]
    Name record_modifier
    Match *
    Record hostname ${HOSTNAME}
```

Feel free to re-open if more help is needed

**Comment by ntavares** [comment]
@agup006 this issue was about the 'connecting device' (IP) rather than hostname, as we've explained in the comments. Mind reopening please?

**Comment by agup006** [comment]
@ntavares apologies I read to fast and completely missed the ask.

**Comment by Irrational-NX** [comment]
We're missing this feature as well.
We're trying to send all our syslog logs to the port 514 of fluentbit, but because some equipements doesn't include their hostname/IP in the message, we're stuck

**Comment by q2dg** [comment]
I've found a very ugly work-around: assigning to an environment variable the output of _hostname -I_ command and then use this variable in record_modifier filter.

**Comment by pawansingal** [comment]
I am also seeing the need for this feature. Not sure if this is already available and I am not aware of it. If someone can point out.

**Comment by thepacmanfan** [comment]
This has been added as a feature! The parameter is Source_Address_Key, and is currently documented at the bottom of the configuration parameter table here: https://docs.fluentbit.io/manual/pipeline/inputs/syslog
I set it to source_host, and the ip address of the device sending remote syslogs to the FB syslog input is being added to the log line before it's passed to outputs.

**Comment by brunooliveiramac** [comment]
Im not properly getting the client IP
```
{
	"@timestamp": 1702326219.152389,
	"message": "This is my TCP message",
	"remote_addr": "tcp://127.0.0.6:52685"
}
```
Im using Google Cloud Kubernetes and exposing my fluent bit using a service type load balancer:

```
apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
  labels:
    app: fluent-bit
  annotations:
    cloud.google.com/l4-rbs: "enabled"    
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: fluent-bit
      port: 24224
      targetPort: 24224
      protocol: TCP
    - name: http
      port: 2020
      targetPort: 2020
      protocol: TCP
    - name: tcp
      port: 514
      targetPort: 514
      protocol: TCP
    - name: udp
      port: 514
      targetPort: 514
      protocol: UDP
  selector:
    app: fluent-bit
```

 I set the externalTrafficPolicy: Local, to preserve the client IP but doesn't seems to be working anyway.
 Would some of you have any idea.
