### ISSUE TITLE
Getting parser error on any message

### ISSUE THREAD

**Issue by Imunhatep** [fluent/fluent-bit#1468]
## Bug Report

Sending any message (string, int, json array e.t.c.) to fluent-bit I see a debug message in logs:
```
[debug] [in_fw] parser: expecting an array (type=2), skip.
```

But if I create a pipe like FluentD -> Fluent-bit and try to send the same message to FluentD, everything works as expected and I can see the output on fluent-bit side.

##### Steps to reproduce the problem: 

Send msg and watch logs:
```bash
echo -n '["gelf.1", 1564060796, {"short_message": "test message to FluentD"}]' | nc -w 1 localhost 24224

echo -n '["gelf.1", 1564060796, {"short_message": "test message to Fluent-Bit"}]' | nc -w 1 localhost 24225
```

**Expected behavior**
Fluent-bit should output 2 messages

* Version used: 1.2.2

* Configuration:
docker-compose.yaml
```yaml
version: '2.3'
services:
  fluent-bit:
    restart: always
    image: fluent/fluent-bit:latest
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - 24225:24224

fluentd:
    restart: always
    image: fluent/fluentd:edge
    volumes:
      - ./fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 24224:24224
```
fluent.conf
```
## TCP input
<source>
  @type forward
  port  24224
</source>

<filter **>
  @type stdout
</filter>

<match **>
    @type forward

    <buffer>
      @type memory

      chunk_limit_size    5m
      chunk_limit_records 4096
      flush_mode          interval
      flush_interval      10s
      flush_at_shutdown   true
      retry_type          periodic
      retry_wait          1s
      retry_forever       true
    </buffer>

    <server>
      host fluent-bit
      port 24224
    </server>
</match>
```

fluent-bit.conf
```
    [SERVICE]
        Flush        5
        Daemon       off
        Log_Level    debug
        HTTP_Server  On
        HTTP_Listen  0.0.0.0
        HTTP_PORT    2020

    [INPUT]
        Name              forward
        Listen            0.0.0.0
        Port              24224
        Buffer_Chunk_Size 128KB
        Buffer_Max_Size	  1024KB

    [OUTPUT]
        Name        stdout
        Match       *
```

Am I missing something?
