### ISSUE TITLE
udp socks default permission

### ISSUE THREAD

**Issue by mhf-ir** [fluent/fluent-bit#1493]
##  Feature request 

**Describe**
Mount input syslog define permission as default.
I use fluentbit as host log collector and i need to mount the unix syslog as input of logs for example on real world use case:
```yaml
version: '3'
services:

  nginx:
    image: nginx:1
    volumes:
      - ./nginx:/etc/nginx
      - /run/fluentbit.nginx_error.sock:/run/fluentbit.nginx_error.sock
      - /run/fluentbit.nginx_access.sock:/run/fluentbit.nginx_access.sock
```

in fluent:
```
[INPUT]
  Name syslog
  Tag nginx_access
  Parser syslog-rfc3164
  Path /run/fluentbit.nginx_access.sock
  Mode unix_udp
```
Nginx give permission error on default permision of sock file.
After correct permission work well.
How tel fluentbit about permission of this file to start as 0777

**Expected behavior**
Can add permission config for unix file Like:

```
[INPUT]
  Name syslog
  Tag nginx_access
  Parser syslog-rfc3164
  Path /run/fluentbit.nginx_access.sock
  Mode unix_udp
  Permission 0777 # < SAMPLE
```
