### ISSUE TITLE
Flushing buffered data at shutdown

### ISSUE THREAD

**Issue by musaprg** [fluent/fluent-bit#1496]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace fluentd to fluent-bit for reducing container size, but fluent-bit seem not to flush data in buffer when shutting down. Is there any feature like [`flush_at_shutdown`](https://docs.fluentd.org/configuration/buffer-section) in fluent-bit?

**Describe the solution you'd like**
**Describe alternatives you've considered**
**Additional context**

**Comment by edsiper** [comment]
are you using the storage file system type ?, please share your full config

**Comment by musaprg** [comment]
My configuration file is below. I try to receive log data from fluent-logger by fluent-bit sidecar container and forward it to fluentd container.

```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name    forward
    Listen  0.0.0.0
    Port    24224
    Buffer_Chunk_Size 32KB
    Buffer_Max_Size   64KB

[OUTPUT]
    Name  forward
    Match *
    Host  fluentd
```

FYI: my docker-compose.yml is below
```
version: '3'
services:
  app:
    build: .
  fluent-bit:
    image: fluent/fluent-bit:1.2
    volumes:
    - .:/fluent-bit/etc
  fluentd:
    image: fluent/fluentd:v1.6
    volumes:
    - .:/fluentd/etc
```
