### ISSUE TITLE
Tail path for /var/log/pods/POD_UID/CONTAINER_NAME/*.log throws invalid pattern 

### ISSUE THREAD

**Issue by y0zg** [fluent/fluent-bit#1535]
## Bug Report

**Describe the bug**
I want to capture logs from path /var/log/pods/*/*/*.log but based on documentation it's not clear whether this is possible

**To Reproduce**

1. `helm fetch stable/fluent-bit --untar`
2. Modify `values.yaml` path 

```
input:
  tail:
    memBufLimit: 5MB
    parser: docker
    path: /var/log/pods/*/*/*.log
  systemd:
    enabled: false
    filters:
      systemdUnit:
        - docker.service
        - kubelet.service
        - node-problem-detector.service
    maxEntries: 1000
    readFromTail: true
    tag: host.*
```
3. 
`helm install --name fluentbit stable/fluent-bit -f fluent-bit/values.yaml --set backend.es.host=targer.server.path`

**ERROR:**
```
[2019/08/27 10:28:41] [ warn] [filter_kube] invalid pattern for given tag kube.var.log.pods.ad7566ef-c35d-11e9-936a-ee2ce51991c9.couchdb.0.log

```
I can tail `/var/log/pods/POD_UID/*/*.log` with **filebeat** with below config but I don't find any reference for POD UID  for **fluentbit**
```
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          include_pod_uid: true
          in_cluster: true
          hints.enabled: true
          include_annotations: '*'
          templates:
            - condition.regexp:
                kubernetes.container.name: '.+'
              config:
                - type: docker
                  combine_partial: true
                  cri.parse_flags: true
                  cri.force: true
                  containers:
                    path: "/var/log/pods/${data.kubernetes.pod.uid}/"
                    ids:
                      - "${data.kubernetes.container.name}"
```
