### ISSUE TITLE
kubernetes filter: get image from container status

### ISSUE THREAD

**Issue by gorilych** [fluent/fluent-bit#1763]
**Is your feature request related to a problem? Please describe.**

At the moment, kubernetes filter plugin only takes `containerID` and `imageID` fields from `containerStatuses` and `initContainerStatuses`.

So, having this information in k8s

```
  containerStatuses:
  - containerID: docker://b52947b08ca2e6f9f39bcdc92d943f3beb6cd5f0812b4a82b07788c94f16fa3b
    image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.26.1
    imageID: docker-pullable://quay.io/kubernetes-ingress-controller/nginx-ingress-controller@sha256:d0b22f715fcea5598ef7f869d308b55289a3daaa12922fa52a1abf17703c88e7
```

only `b52947b08ca...` and `.../nginx-ingress-controller@sha256:d0b22f7...` will be attached to log record, but not `.../nginx-ingress-controller:0.26.1`

So the problem is that we can't search in logs by image tag later.

**Describe the solution you'd like**

It makes sense to take `image` field as well, because it contains image tag. Image hash is valuable information, but not so descriptive.

It seems quite easy to add processing for `image` into `extract_container_hash()` in https://github.com/fluent/fluent-bit/blob/master/plugins/filter_kubernetes/kube_meta.c
