### ISSUE TITLE
[needs #1672] Add option to validate configuration

### ISSUE THREAD

**Issue by megamorf** [fluent/fluent-bit#1787]
**Is your feature request related to a problem? Please describe.**

It seems fluent-bit is missing the capability to only test its config file (and the files it recursively includes) for valid syntax. 

At the moment when I deploy a configuration I have to restart fluent-bit and hope that everything works and if there is an issue with the config fluent-bit could halt with the risk of losing event records. 

**Describe the solution you'd like**

In order to prevent unwanted downtimes I'd like to use the fluent-bit binary to validate the configuration after an update (be it via config management or manually). The service should only be attempted to be restarted (by my orchestration of choice) if the config check is considered successful.

Many applications allow you to check if their configuration contains errors, e.g.:
* `nginx -c /etc/nginx/nginx.conf -t`
* `apachectl configtest`

**Describe alternatives you've considered**

The only issue that's somewhat similar is #252 but does not offer a solution.

**Additional context**

```
OS: 
    CentOS 7

[Fluent Bit]
    Edition             Community Edition
    Version             1.3.3
```

Here's an example Ansible playbook:

```yml
- hosts: loadbalancers
  become: yes

  handlers:
    - name: Restart fluent-bit
      service:
        name: td-agent-bit
        state: restarted
        enabled: yes

  tasks:
    - name: Add fluent-bit repo
      yum_repository:
        name: TD Agent Bit
        file: td-agent-bit
        baseurl: http://packages.fluentbit.io/centos/7
        enabled: true
        gpgkey: http://packages.fluentbit.io/fluentbit.key
        gpgcheck: true

    - name: Install latest version of fluent-bit
      yum:
        name: td-agent-bit
        state: latest

    - name: Ensure fluent-bit is running
      systemd:
        name: td-agent-bit
        enabled: true
        state: started

    - name: Deploy fluent-bit config
      template:
        src: "templates/{{ item }}.j2"
        dest: "/etc/td-agent-bit/{{ item }}"
        owner: root
        group: root
        mode: 0644
        validate: "/opt/td-agent-bit/bin/td-agent-bit --check"
      loop:
        - td-agent-bit.conf
        - output-gelf.conf
      notify: Restart fluent-bit
```
