### ISSUE TITLE
Included CRI format parser breaks Kubernetes filter annotation parsers

### ISSUE THREAD

**Issue by FallenWarrior2k** [fluent/fluent-bit#2095]
## Bug Report

**Describe the bug**

The Kubernetes filter expects the actual log line to be in a field named `log`, since that's what Docker uses. The CRI parser shipped with fluent-bit, however, emits a field named `message`, as you can see [here](https://github.com/fluent/fluent-bit/blob/cb0babaf634c1e97dd72cd8711a57f4ff8c8879b/conf/parsers.conf#L106).

**To Reproduce**
- Example log message if applicable (uses Logfmt format):
```
2020-04-10T00:01:02.931087621Z stdout F key1=value1 key2=value2
```
- Steps to reproduce the problem:
  - On a Kubernetes cluster running on containerd, set up fluent-bit with its Kubernetes filter and set the input parser to `cri`. Send the output somewhere you can easily see it, e.g. to a `netcat`/`nc` instance running in your shell via TCP output.
  - Annotate some pod that logs structured messages with a fitting `fluentbit.io/parser` value.
  - You won't see the parsed fields on incoming records.

**Expected behavior**

The parser set via annotation should work on non-Docker hosts as well.

**Your Environment**

* Version used: 1.3.7
* Environment name and version (e.g. Kubernetes? What version?): k3os v0.9.1 (Kubernetes v1.17.2)
* Filters and plugins: Kubernetes filter, Tail input plugin

**Additional context**

As expected, creating a custom regex parser that renames the `message` capture group to `log` and using that to parse container logs creates the expected fields. The full regex used is
```
^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
```

I understand that simply renaming a field like would be a breaking change, but with a regex like the following, both field names could be emitted.
```
^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>(?<message>.*))$
```

**Comment by obeyler** [comment]
same pb, do you find a solution for this?

**Comment by FallenWarrior2k** [comment]
I added a custom parser that was essentially the same as the provided parser but with the modified regex included in my original post, i.e. like this:
```
[PARSER]
    Name containerd
    Format regex
    Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$
    Time_Key time
    Time_Format %Y-%m-%dT%H:%M:%S.%L%z
    Time_Keep On
```

**Comment by obeyler** [comment]
Thanks @FallenWarrior2k  could you post you full config map to avoid error ?

**Comment by FallenWarrior2k** [comment]
I used the stable/fluent-bit Helm chart when I encountered this issue. Here's the relevant parts from my values.yml:
```
input:
    tail:
        parser: containerd
parsers:
    enabled: true
    regex:
        - name: containerd
          regex: '^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<log>.*)$'
          timeKey: time
          timeFormat: "%Y-%m-%dT%H:%M:%S.%L%z"
          timeKeep: true
```
