### ISSUE TITLE
`modify` filter does not respect nested keys

### ISSUE THREAD

**Issue by astorath** [fluent/fluent-bit#2152]
## Bug Report

**Describe the bug**

`modify` filter does not respect nested keys

**To Reproduce**
- Config:
    ```
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    debug
        Parsers_File parsers.conf

    [INPUT]
        Name             tail
        Path        /log.json

    [FILTER]
        Name parser
        Match *
        Key_Name log
        Parser test

    [FILTER]
        Name  modify
        Match *

        Condition Key_exists           json

        Copy        json.Message      log

    [OUTPUT]
        Name  stdout
    ```
- Example log message if applicable:
```
{ "json": { "Message": "HttpClientTracingProvider:: Class is receiving HTTP Response from  using .: StatusCode=200 Elapsed=00:00:00.0078867 ResponseHeaders={$Headers} ResponseBody={$Body}" } }
```
- Steps to reproduce the problem:
Just run fluent-bit with config attached.

**Expected behavior**

`json.Message` contents should be copied to `log` key.

**Screenshots**

![image](https://user-images.githubusercontent.com/6577390/80923475-ba5fcd80-8d8c-11ea-9412-f69c1ffb4dce.png)

**Your Environment**

* Version used: 1.3.7, 1.4.3
* Configuration: provided above
* Environment name and version (e.g. Kubernetes? What version?): docker 19.03.8
* Server type and version: -
* Operating System and version: MacOS 10.15
* Filters and plugins: -

**Additional context**

Non-nested keys are working fine

**Comment by mshade** [comment]
Can confirm this still does not work on v1.5.2. What I'm doing to work around, for now, is using the `nest` filter to `lift` records up and then process with `rename`. This isn't optimal, though, as I'd ideally only like to lift 1 or 2 keys rather than the whole nested structure.

**Comment by vinodkmrm** [comment]
Does not work in v1.5.2 too. I had to use the same workaround.

**Comment by trnl** [comment]
Anyone found a way out? Any relation with https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/record-accessor?

**Comment by vladimir259** [comment]
The issue still exist in 1.7 :-(

**Comment by maximchukm** [comment]
I've found out a more effective workaround for this issue than using nest filter, you can use instead the Lua filter https://docs.fluentbit.io/manual/pipeline/filters/lua with a script like this:
```
function label_key_rename(tag, timestamp, record)
    local old_key, new_key = "oldKey", "newKey"

    local labels = record["kubernetes"]["labels"]
    local new_record = record
    local code = 0

    if labels[old_key] ~= nil then
        code = 1
        local new_labels = {}
        for key, value in pairs(labels) do
            if key == old_key then key = new_key end
            new_labels[key] = value
        end
        new_record["kubernetes"]["labels"] = new_labels
    end

    return code, timestamp, new_record
end
```

**Comment by astorath** [comment]
> I've found out a more effective workaround for this issue than using nest filter, you can use instead the Lua filter https://docs.fluentbit.io/manual/pipeline/filters/lua with a script like this:
> 

I'm a bit concerned about using lua - the main point of using fluent-bit in place of fluentd is performance. Falling back to scripting somewhat defeats this advantage. Am I wrong?

**Comment by maximchukm** [comment]
> > I've found out a more effective workaround for this issue than using nest filter, you can use instead the Lua filter https://docs.fluentbit.io/manual/pipeline/filters/lua with a script like this:
> 
> I'm a bit concerned about using lua - the main point of using fluent-bit in place of fluentd is performance. Falling back to scripting somewhat defeats this advantage. Am I wrong?

Sure, native C implementation still will be faster. But using lua script with straight logic is much better both from readability and performance points than juggling with "nest" plugin (one operation per field instead of 3+)

**Comment by isaccavalcante** [comment]
Still a valid issue, commenting so this doesn't get closed.

**Comment by mattwhittingham** [comment]
Not sure how you would support this perfectly without a new parameter with a json path.   I've used nest like this, hopefully this helps people.  

```
    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        kubernetes
        Add_prefix          temp_l1_

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           lift
        Nested_under        temp_l1_labels
        Add_prefix          temp_l2_

    [FILTER]
        Name                modify
        Match               kube.*
        Rename              temp_l2_label1 label1
        Rename              temp_l2_label2 label2

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           nest
        Wildcard            temp_l2_*
        Nest_under          temp_l1_labels
        Remove_prefix       temp_l2_

    [FILTER]
        Name                nest
        Match               kube.*
        Operation           nest
        Wildcard            temp_l1_*
        Nest_under          kubernetes
        Remove_prefix       temp_l1_
```

**Comment by scila1996** [comment]
I have the same issue !

Input

```
{
  "method":"POST",
  "remoteAddr":"1.2.3.4",
  "user":{"group": ["a", "b", "c"]}
}
```

```
    [FILTER]
        Name    record_modifier
        Match   app.log
        Remove_key  remoteAddr
        Remove_key  user.group
```

Remove the nested key `user.group` not work

**Comment by amitjoseph** [comment]
This issue is still valid, why isn't this issue not labeled as a bug?

**Comment by data-dude** [comment]
Still a problem.  I'd like to remove some kubernetes.examplekey but the filter doesn't respect nested keys.  record_modifier has the same problem

**Comment by dFurman** [comment]
> Still a problem. I'd like to remove some kubernetes.examplekey but the filter doesn't respect nested keys. record_modifier has the same problem

I encountered a similar issue and i managed to resolve it using a super simple lua script, hope it helps:
`function remove_k8s_labels_annotations(tag, timestamp, record)
      record['kubernetes']['labels'] = nil
      record['kubernetes']['annotations'] = nil

      return 2, timestamp, record
    end`

and you use it like this:
`[FILTER]
        Name    lua
        Match   kube.*
        script  functions.lua
        call    remove_k8s_labels_annotations`

**Comment by data-dude** [comment]
@dFurman Thanks for the tip

**Comment by alt-dima** [comment]
But you can simply turn it off

```
[FILTER]
    Name                kubernetes
    Labels              Off
    Annotations         Off
```

> > Still a problem. I'd like to remove some kubernetes.examplekey but the filter doesn't respect nested keys. record_modifier has the same problem
> ```
> function remove_k8s_labels_annotations(tag, timestamp, record)
>       record['kubernetes']['labels'] = nil
>       record['kubernetes']['annotations'] = nil
> ```

**Comment by antoniocascais** [comment]
Having the same problem as explained in this issue.

My use case: we have a field (that comes from kubernetes audit logs, so we can't modify the source) where `record["foo"]["bar"]` sometimes is a specific string and other times is a json object. Because of this, Opensearch complains and rejects the log.

Our idea is to modify the record. Something like 
```
if record["foo"]["bar"]=string then 
  modify record to record["foo"]["custom"]["bar"]
end
```

I know this can be done with a Lua script, but it would be much more readable (and less error prone) to do it via the modify filter.

Any plans on adding this feature to `modify`?

**Comment by mjiderhamn** [comment]
Please note that fixing this could have side effects.

For example, with ElasticSearch there will be an error if for some entries `foo` has nested values and for some it is a string; i.e. `object mapping for [foo] tried to parse field [foo] as object, but found a concrete value`.

Currently, this can be avoided by renaming keys with a string value like so
```
      [FILTER]
          Name modify
          Rename foo bar
          Condition Key_exists foo
```

**Comment by data-dude** [comment]
> > Still a problem. I'd like to remove some kubernetes.examplekey but the filter doesn't respect nested keys. record_modifier has the same problem
> 
> I encountered a similar issue and i managed to resolve it using a super simple lua script, hope it helps:
> 
> ```
> function remove_k8s_labels_annotations(tag, timestamp, record)
>       record['kubernetes']['labels'] = nil
>       record['kubernetes']['annotations'] = nil
> 
>       return 2, timestamp, record
>     end
> ```
> 
> and you use it like this:
> 
> ```
> [FILTER]
>         Name    lua
>         Match   kube.*
>         script  functions.lua
>         call    remove_k8s_labels_annotations
> ```

Yea that might work for some people.  I found the easiest was to set the kubernetes plugin filter to annotations off and lables off
See docs for more details:
https://docs.fluentbit.io/manual/pipeline/filters/kubernetes

**Comment by data-dude** [comment]
my workaround was nest nest nest and then delete

**Comment by helmut72** [comment]
Also an issue for me. Fortunately a lift worked in this case, but isn't always possible.

**Comment by slyt** [comment]
This issue still exists. I was able to lift then copy into the destination fields but this leaves a fairly hacky config file to maintain down the road.

Example YAML config:
```yaml
pipeline:
  inputs:
    - name: tail # https://docs.fluentbit.io/manual/pipeline/inputs/tail
      path: /var/log/containers/*.log
      multiline.parser: docker, cri
      tag: kube.*
      skip_long_lines: Off
  filters:
    - name: kubernetes # https://docs.fluentbit.io/manual/pipeline/filters/kubernetes
      match: kube.*
      merge_log: On
      keep_log: Off
      k8s-logging.parser: On
      k8s-logging.exclude: On
    - name: nest
      match: kube.*
      operation: lift
      nested_under: kubernetes
      add_prefix: kubernetes_
    - name: nest
      match: kube.*
      operation: lift
      nested_under: kubernetes_labels
      add_prefix: kubernetes_labels_
    - name: modify
      match: kube.*
      copy: 'kubernetes_namespace_name labels.namespace'
      copy: 'kubernetes_host labels.node'
      copy: 'kubernetes_pod_name labels.pod'
      copy: 'kubernetes_labels_app labels.application'
      copy: 'kubernetes_labels_app.kubernetes.io/name labels.application'
      copy: 'kubernetes_labels_k8s-app labels.application'
      copy: 'kubernetes_labels_app.kubernetes.io/component component'
      copy: 'kubernetes_labels_component component'
      copy: 'kubernetes_container_name container.name'
      copy: 'kubernetes_docker_id container.id'
      copy: 'kubernetes_container_image container.image.name'
      rename: 'msg message'
      rename: 'log message'
    - name: stdout
      match: kube.*
      format: json_lines
```
