### ISSUE TITLE
Alpine + Docker: Segfault with Input CPU and Output Fluentd

### ISSUE THREAD

**Issue by mirosval** [fluent/fluent-bit#223]
Using the default alpine-based fluentd image and fluent-bit image from the [here](https://github.com/fluent/fluent-bit-docker-image) and the following configuration, I get a segfault in fluent bit:

```zsh
Creating network "fluentbit_default" with the default driver
Creating fluentbit_fluentd_1
Creating fluentbit_fluentbit_1
Attaching to fluentbit_fluentd_1, fluentbit_fluentbit_1
fluentd_1    | 2017-04-03 15:52:00 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
fluentbit_1  | Fluent-Bit v0.11.0
fluentd_1    | 2017-04-03 15:52:00 +0000 [info]: starting fluentd-0.12.32
fluentbit_1  | [2017/04/03 15:52:01] [ info] [engine] started
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.3'
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: gem 'fluent-plugin-record-reformer' version '0.9.0'
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: gem 'fluentd' version '0.12.32'
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: adding match pattern="**" type="stdout"
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: adding source type="forward"
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: using configuration file: <ROOT>
fluentd_1    |   <source>
fluentd_1    |     @type forward
fluentd_1    |     bind 0.0.0.0
fluentd_1    |     port 24224
fluentd_1    |   </source>
fluentd_1    |   <match **>
fluentd_1    |     @type stdout
fluentd_1    |   </match>
fluentd_1    | </ROOT>
fluentd_1    | 2017-04-03 15:52:01 +0000 [info]: listening fluent socket on 0.0.0.0:24224
fluentbit_fluentbit_1 exited with code 139
```

fluent-bit.conf
```conf
[SERVICE]
    Flush     1
    Daemon    Off
    Log_Level debug

[INPUT]
    Name        cpu
    Tag         cpu_usage

[OUTPUT]
    Name        forward
    Match       *
    Host        fluentd
    Port        24224
```

fluent.conf
```conf
<source>
  @type forward
  bind 0.0.0.0
  port 24224
</source>

<match **>
  @type stdout
</match>
```

docker-compose.yml
```yaml
version: '3'
services:
    fluentbit:
        build: fluentbit
        links:
            - fluentd
        volumes:
            - "./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf"
    fluentd:
        build: fluentd
        expose:
            - "24224"
        ports:
            - "24224:24224"
        volumes:
            - "./fluentd/fluent.conf:/fluentd/etc/fluent.conf"
```

It does not happen when the output in fluentbit is set to stdout, so I suspect it is the fluentbit-fluentd connection causing this. Further I have observed corruption of the messages in some cases, which leads me to believe that the problem is caused by reading beyond the end of an array. 

My hypothesis: this could be caused by how floats are serialized, because we observe floats with 1-4 decimal places so it could be that they are counted as constant width when in fact they are variable width.

Please let me know if you need further info.
