### ISSUE TITLE
Unable to install following walkthrough on website.

### ISSUE THREAD

**Issue by matty1979** [fluent/fluent-bit#2230]
## Bug Report

**Describe the bug**
Unable to install following documentation  

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
error: unable to recognize "https://raw.githubusercontent.com/fluent/fluent-bit-kubernetes-logging/master/output/elasticsearch/fluent-bit-ds-minikube.yaml": no matches for kind "DaemonSet" in version "extensions/v1beta1"
```
- Steps to reproduce the problem:
Minikube running 
Walked through the steps on the document 
**Expected behavior**
Should install as written 

**Your Environment**

* Version used: 
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes Client v.17.4 Server v.18.2
* Server type and version: Minikube v1.10.1
* Operating System and version: Mac Darwin 19.4.0 
* Filters and plugins:

**Additional context**
Unable to install to work locally

**Comment by matty1979** [comment]
Replacing the v1beta to apps/v1 

`error: error validating "fluent-bit-ds-minikube.yaml": error validating data: ValidationError(DaemonSet.spec): missing required field "selector" in io.k8s.api.apps.v1.DaemonSetSpec; if you choose to ignore these errors, turn validation off with --validate=false`

Adding the --validate=false 
`The DaemonSet "fluent-bit" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"fluent-bit-logging", "kubernetes.io/cluster-service":"true", "version":"v1"}: `selector` does not match template `labels``

**Comment by matty1979** [comment]
Updating the fluent-bit-ds.yaml to below I was able to run the daemonset. 

`spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus`

**Comment by matty1979** [comment]
Changing even more within the fluent-bit-ds-minikube.yaml adding in 

`env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "opendistro-es-client-service"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSERACH_SCHEME
          value: "https"
        - name: FLUENT_ELASTICSEARCH_USER
          value: "admin"
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: "admin"`

Is now giving the following errors 

```
2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [error] [src/flb_http_client.c:844 errno=32] Broken pipe
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
[2020/06/08 20:39:51] [ warn] [engine] failed to flush chunk '1-1591648790.939798289.flb', retry in 7 seconds: task_id=1, input=tail.0 > output=es.0
[2020/06/08 20:39:51] [ warn] [engine] failed to flush chunk '1-1591648790.952254804.flb', retry in 10 seconds: task_id=2, input=tail.0 > output=es.0
[2020/06/08 20:39:51] [error] [http_client] broken connection to opendistro-es-client-service:9200 ?
[2020/06/08 20:39:51] [ warn] [out_es] http_do=-1 URI=/_bulk
```

**Comment by matty1979** [comment]
```
output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     5
        Time_Key        @timestamp
        Replace_Dots    On
        Logstash_Prefix userale
        HTTP_User       admin
        HTTP_Passwd     admin
        tls             on
        tls.debug       2
        tls.verify      Off
        Type            flb_type
```

Changing the configmap to match this allowed me to connect. 

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.3.11
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "opendistro-es-client-service"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        - name: FLUENT_ELASTICSERACH_SCHEME
          value: "https"
        - name: FLUENT_ELASTICSEARCH_USER
          value: "admin"
        - name: FLUENT_ELASTICSEARCH_PASSWORD
          value: "admin"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: mnt
          mountPath: /mnt
          readOnly: true
```

This is what the beginning of the fluent-bit-ds-minikube.yaml looks like to get it to connect.
