### ISSUE TITLE
Too high memory usage when `retry_limit false`

### ISSUE THREAD

**Issue by hectorhuertas** [fluent/fluent-bit#2285]
## Bug Report

**Describe the bug**

Using a tail input with `mem_buf_limit 1mb` and an http output with `retry_limit false`, memory goes much higher than expected when the output enters a retry loop.

**To Reproduce**
- Run a fluent-bit setup with the configuration detailed below
- Take down the receiving endpoint so the output can't send logs
- Observe memory going very high

**Expected behaviour**

We would expect memory go up a bit, which according to https://docs.fluentbit.io/manual/administration/memory-management shouldn't be more than ~5mb, but instead see the screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/13817763/85385048-20bdcc80-b542-11ea-965f-2a5654c0e575.png)

**Your Environment**

* Version used: 1.6.0 & 1.4.6 & 1.4.3
* Environment name and version: kubernetes 1.19.2 for 1.6.0 and kubernetes 1.18.3 for 1.4.x
* Server type and version: AWS EC2 m5a.large
* Operating System and version: Flatcar Container Linux by Kinvolk stable (2605.6.0 for 1.6.0) and (2512.2.1 for 1.4.x)
* Configuration: (besides volumes and files needed)
```
resources:
  requests:
    cpu: 0m
    memory: 16Mi
  limits:
    cpu: 1000m
    memory: 128Mi
```
* Filters and plugins:
```

[SERVICE]
    Flush         1
    Log_Level     error
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Port     8080

[INPUT]
    Name              tail
    Alias             kube-container
    Tag               kube-container.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     1MB
    Skip_Long_Lines   On
    Refresh_Interval  10

[OUTPUT]
    Name         http
    Alias        kube-container
    Match        kube-container.*
    Host         ${FLUENTD_HOST}
    Port         443
    URI          ${FLUENTD_CONTAINER_URI}
    KeepAlive    on # this line removed for version 1.6.0 
    TLS          on
    Format       json
    Retry_Limit  False

```

**Additional context**

On 1.6.0 we see no errors in the log, besides the expected:
```
[2020/10/14 13:56:31] [error] [output:http:kube-container] my-host.com:443, HTTP status=404
404 page not found
```

On 1.4.3 we see no errors in the log, besides the expected:
```
[2020/06/22 15:24:03] [error] [output:http:kube-container] my-host.com:443, HTTP status=404
```

On 1.4.6, in addition to the output error, we also see
```
[2020/06/22 15:17:21] [  Error] epoll_ctl: File exists, errno=17 at /tmp/fluent-bit/lib/monkey/mk_core/mk_event_epoll.c:136
```
However, this seems unrelated and does not make any difference in the observed behaviour

Thank you!

**UPDATE**: updated the issue to reflect tests with 1.6.0

**Comment by hectorhuertas** [comment]
We are still seeing this behaviour in 1.6.0. I've updated the issue description

**Comment by hectorhuertas** [comment]
Thanks for looking into this. It is always reproducible. We are using the official images. I'm happy to do more testing or provide more data if you guide me.

**Comment by hectorhuertas** [comment]
I've reproduced the issue with a simple setup in kubernetes, and also locally on a macbook.

The setup is:
* fluentd listening for http inputs
* a simple logger appending to a file
* fluentbit tailing the file and sending logs to fluentd

Once everything is running, kill fluentd and watch memory go up without limit.

# Reproducing in Kubernetes
kubernetes: 1.19.2
fluent-bit: 1.6.2
fluentd: 1.11.4
server: AWS EC2 m5a.large
OS: Flatcar Container Linux by Kinvolk stable (2605.6.0)

Deploy a fluentd pod and service:
```
apiVersion: v1
kind: Service
metadata:
  name: fluentd
spec:
  selector:
    app.kubernetes.io/name: fluentd
  ports:
    - port: 8888
      name: http-input
---
apiVersion: v1
kind: Pod
metadata:
  name: fluentd
  labels:
    app.kubernetes.io/name: fluentd
  annotations:
    fluentbit.io/exclude: "true"
spec:
  containers:
    - name: fluentd
      image: fluent/fluentd:v1.11.4-2.0
      args: ["-c", "/etc/fluent/config.d/uw.conf", "-q", "--no-supervisor"]
      ports:
        - containerPort: 8888
      volumeMounts:
        - name: conf
          mountPath: /etc/fluent/config.d
  volumes:
    - name: conf
      configMap:
        name: fluentd
```

With the following fluentd configuration:
```
<source>
  @type http
  port 8888
  format json
</source>

<match **>
  @type null
</match>
```

Then deploy a pod with a logger container along with fluentbit:
```
apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /api/v1/metrics/prometheus
    prometheus.io/port: "8080"
    fluentbit.io/exclude: "true"
spec:
  containers:
    - name: fluent-bit
      image: fluent/fluent-bit:1.6.2
      ports:
        - containerPort: 8080
      env:
        - name: FLUENTD_HOST
          value: fluentd.sys-log.svc.cluster.local
        - name: FLUENTD_CONTAINER_URI
          value: /testing
      volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: tester
          mountPath: /tester
    - name: logger
      image: busybox
      command:
        - sh
        - -c
        - |
          touch /tester/mylog
          while true; do
            echo "Hello - $(date)" >> /tester/mylog
            sleep 1
          done
      volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/fluent-bit.conf
          subPath: fluent-bit.conf
        - name: tester
          mountPath: /tester
  volumes:
    - name: config
      configMap:
        name: fluent-bit
    - name: tester
      emptyDir: {}
```

With the following fluent-bit configuration:
```
[SERVICE]
    Flush            1
    Log_Level        info
    HTTP_Server      On
    HTTP_Port        8080

[INPUT]
    Name              tail
    Tag               kube-container.*
    Path              /tester/*
    Mem_Buf_Limit     1MB

[OUTPUT]
    Name         http
    Match        kube-container.*
    Host         ${FLUENTD_HOST}
    Port         8888
    URI          ${FLUENTD_CONTAINER_URI}
    Format       json
    Retry_Limit  False
```

At this point everything is working fine. If we delete the fluentd pod, then memory starts growing without limit.

<img width="1337" alt="cpu-and-memory" src="https://user-images.githubusercontent.com/13817763/97462272-d52b8d00-193e-11eb-987e-377cab80eacf.png">


Logs:
