### ISSUE TITLE
[setup] fluent-bit  [in_tail] read error, check permissions

### ISSUE THREAD

**Issue by linbingdouzhe** [fluent/fluent-bit#2374]
## Bug Report

**Describe the bug**
i can not collect logs where "/var/lib/rancher/rke/log/kube*.log" , but can "/var/log/containers/*"
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2020/07/21 02:58:49] [ info] [engine] started (pid=1)
[2020/07/21 02:58:49] [error] [in_tail] read error, check permissions: /var/lib/rancher/rke/log/kube*.log
[2020/07/21 02:58:49] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
```
- Steps to reproduce the problem:

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v1.2.2
* Configuration: 
```
input:
  tail:
    memBufLimit: 5MB
    parser: docker
    path: /var/lib/rancher/rke/log/kube*.log
  systemd:
    enabled: false
    filters:
      systemdUnit:
        - docker.service
        - kubelet.service
        - node-problem-detector.service
    maxEntries: 1000
    readFromTail: true
    tag: host.*

filter:
  kubeURL: https://kubernetes.default.svc:443
  kubeCAFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  kubeTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
  kubeTag: kube
  kubeTagPrefix: kube.var.lib.rancher.rke.log.
```

* Environment name and version (e.g. Kubernetes? What version?):  kubernetes 1.15.4
* Server type and version: 
* Operating System and version: rancheros
* Filters and plugins:

**Additional context**
