### ISSUE TITLE
How to read multiline json format

### ISSUE THREAD

**Issue by yeruvass** [fluent/fluent-bit#2418]
I'm trying to read below json format but reading line by line . 

td-agent-bit version is 1.4.5

**Log format** :-

{
  "thread" : "1",
  "level" : "OFF",
  "loggerName" : "AuditLogger",
  "marker" : {
    "name" : "Audit",
    "parents" : [ {
      "name" : "EVENT"
    } ]
  },
  "message" : "Audit [useCredentials fileName=\"Credential id=apitoken name=paasjenkins/****** (apitoken-nonprod-jobs)\" name=\"Credential id=apitoken name=paasjenkins/****** (apitoken-nonprod-jobs)\" timestamp=\"2020-06-02T12:34:36.928+04:00\" usage=\"[11,1864)\"]",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.audit.AuditLogger",
  "instant" : {
    "epochSecond" : 1594986664,
    "nanoOfSecond" : 204000000
  },
  "contextMap" : { },
  "threadId" : 129467,
  "threadPriority" : 5
}
{
  "thread" : "2",
  "level" : "OFF",
  "loggerName" : "AuditLogger",
  "marker" : {
    "name" : "Audit",
    "parents" : [ {
      "name" : "EVENT"
    } ]
  },
  "message" : "Audit [useCredentials fileName=\"Credential id=apitoken name=paasjenkins/****** (apitoken-nonprod-jobs)\" name=\"Credential id=apitoken name=paasjenkins/****** (apitoken-nonprod-jobs)\" timestamp=\"2020-06-02T12:34:36.928+04:00\" usage=\"[11,1864)\"]",
  "endOfBatch" : false,
  "loggerFqcn" : "org.apache.logging.log4j.audit.AuditLogger",
  "instant" : {
    "epochSecond" : 1594986664,
    "nanoOfSecond" : 204000000
  },
  "contextMap" : { },
  "threadId" : 129467,
  "threadPriority" : 5
}

**td-agent-bit.conf**
[SERVICE]
   Parsers_File /etc/td-agent-bit/parsers.conf
   Daemon off
   Flush 5
   Log_Level trace

[INPUT]
   Name tail
   Path /var/log/jenkins/audit1.log
   DB /etc/td-agent-bit/db/enbd-jenkins-audit.db
   Path_Key tailed.path
   Tag enbd-jenkins-audit
   Parser_Firstline firstline2
   Multiline  On
   Parser_1 multiline2
   Refresh_Interval 5
   Buffer_Chunk_Size  3M
   Buffer_Max_Size    200M
   Mem_Buf_Limit      300M
   Skip_Long_Lines    true
[OUTPUT]
   Name stdout
   Match enbd-jenkins-*

**parsers.conf**
[PARSER]
   Name        firstline2
   Format      regex
   Regex       ^(?<message>\{\n\s{1,}\"thread\"\s:)

[PARSER]
   Name        multiline2
   Format      regex
   Regex       (?m-ix)^(?<message>\{\n\s{1,}\"thread\".*)

I want to read whole thread-1 is one message and other one is another message.

**Comment by simonasr** [comment]
This configuration works for us:

parser.conf
```
[PARSER]
    Name multilinejson
    Format regex
    Regex ^(?<data>{.*)
```

Input tail config:
```
[INPUT]
    Name tail
    Multiline On
    Parser_Firstline multilinejson
    Tag testmultilinejson
```

Not sure if this is a best solution 😸 
It would be great, if json parser could parse multiline json logs out of the box 🙏

**Comment by yeruvass** [comment]
Working perfectly. Thanks alot.

**Comment by bartweber** [comment]
Thanks @simonasr this is where I was looking for, for a long time. Though it looks like a workaround to me, I'm glad the issue didn't end in a show stopper. To get a regular JSON log event (without wrapping all content in the field `data`) I added an extra filter to your solution:
```
[FILTER] 
    Name             parser
    Key_Name         data
    Parser           json
    Unescape_Key     On
```

**Comment by edsiper** [comment]
# Multiline Update

As part of Fluent Bit v1.8, we have released a new Multiline core functionality. This new big feature allows you to configure new `[MULTILINE_PARSER]`s that support multi formats/auto-detection, new multiline mode on Tail plugin, and also on v1.8.2 (to be released on July 20th, 2021) a new Multiline Filter. 

For now, you can take at the following documentation resources:

- [Multiline Parsers / Concepts and Configuration](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/multiline-parsing)
- [Tail + New Multiline Core Feature](https://docs.fluentbit.io/manual/pipeline/inputs/tail#multiline-support)
- [New Multiline Filter](https://docs.fluentbit.io/manual/pipeline/filters/multiline-stacktrace)

Documentation pages now point to complete config examples that are available on our repository.

Thanks everyone for supporting this!

**Comment by edmondsiu0** [comment]
This YAML based config seems to work to some extent: 

```yaml
# This parser matches pretty-printed JSON objects from `{` all the way until the next `{` at the start of a new line.
multiline_parsers:
  - name: multiline-json
    type: regex
    flush_timeout: 500
    rules:
      - state: start_state
        regex: '/^\{.*/'
        next_state: cont
      - state: cont
        regex: '/^([^\S\r\n].*|})$/'
        next_state: cont
```

```yaml
parsers:
  # This parser decodes the escaped `log` entry processed by the multiline parser
  # We use this `opportunistic_json` as this pipeline also processes normal JSON objects
  - name: opportunistic_json
    format: json
    # This is not really a valid YAML, but see:
    # https://github.com/fluent/fluent-bit/discussions/9717
    decode_field_as: escaped log try_next
    decode_field_as: escaped_utf8 log try_next
    decode_field_as: json log
```

```yaml
pipeline:
  inputs:
    - name: tail
      path: /tmp/logs/*.json
      tag: mytag
      read_from_head: true
      buffer_max_size: 1M
      multiline.parser: multiline-json

  filters:
    - name: parser
      match: "*"
      key_name: log
      parser: opportunistic_json
```

I say this solution partially works for us, because it only works in active tailing mode - not in batch processing mode with `exit_on_eof` which conflicts with multi-line parser's flush interval. 

Hope this helps someone.
