### ISSUE TITLE
Fluent-Bit stackdriver plugin receives the resource labels from wrong log

### ISSUE THREAD

**Issue by PDVJAM** [fluent/fluent-bit#2423]
## Bug Report

**Describe the bug**
Fluent-Bit stackdriver plugin receives the resource labels from wrong log.

**To Reproduce**

**Expected behavior**
Correct labels must be set.

**Screenshots**
[Screenshot_1] (https://ibb.co/485MX8n)
[Screenshot_2] (https://ibb.co/YbJT38K)

As you can see, tag is correct but k8s_container labels are not.

**Your Environment**

* Version used: Fluent-Bit 1.5.2
* Configuration:
Fluent-Bit ConfigMap configuration:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
      Flush         1
      Log_Level     warn
      Daemon        off
      Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-stackdriver.conf

  input-kubernetes.conf: |
    [INPUT]
      Name               tail
      Tag_Regex          var.log.containers.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace_name>[^_]+)_(?<container_name>.+)-(?<docker_id>[a-z0-9]{64})\.log$
      Tag                k8s_container.<namespace_name>.<pod_name>.<container_name>
      Path               /var/log/containers/*.log
      Exclude_Path       *_kube-system_*.log
      Parser             docker

  filter-kubernetes.conf: |
    [FILTER]
      Name    lua
      Match   k8s_container.*
      script  /fluent-bit/lua/append_tag.lua
      call    append_tag

    [FILTER]
      Name                kubernetes
      Match               k8s_container.*
      Kube_URL            https://kubernetes.default.svc.cluster.local:443
      Kube_Tag_Prefix     k8s_container.
      Regex_Parser        k8s-container-custom-tag
      Annotations         Off
      Labels              Off

  output-stackdriver.conf: |
    [OUTPUT]
      Name                       stackdriver
      Match                      *
      Resource                   k8s_container
      k8s_cluster_name           humanly-k8s-dev-0001
      k8s_cluster_location       digitalocean
      google_service_credentials /var/secrets/google/key.json
      tls                        On
      tls.verify                 Off
      severity_key               level

  parsers.conf: |
    [PARSER]
      # https://docs.fluentbit.io/manual/parser/json
      Name        docker
      Format      json
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L
      Time_Keep   Off
      # Command      |  Decoder | Field | Optional Action
      # =============|==================|=================
      Decode_Field_As   json       log   do_next
      Decode_Field_As   escaped    log

    [PARSER]
      Name    k8s-container-custom-tag
      Format  regex
      Regex   ^(?<namespace_name>[^_.]+)\.(?<pod_name>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*+)\.(?<container_name>[^.]+)$ 
```

append_tag.lua:
```apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-lua
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  append_tag.lua: |
    function append_tag(tag, timestamp, record)
      new_record = record
      new_record["logging.googleapis.com/local_resource_id"] = tag
      new_record["test_tag_value"] = tag
      return 1, timestamp, new_record
    end
```

DaemonSet:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.5.2
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: fluent-bit-lua
          mountPath: /fluent-bit/lua/
        - name: mnt
          mountPath: /mnt
          readOnly: true
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_SERVICE_CREDENTIALS
          value: /var/secrets/google/key.json
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: fluent-bit-lua
        configMap:
          name: fluent-bit-lua
      - name: mnt
        hostPath:
          path: /mnt
      - name: google-cloud-key
        secret:
          secretName: fluent-bit-logging-key
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
```

* Environment name and version (e.g. Kubernetes? What version?): DigitalOcean k8s v1.17.5.
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**
