### ISSUE TITLE
systemd input path set up for RHEL(Redhat) Host system

### ISSUE THREAD

**Issue by lalithvaka** [fluent/fluent-bit#2449]
## Bug Report

**Describe the bug**
Using the systemd plugin for capturing the systemd/journald logs with the following input under fluent-bit-configmap.yaml
```
[INPUT]
        Name                     systemd
        Tag                          host.*
        Path                        /run/log/journal/<how to specify etcmachineid> 
        Systemd_Filter    _SYSTEMD_UNIT=docker.service
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
```
Also trying to use under fluent-bit-ds.yaml
```
      containers:
        volumeMounts:
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
      volumes:
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
```
getting the following errors
[2020/08/11 02:49:37] [error] [plugins/in_systemd/systemd_config.c:70 errno=2] No such file or directory
[2020/08/11 02:49:37] [error] [in_systemd] given path /run/log/journal is invalid
[2020/08/11 02:49:37] [error] [in_systemd] cannot initialize
[2020/08/11 02:49:37] [error] Failed initialize input systemd.1

**Expected behavior**
Not sure how to specify the machine ID value in the Path of the [INPUT]

**Your Environment**
Kubernetes Cluster with standard Fluent-bit deployment writing to a http output

* Version used: fluent/fluent-bit:1.3.11
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): K8S 15.3
* Server type and version: 
* Operating System and version: RHEL 7.7
* Filters and plugins: systemd

**Additional context**

Can not forward systemd/journald logs

**Comment by lalithvaka** [comment]
Missed to mount /run/log/journal under fluent-bit-ds.yaml file
```
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - name: etcmachineid
          mountPath: /etc/machine-id
          readOnly: true
        - name: runlogjournal
          mountPath: /run/log/journal
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: runlogjournal
        hostPath:
          path: /run/log/journal
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: etcmachineid
        hostPath:
          path: /etc/machine-id
          type: File
```

Also referencing the path as "Path              /run/log/journal"  under [INPUT] of fluent-bit-config.yaml
```
input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
    [INPUT]
        Name              systemd
        Tag               host.*
        Path              /run/log/journal
        Systemd_Filter    _SYSTEMD_UNIT=docker.service
        Systemd_Filter    _SYSTEMD_UNIT=kubelet.service
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10
```
