### ISSUE TITLE
Invalid entry in /var/log/containers while fluent-bit pods start

### ISSUE THREAD

**Issue by stan-iakov** [fluent/fluent-bit#2676]
## Bug Report

**Describe the bug**
Hi Team,
I have deployed the fluent-bit:1.5-debug image on a Kubernetes v1.15 cluster.
while the fluent-bit pods is starting I see 
...skip (invalid) entry=/var/log/containers/... messages in the logs.
I am able to get inside the fluent-bit pods and I can list the .log files in the /var/log/containers folder corresponding to symlinks, however I cannot cat or tail those .log files.
In my fluent-bit-input.conf file I have the Path set to /var/log/containers/*.log

Can you advise what could be wrong in my configuration?
**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:

**Expected behavior**
logs files in the /var/log/containers/ folder should not be skipped

**Screenshots**

**Your Environment**

* Version used: 1.15-debug
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): kubernetes v1.15
* Server type and version:
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by xuchenCN** [comment]
I encounterd this issue too and view the [code](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_scan_glob.c#L232).
I guss the symbol link file may cause this issue.

**Comment by xuchenCN** [comment]
@stan-iakov I got the point, /var/log/containers/*.log files are link to /var/log/pods/ and the file in the /var/log/pods/ is link the $DOCKER_HOME/containers, so if you chage the location of the docker you should identify the path.

**Comment by zxdvd** [comment]
I got this problem today while following the official kubernetes doc.

It seems [this line](https://github.com/fluent/fluent-bit/blob/master/plugins/in_tail/tail_scan_glob.c#L232) matters. But I don't know why. Anyone can help to explain why it should be a regular file?

**Comment by edsiper** [comment]
maybe a broken link or bad mount of your volume ?

**Comment by BertelBB** [comment]
I am trying to deploy fluent-bit using the [Helm chart](https://github.com/fluent/helm-charts/blob/master/charts/fluent-bit) and I am also encountering this issue. I am deploying fluent-bit as non-root and dropping all privileges, is that causing this?
There is no way to change how these volumes are mounted into the pod because it is hard coded into the chart....

**Comment by hisrarul** [comment]
Thanks @xuchenCN. As suggested I check that files in the directory `/var/log/containers/` were pointing to files in the directory `/var/log/pods/` and log files in the `/var/log/pods/` were pointing to `/mnt/docker/containers`. After adding volume `mntdatadockercontainers`. It is working fine for me.

```
.....
    containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.6-debug
        imagePullPolicy: Always
        ports:
          - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /home/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        - mountPath: /mnt/docker/containers
          name: mntdatadockercontainers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /home/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - hostPath:
          path: /mnt/docker/containers
        name: mntdatadockercontainers
        readOnly: true
.....
```

**Comment by malekerramli** [comment]
im having the same issue ... i tried to add  { path: /mnt/docker/containers | name: mntdatadockercontainers} that did not fix it , anyone has another approach ? thanks!

**Comment by thethir13en** [comment]
As @hisrarul said:
```/var/log/containers/*.log``` are symlinks to ```/var/log/pods/*`` which are also symlinked to``` /var/lib/docker/containers/*```

You should mount them all to your fluentbit pods for proper work:
```
---
apiVersion: v1
kind: Pod
metadata:
  name: fluentbit
  labels:
    name: fluentbit
spec:
  containers:
  - name: logging-fluentbit
    image: docker.io/fluent/fluent-bit:1.6
    securityContext:
      privileged: true
    volumeMounts:
      # host volumes with logs
      - name: var-log-containers
        mountPath: "/var/log/containers"
      - name: var-log-pods
        mountPath: "/var/log/pods"
      - name: var-lib-docker-containers
        mountPath: "/var/lib/docker/containers"
  volumes:
  # host volumes with logs
  - name: var-log-containers
    hostPath:
      path: "/var/log/containers"
      type: ""
  - name: var-log-pods
    hostPath:
      path: "/var/log/pods"
      type: ""
  - name: var-lib-docker-containers
    hostPath:
      path: "/var/lib/docker/containers"
      type: ""
```
