### ISSUE TITLE
Tail plugin silently skips logs

### ISSUE THREAD

**Issue by Kristian-ZH** [fluent/fluent-bit#2723]
## Bug Report
When fluent-bit CPU is on the edge, the tail plugin starts skipping logs silently, without any indication.

**Describe the bug**

We ran an integration test with 250 000 logs generated for 20 seconds on node
The tail  plugin skipped ~20 000 logs silently  without any indication or error log for that (We waited more than 2hours for the test but logs did not appear). 

When we increased the fluent-bit resources, we received the logs successfully.

We Increased the log level of the fluent-bit to `debug` but still everything looked normal.
This behaviour looks like a race condition, because when the CPU is on the edge, the expected behaviour is to slow down the flushing rate, not to skip a bunch of logs without any indication.

**To Reproduce**
- Steps to reproduce the problem:
1 Deploy fluent-bit:1.5.4.
2 Deploy the logger application (given below).
3 Run this test several times and half of the tests should fail.

**Expected behavior**

We expect fluent-bit to not skip logs silently on increased load.

**Your Environment**

* Version used: fluent-bit 1.5.4
* Configuration:
```
    [SERVICE]
        Flush           30
        Daemon          Off
        Log_Level       info
        Parsers_File    parsers.conf
        HTTP_Server     On
        HTTP_Listen     0.0.0.0
        HTTP_PORT       {{ .Values.ports.metrics }}

    [INPUT]
        Name              tail
        Tag               kubernetes.*
        Path              /var/log/containers/*.log
        Exclude_Path      *_garden_fluent-bit-*.log,*_garden_loki-*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Skip_Long_Lines   On
        Mem_Buf_Limit     30MB
        Refresh_Interval  10
        Ignore_Older      1800s
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.17.12
* 10 Logger applications on the same node with the following configuration:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger
  namespace: {{ .HelmDeployNamespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger
        image: k8s.gcr.io/logs-generator:v0.1.1
        args:
          - /bin/sh
          - -c
          - |-
            /logs-generator --logtostderr --log-lines-total=${LOGS_GENERATOR_LINES_TOTAL} --run-duration=${LOGS_GENERATOR_DURATION}

            # Sleep forever to prevent restarts
            while true; do
              sleep 3600;
            done
        env:
        - name: LOGS_GENERATOR_LINES_TOTAL
          value: "250000"
        - name: LOGS_GENERATOR_DURATION
          value: 20s
```
* Operating System and version: Debian 11
* Filters and plugins: Does not fit on this issue
