### ISSUE TITLE
output_file enhancement:  support tag accessor and time format string in file path

### ISSUE THREAD

**Issue by monsterxx03** [fluent/fluent-bit#2786]
Current file output plugin will write records to `Path/File` location, if File is not provided, fallback to tag name.

I think fluent-bit can support path format like out_s3: https://docs.fluentbit.io/manual/pipeline/outputs/s3#s3-key-format-and-tag-delimiters. Then file path can be sth like $TAG[0]/$TAG[1]/%Y/%m/%d

I'm trying  to deploy fluent-bit as a central logging server, store logs on local disk.Output all logs to single file is difficult to work with logrotate or customized scripts.My normal workflow is use a daily cronjob to archive yesterday's log as gzip and upload to s3 or somewhere.

**Comment by james-masson** [comment]
I'm working on exactly the same thing right now.

I'm trying to dynamically configure the record tag to include the date, so it self-rotates. Haven't figured out how yet, without getting Lua involved. There doesn't seem to be a native way to transform the epoch timestamp.

**Comment by james-masson** [comment]
I ended up using lua in the end

`  new_record["record_date"] = os.date("%Y-%m-%d",timestamp)`

with

```
# make our tag be our filename
[FILTER]
    Name          rewrite_tag
    Match         source.docker.*
    Rule          $container_name ^(.*)$ container.$1.$record_date.log false

# Write it to disk
[OUTPUT]
    Name file
    Match container.*
    Path ${LOG_DIR}/
    Format template
    Template [{stream}]: {log}
```

**Comment by ugoviti** [comment]
Hi @james-masson,

thankyou for the reply, I'm spent some minutes to figure out how complete this workaround, and so I report here the full procedure (correct me if I'm wrong)

File: record_date.lua
```record_date.lua
function record_date(tag, timestamp, record)
        new_record = record
        new_record["record_date"] = os.date("%Y%m%d",timestamp)
        return 1, timestamp, new_record
end
```

File: fluent-bit.conf
```
[FILTER]
    Name    lua
    Match   apache.*
    script  record_date.lua
    call    record_date

[FILTER]
    Name   rewrite_tag
    Match  apache.*
    Rule   $vhost ^(.*)$ /tmp/log/$0/$TAG[1]-$record_date.log true

[OUTPUT]
    name        file
    match       /tmp/log/*
```

Kind Regards

**Comment by MaximeWewer** [comment]
Hello,

I used @ugoviti example as follows, and it works perfectly : 

```yaml
service:
  flush: 5
  log_level: info
  parsers_file: parsers.conf

pipeline:
  inputs:
    # Syslog (UDP + TCP)
    - name: syslog
      tag: linux
      mode: udp
      listen: 0.0.0.0
      port: 5000
      parser: syslog-rfc3164
      source_address_key: "source_ip"

    - name: syslog
      tag: linux
      mode: tcp
      listen: 0.0.0.0
      port: 5000
      parser: syslog-rfc3164
      source_address_key: "source_ip"

    # Firewall (UDP + TCP)
    - name: syslog
      tag: firewall
      mode: udp
      listen: 0.0.0.0
      port: 5001
      parser: syslog-rfc3164
      source_address_key: "source_ip"

    - name: syslog
      tag: firewall
      mode: tcp
      listen: 0.0.0.0
      port: 5001
      parser: syslog-rfc3164
      source_address_key: "source_ip"

  filters:
    # Generate date
    - name: lua
      match_regex: ^(linux|firewall)$
      call: record_date
      code: |
        function record_date(tag, timestamp, record)
            record["record_date"] = os.date("%Y%m%d", timestamp)
            return 2, timestamp, record
        end

    # Rewrite tag linux -> linux.20260120
    - name: rewrite_tag
      match_regex: ^(linux|firewall)$
      rule: $record_date ^(.+)$ $TAG.$1 false
      emitter_name: date_emitter

    # Remove record_date only from the final tags (ex: linux.YYYYMMDD)
    - name: modify
      match_regex: ^(linux|firewall)$
      remove: record_date

  outputs:
    - name: file
      match: "linux.*"
      path: /YOUR_PATH/fluent-bit/linux
      mkdir: true
      format: out_file

    - name: file
      match: "firewall.*"
      path: /YOUR_PATH/fluent-bit/firewall
      mkdir: true
      format: out_file
```
