### ISSUE TITLE
Cloudwatch log_stream_prefix based on kubernetes namespace?

### ISSUE THREAD

**Issue by shinebayar-g** [fluent/fluent-bit#2844]
Hi. I'm using Fluent-Bit to ship kubernetes container logs into cloudwatch. [This config](https://github.com/fluent/fluent-bit-kubernetes-logging/blob/master/output/elasticsearch/fluent-bit-configmap.yaml) is working fine. Instead of `output-elasticsearch.conf` I have following:

```
output-cloudwatch.conf: |
    [OUTPUT]
        Name                cloudwatch_logs
        Match               *
        region              us-east-1
        log_group_name      /aws/eks/eks-cluster-1234/containers
        log_stream_prefix   <kubernetes-namespace>
        auto_create_group   On
```

How can I grab the kubernetes **namespace** value for this config? ~~So our cloudwatch logs will be little bit organized, rather than putting everything inside single log group.~~ Just found out I can't create multiple log groups at first place because of `log_group_name`

But I could still set `log_stream_prefix` with k8s namespace or something..

**Comment by shinebayar-g** [comment]
I got it working with little bit modification to deployments. First we have to set environment variables for pods.

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: my-deployment
  namespace: my-namespace
  labels:
    k8s-app: my-deployment
  ...
  ...
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['k8s-app']
```

Next use envs that we just passed.

```
output-cloudwatch.conf: |
    [OUTPUT]
        Name                cloudwatch_logs
        Match               *
        region              us-east-1
        log_group_name      /aws/eks/eks-cluster-1234/${MY_NAMESPACE}/${MY_DEPLOYMENT_NAME}
        log_stream_prefix   pod-
        auto_create_group   On
```

I would still prefer if there is a way to get it working without passing ENVs around. Because now I have to modify every k8s deployments..
