### ISSUE TITLE
SIGSEGV on 1.7.1 

### ISSUE THREAD

**Issue by vladimirfx** [fluent/fluent-bit#3130]
## Bug Report

**Describe the bug**

Periodical crash with SIGSEGV.

**To Reproduce**
No steps to reproduce.
```
[2021/02/25 07:52:43] [engine] caught signal (SIGSEGV)
#0 0x560bcec0854c in atomic_load_p() at lib/jemalloc-5.2.1/include/jemalloc/internal/atomic.h:62
#1 0x560bcec0854c in rtree_leaf_elm_bits_read() at lib/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:175
#2 0x560bcec0854c in rtree_szind_slab_read() at lib/jemalloc-5.2.1/include/jemalloc/internal/rtree.h:500
#3 0x560bcec0854c in ifree() at lib/jemalloc-5.2.1/src/jemalloc.c:2570
#4 0x560bcec0854c in je_free_default() at lib/jemalloc-5.2.1/src/jemalloc.c:2790
#5 0x560bcef39a58 in cio_memfs_close() at lib/chunkio/src/cio_memfs.c:64
#6 0x560bcef35623 in cio_chunk_close() at lib/chunkio/src/cio_chunk.c:112
#7 0x560bcecafd3a in flb_input_chunk_destroy() at src/flb_input_chunk.c:560
#8 0x560bcec95999 in flb_task_destroy() at src/flb_task.c:435
#9 0x560bcec92b11 in flb_task_users_release() at include/fluent-bit/flb_task.h:132
#10 0x560bcec92b46 in flb_task_users_dec() at include/fluent-bit/flb_task.h:150
#11 0x560bcec9305f in handle_output_event() at src/flb_engine.c:215
#12 0x560bcec93f9e in flb_engine_start() at src/flb_engine.c:684
#13 0x560bcec79cd2 in flb_lib_worker() at src/flb_lib.c:493
#14 0x7fe6f1958fa2 in ???() at ???:0
#15 0x7fe6f10394ce in ???() at ???:0
#16 0xffffffffffffffff in ???() at ???:0
```
 
**Expected behavior**

No crash.

**Your Environment**

* Version used: 1.7.1
* Configuration: tail input + loki output (configuration from Helm chart)
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes k3s v1.20.2+k3s1
* Server type and version: Loki 2.0
* Operating System and version: Ubuntu 20.04
* Filters and plugins: Kubernetes filter, no plugins

**Comment by edsiper** [comment]
Would you please share your configuration ?

**Comment by vladimirfx** [comment]
FluentBit DaemonSet:
```YAML
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logging-fluent-bit
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fluent-bit
      app.kubernetes.io/instance: logging
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fluent-bit
        app.kubernetes.io/instance: logging
    spec:
      serviceAccountName: logging-fluent-bit
      containers:
        - name: fluent-bit
          image: "fluent/fluent-bit"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 500m
              memory: 270Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: config
              mountPath: /fluent-bit/etc/
            - name: varlog
              mountPath: /var/log
            - name: etcmachineid
              mountPath: /etc/machine-id
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: logging-fluent-bit
        - name: varlog
          hostPath:
            path: /var/log
        - name: etcmachineid
          hostPath:
            path: /etc/machine-id
            type: File
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

```

[flbconf.zip](https://github.com/fluent/fluent-bit/files/6047847/flbconf.zip)
