### ISSUE TITLE
How to Configure fluentbit with journald input, kubernetes filter

### ISSUE THREAD

**Issue by jenningsloy318** [fluent/fluent-bit#332]
Hi All,

I have created a kubernetes cluster, wanna use flunetbit+influxdb+grafana for log processing. right now there seems some issue with configure the journald with the input, and kubernetes as the filter and docker as the parser, finally save the logs into influxdb. 

journald: enable this log driver  in docker service 

fluentbit: manually buid the docker image with 0.12 branch, and modify the Dockerfile, install libsystemd-dev, then it can build journald support. 

fluent-bit.conf
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File fluentbit-parser.conf

[INPUT]
    Name           systemd
    Tag             *
    Systemd_Filter  _SYSTEMD_UNIT=docker.service
    Parser        docker
[FILTER]
    Name          kubernetes
    Kube_URL      https://kubernetes.default.svc:443
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
[OUTPUT]
    Name          influxdb
    Match         *
    Host          monitoring-influxdb
    Port          8086
    Database      k8slog
    Sequence_Tag  _seq
```

fluentbit-parser.conf
```
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
```

when start fluentbit, got error 
```
 NO match rule for kubernetes.0 filter instance

```

Can anybody help me to figure out how to configure the correct kubernetes filter? 
also the default parser is json, but here I use journald, how to implement it as journald format?

**Comment by nokute78** [comment]
'Match' is needed at [FILTER] section.
Could you add 'Match *' at [FILTER] section?

**Comment by jenningsloy318** [comment]
@nokute78 

I added 'Match *' at [FILTER]  into [FILTER] section, this error is gone. but another issue appers, 

```
[2017/07/24 02:23:07] [ info] [engine] started
[2017/07/24 02:23:07] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2017/07/24 02:23:07] [ info] [filter_kube] local POD info OK
[2017/07/24 02:23:07] [ info] [filter_kube] testing connectivity with API server...
[2017/07/24 02:23:07] [error] [filter_kube] could not get meta for POD fluent-bit-v2rq0
```

which shows that it can't get the metadata from apiserver, my k8s cluster is RBAC-enabled and fluentbit is running in monitoring namespace not kube-system, is there any configure that makes it possible to get metadata from all namespace?

**Comment by edsiper** [comment]
Assuming you are using the image fluent/fluent-bit:0.12-dev, you have to append the following configuration property to the Kubernetes filter:

```
[FILTER]
    name         kubernetes
    match        *
    use_journal  On
    ...
```

**Comment by jenningsloy318** [comment]
still got same errors:

log:
```
# kubectl logs fluent-bit-ngxjs -n monitoring
[2017/07/25 01:48:47] [ info] [engine] started
[2017/07/25 01:48:47] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2017/07/25 01:48:47] [ info] [filter_kube] local POD info OK
[2017/07/25 01:48:47] [ info] [filter_kube] testing connectivity with API server...
[2017/07/25 01:48:47] [error] [filter_kube] could not get meta for POD fluent-bit-ngxjs
```
POD conf
```
# hostname
fluent-bit-ngxjs
# cat fluent-bit.conf
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File fluentbit-parser.conf
[INPUT]
    Name           systemd
    Tag             *
    Systemd_Filter  _SYSTEMD_UNIT=docker.service
    Parser        docker
[FILTER]
    Name          kubernetes
    Kube_URL      https://kubernetes.default.svc:443
    Kube_CA_File  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
    Match       *
    use_journal  On
[OUTPUT]
    Name          influxdb
    Match         *
    Host          monitoring-influxdb
    Port          8086
    Database      k8slog
    Sequence_Tag  _seq
```

**Comment by edsiper** [comment]
I have not tested a cluster with RBAC enabled but looking at Tectonic Logging docs, they deploy Fluentd with the following roles (can be used as a reference):

- https://coreos.com/tectonic/docs/latest/files/logging/fluentd-service-account.yaml
- https://coreos.com/tectonic/docs/latest/files/logging/fluentd-role.yaml
- https://coreos.com/tectonic/docs/latest/files/logging/fluentd-role-binding.yaml

refs from: https://coreos.com/tectonic/docs/latest/admin/logging.html

**Comment by jenningsloy318** [comment]
My configuration is same as this one, but no working at this moment. can we have more detauls debug info from fluentbit? more details configuration about the kubernetes scenario ?

**Comment by edsiper** [comment]
sure, I've just pushed a commit that add a debug message from the API server on failure:

- set log_level to debug
- pull image from fluent/fluent-bit:0.12-dev (it's still building now, give it 20 mins)

**Comment by jenningsloy318** [comment]
after set log_level to trace, I got following error

```
[2017/07/26 04:50:07] [ info] [engine] started
[2017/07/26 04:50:07] [debug] [out_influxdb] host=monitoring-influxdb port=8086
[2017/07/26 04:50:07] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2017/07/26 04:50:07] [ info] [filter_kube] local POD info OK
[2017/07/26 04:50:07] [ info] [filter_kube] testing connectivity with API server...
[2017/07/26 04:50:07] [trace] [io_tls] Handshake OK
[2017/07/26 04:50:07] [trace] [io_tls] connection OK
[2017/07/26 04:50:07] [trace] [io] connection OK
[2017/07/26 04:50:07] [trace] [io thread=(nil)] [net_write] trying 1391 bytes
[2017/07/26 04:50:07] [trace] [io thread=(nil)] [net_write] ret=0 total=1391/1391
[2017/07/26 04:50:07] [trace] [io thread=(nil)] [net_read] try up to 4095 bytes
[2017/07/26 04:50:07] [trace] [io thread=(nil)] [net_read] ret=257
[2017/07/26 04:50:07] [debug] [filter_kube] API Server (ns=monitoring, pod=fluent-bit-10m4c) http_do=0, HTTP Status: 403
[2017/07/26 04:50:07] [trace] [upstream] [fd=16] releasing connection 0x7f64e8c3f150
[2017/07/26 04:50:07] [error] [filter_kube] could not get meta for POD fluent-bit-10m4c
[2017/07/26 04:50:07] [debug] [router] input=systemd.0 'DYNAMIC TAG'
```

but When I use curl to access the api server inside the pod, it is ok 

```
# TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)

curl --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -H "Authorization: Bearer $TOKEN" https://kubernetes.default.svc:443/version -v
* Hostname was NOT found in DNS cache
*   Trying 192.168.0.1...
* Connected to kubernetes.default.svc (192.168.0.1) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=cnpvgl56588417.pvg.global.corp.sap
*        start date: 2017-07-18 05:55:27 GMT
*        expire date: 2027-07-16 05:55:27 GMT
*        subjectAltName: kubernetes.default.svc matched
*        issuer: C=CN; ST=SH; L=SH; O=SAP; OU=CSC; CN=CDDEVOPS; emailAddress=DL_57BA68805F99B710F600001A@exchange.sap.corp
*        SSL certificate verify ok.
> GET /version HTTP/1.1
> User-Agent: curl/7.38.0
> Host: kubernetes.default.svc
> Accept: */*
> Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtb25pdG9yaW5nIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImZsdWVudGJpdC10b2tlbi03MzFubiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJmbHVlbnRiaXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwNWMyMWQ5YS03MWE2LTExZTctOTdmZi0zMGUxNzE1ZGJkMzgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6bW9uaXRvcmluZzpmbHVlbnRiaXQifQ.c_Mc7EshnNU3Q4dgiz4r7SbWE9ZEGuP6seTrLDuj3cqjgAR3siptYBIE3OYApKEgHqJ6U7-4hqdmCInCHCs3nhlvdsecmF8XAsP64avbVjp856sNoiqBtrZtPkqPW-5v3_8Scf-dOtFOPsFYRCnevEMVIZvoC3HAAASKhX6E_z3HaMFf2BccQaVmJVIgvcRVyo9oXc40n7sYtRWiW0q7NMTqu7dRSEPUObFhUgIIdzBbitnyFeFIaY1C-Ys1ytfzyxBZdRGuDdW6kFUV5qnv6Mnor8FKRIwIxTRSdv6dsYjrmbgJFUT5SU64_SCOiV5Z8oNpwasFJYJLVUeBfFAx0gBHZHB1JSScWiGCKQ7YRYJ_N2MXHLsZj8qGnHpcZIFtoCQ5pXNgKk-ruicSaL1oP4FeAkosx-Bqb1Ho6VDbPsiywukI93DKWfq8e2OHXHo_oLhFZiEbszqvE_7za7GP0KAXpQgqq53BHM7MCgFh33FCaq9KPeFf53kymghqb-U0Ftiy9gb8eaONLeLaEBUkNiL4mgFye99BmBj_ifEov0xGvWaDlj4t6-4l2tsDCgf6nTWO5SMwkmjjU6WcnPpx6KKy7Ii5--e-jNK4O6l30QUT8-OFtvmMg1_NSnDt72RWdY8_CGWBVJRempwkFHjmeJV_NQ9m4NegzsyKbxwqb2w
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 26 Jul 2017 05:00:36 GMT
< Content-Length: 260
<
{
  "major": "1",
  "minor": "7",
  "gitVersion": "v1.7.1",
  "gitCommit": "1dc5c66f5dd61da08412a74221ecc79208c2165b",
  "gitTreeState": "clean",
  "buildDate": "2017-07-14T01:48:01Z",
  "goVersion": "go1.8.3",
  "compiler": "gc",
  "platform": "linux/amd64"
* Connection #0 to host kubernetes.default.svc left intact
```

**Comment by jenningsloy318** [comment]
for kubernetes filter issue, it is caused by the insufficient permission when use early clusterrole. now I changed it. not it can connect to apiserver. 

I can move the next step, for the parser and output configuration.

**Comment by edsiper** [comment]
actually the Systemd input plugin do not use a Parser because the logs are already structured by Journald. 

Some suggestions:

- set a database file (DB parameter): http://fluentbit.io/documentation/0.12/input/systemd.html
- verify that Fluent Bit container can reach monitoring-influxdb:8086

**Comment by jenningsloy318** [comment]
when I execute journalctl inside the pod, no ouput. seems it don't find the journald socket
 but use journalctl -D /var/log/journal inside the pod, I can get the logs, I already share the sockets and log directory between pod and host. 

```
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: fluentbit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12-dev
        command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf","--verbose"]
        env:
        resources:
          limits:
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: journald-socket1
          mountPath: /run/systemd/journal/
          readOnly: true
        - name: journald-socket2
          mountPath: /var/run/systemd/journal
          readOnly: true
        - name: fluentbit-conf
          mountPath: /fluent-bit/etc/
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: journald-socket1
        hostPath:
          path:  /run/systemd/journal/
      - name: journald-socket2
        hostPath:
          path:  /var/run/systemd/journal
      - name: fluentbit-conf
        configMap:
          name: fluentbit-conf
```

Another thing:  I think there is a need to display more details when fluentbit  is checking the journald socket or journal logs
