### ISSUE TITLE
Loki Output timestamp not parsed properly

### ISSUE THREAD

**Issue by Z18Aplha** [fluent/fluent-bit#3350]
## Bug Report
First of all: I use the docker container of fluent bit v1.7.3 (and also tested with 1.7.2).

**Description of the bug**
Sending any type of input (syslog, tail, forward) to loki ends in an error from loki refering to the timestamp.

**To Reproduce**
- create ```fluent-bit.conf``` with the content
```
[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    trace
    Parsers_File parsers.conf
    Plugins_File plugins.conf
    HTTP_Server  Off

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=docker-forward, agent=fluentbit

[OUTPUT]
    Name stdout
    Match *
```
- run loki and fluent-bit docker containers with docker-compose:
```
version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.2.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
   
  fluentbit:
    image: fluent/fluent-bit:1.7.3
    container_name: fluentbit
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    networks:
      - loki
```
- trigger a log message via the fluentd log driver implemented in docker with
```
docker run --rm --log-driver=fluentd -t ubuntu echo "Testing a log message"
```
- Now you should see something like
```
[0] 98bb7a08ba8b: [1617978084.000000000, {"container_name"=>"/zen_franklin", "source"=>"stdout", "log"=>"Testing a log message", "container_id"=>"98bb7a08ba8b403167488f8b6b9f3ea1dec3a0180d4a7b10753be88b0329daee"}]
```
and the error from loki
```
[2021/04/09 14:21:29] [error] [output:loki:loki.0] loki:3100, HTTP status=400 loghttp.PushRequest.Streams: []*loghttp.Stream: loghttp.Stream.Entries: error reading entry timestamp: strconv.ParseInt: parsing "18446744072487954432": value out of range, error found in #10 byte of ...|487954432","{\"conta|..., bigger context ...|nt":"fluentbit"},"values":[["18446744072487954432","{\"container_name\":\"/zen_franklin\",\"source\"|...
```
Loki complains about the parsing of the timestamp. In the log above the timestamp is correct and in the format of fluentbit (```SECONDS.NANOSECONDS```). Apparently loki expects a nanoseconds-timestamp as an integer so the parsing results in a wrong number ```18446744072487954432``` and decoding this timestamp to ```Monday, 22. Juli 2554 01:34:32.487 GMT+02:00 DST``` which is obviously *out of range*.

**Expected behavior**
Sending to loki causes no error and the timestamp is correct.

**Environment**
**Version used:**
- loki v2.2.1
- fluentbit v1.7.3

**Configuration:**
- see above

**Environment name and version:**
- Docker v18.09.1

**Filters and plugins:**
- just used the docker images as it comes

**Additional context**
I want to collect the logs of all my docker containers and monitor them with grafana. So i use Loki as the log storage. 
I also tried to use promtail for log collection and it worked but the CPU load was too high and i want to use fluentbit because its lightweight and written in C.
My host is a raspberrypi 4 (armv7) with 2GB of RAM as my docker host. I could test it on my Synology NAS (x86_64) but my production system is the raspi.
