### ISSUE TITLE
Make `Logstash_Prefix_Key` more dynamic

### ISSUE THREAD

**Issue by ppoetz** [fluent/fluent-bit#3624]
**Is your feature request related to a problem? Please describe.**

When using the elasticsearch plugin I'd like to have the same prefix for all indices and a dynamic part which depends e.g. on the namespace and of course the date suffix. This would make it much easier to handle index patterns in Elasticsearch.
ATM I have to adapt index patterns (create a new one and delete the old one) all the time when new namespaces appear in my cluster which I want to observe.

According to https://github.com/fluent/fluent-bit/issues/1775 it is only possible to have either a hardcoded Prefix or exact one key.
Let's say I have an application with a number of microservices. I want to have one index per microservice because it's easier to find bugs when split up in smaller indices and you can keep track of log volume per service.
But at the same time I want to have a single index pattern for the whole application including all services. And that's not possible right now.

**Describe the solution you'd like**

My proposed solution is quite simple:
Make a composable `Logstash_Prefix_Key`

Right now one can only use a single key like `$kubernetes['namespace_name']` to make the index dynamic.
In my use case it would be beneficial if this key is composable like: 
`myhardcodedappname-$kubernetes['namespace']` 

This would be a super dynamic solution wrt to Kibana index patterns. In this case this would allow to create a single Index Pattern like: `myhardcodedappname-*`

**Describe alternatives you've considered**
The alternatives are:
* Use a single index which bloats very quickly
* Use one key only which requires to adapt Index Patterns in Kibana all the time.

**Additional context**
This issue was a good start for me: https://github.com/fluent/fluent-bit/issues/1775

**Comment by ppoetz** [comment]
Just pushing this one for another cycle ;-) 
I'm not familiar with C, but would really like to see this feature integrated.

**Comment by danielwegener** [comment]
Same here. Since ES ism_template index_patterns do not allow excludes for system namespaces (like .kibana or .opendistro-job-scheduler-lock), it would be great to be able to have all fluent-bit logs under the same prefix.

**Comment by m44soroush** [comment]
any progress?
I'm still looking for this:
```
Logstash_Prefix_Key      k8s-ns-$kubernetes['namespace_name']
```

**Comment by hostalp** [comment]
I'm also calling for this one. Please someone reopen this issue.

**Comment by rfarro82** [comment]
Could I do something like this @nd-brown within my fluent-bit configmap? I'm not sure where/how I would call the utils.lua outside of it. I'm trying to use the namespace as the index pattern in ES/OS. 
```
filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

    [FILTER]
        Name      lua
        Match     *
        script    filters.lua
        call      add_index_prefix_field

  filters.lua: |
    -- Use a Lua function to create some additional entries based
    -- on substrings from the kubernetes properties.
    function add_index_prefix_field(tag, timestamp, record)
        retcode = 0
        prefix = 'myhardcodedappname' -- Your prefix for output index
        namespace = record['kubernetes']['namespace_name'] -- Any record accessor
        app_name = record['kubernetes']['labels']['app'] -- Any record accessor

        if namespace ~= nil or app_name ~= nil then
            index_prefix = prefix .. '_' .. namespace .. '_' .. app_name

            if index_prefix ~= nil then
                record['index_prefix'] = index_prefix
                retcode = 2
            end
        end

        return retcode, timestamp, record
    end

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ES-CLUSTER-ENDPOINT
        Port            443
        TLS             On
        AWS_Auth        On
        AWS_Region      us-east-1
        Retry_Limit     6
        Replace_Dots    On
        Retry_Limit     2
        Type            _doc
        Logstash_Format On
        Logstash_Prefix_Key $index_prefix
        Logstash_DateFormat %Y.%m.%d
```

**Comment by nd-brown** [comment]
@rfarro82 Yeah, you can.

Only one more thing. You have to be sure that you mount your Configmap appropriately 
e.g

```
apiVersion: apps/v1
kind: DaemonSet
...
spec:
  template:
   metadata: {}
   spec:
      containers:
        - image: fluent/fluent-bit:1.9.0
            ...
            volumeMounts:
            - mountPath: /fluent-bit/etc/filter-kubernetes.conf
               name: config
               subPath: filter-kubernetes.conf
            - mountPath: /fluent-bit/etc/filters.lua
               name: config
               subPath: filters.lua
            - mountPath: /fluent-bit/etc/output-elasticsearch.conf
               name: config
               subPath: output-elasticsearch.conf
            ...
      ...
      volumes:
         - configMap:
            defaultMode: 420
            name: fluentbit
         name: config
```
