### ISSUE TITLE
log loss occurs if fluentBit POD is deleted during log generation

### ISSUE THREAD

**Issue by wenchajun** [fluent/fluent-bit#3702]
## Bug Report

**Describe the bug**

During log generation, I manually deleted the Fluent-bit pod. POD restarts automatically, and fewer logs were collected than the total number of logs。
- Steps to reproduce the problem:
A log generator is set up to produce one log per second for a total of 100 entries, I manually deleted the Fluent-bit pod  during log generation, but two or three logs will be lost the last

input.conf
```
[Input]                                                                                                                  
    Name    tail                                                                                                         
    Path    /var/log/containers/*.log                                                                                    
    Exclude_Path    /var/log/containers/*_kube*-system_*.log
    Refresh_Interval    10                        
    Skip_Long_Lines    true                                             
    DB    /fluent-bit/tail/pos.db                                         
    DB.Sync    Full                                                       
    Mem_Buf_Limit    5MB                                                  
    Parser    docker                                                      
    Tag    kube.*    
```
fluentbit.yaml
```

spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-role.kubernetes.io/edge
                operator: DoesNotExist
  fluentBitConfigName: fluent-bit-config
  image: 'fluent/fluent-bit:v1.7.3'
  positionDB:
    hostPath:
      path: /var/log/positiondb
  resources: {}

```

**Expected behavior**

Not missing the collection log

**Your Environment**

* Version used:fluent-bit:v1.7.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):kubernetes v1.20
* Server type and version:
* Operating System and version:ubuntu 18.04
* Filters and plugins:

**Additional context**

In order not to lose the log, I used the hostpath, but when I deleted the fluentbit during the log generation, there was still a small amount of log loss.
