### ISSUE TITLE
Wrong container_name attached to log

### ISSUE THREAD

**Issue by sagikazarmark** [fluent/fluent-bit#380]
Using 0.12.2 I still experience the issue described in #353

It only occurs when there are more than one containers in a pod (tested with two). All containers receive the alphabetically first name.

The error is consistent after a few deployments of both fluent-bit and the target pods themselves.

**Comment by edsiper** [comment]
@sagikazarmark 

would you please provide a yaml file that could help to reproduce the problem ?, I checked the code on 0.12 and the fix is in place for the problem reported in #353.

**Comment by sagikazarmark** [comment]
Sure thing. Here is one:

``` yaml
kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: default
spec:
  volumes:
  containers:
    - name: testcontainer
      image: 'deshboard/boilerplate-grpc-service:master'
      ports:
        - name: debug
          containerPort: 10000
          protocol: TCP
        - name: grpc
          containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      livenessProbe:
        httpGet:
          path: /healthz
          port: debug
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /readiness
          port: debug
          scheme: HTTP
        timeoutSeconds: 1
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
    - name: jaeger-agent
      image: jaegertracing/jaeger-agent
      command:
        - /go/bin/agent-linux
        - '--collector.host-port=tracer-jaeger-collector.tracing.svc:14267'
      ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 5778
          protocol: TCP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
```
