### ISSUE TITLE
kubernetes fluent bit crashed with error when try to find container

### ISSUE THREAD

**Issue by juicycool92** [fluent/fluent-bit#3934]
## Bug Report

**Describe the bug**
after boot fluent-bit, i realise that daemonset is keed died without speacial warning.
therefor i checked log with  `kubectl logs daemonset/fluent-bit --namespace kube-system`
below is full lof for daemonset's log.

```
Found 3 pods, using pod/fluent-bit-4zk8c
Fluent Bit v1.2.2
Copyright (C) Treasure Data

[2021/08/09 06:56:30] [ info] [storage] initializing...
[2021/08/09 06:56:30] [ info] [storage] in-memory
[2021/08/09 06:56:30] [ info] [storage] normal synchronization mode, checksum disabled, max_chunks_up=128
[2021/08/09 06:56:30] [ info] [engine] started (pid=1)
[2021/08/09 06:56:30] [ info] [filter_kube] https=1 host=kubernetes.default.svc port=443
[2021/08/09 06:56:30] [ info] [filter_kube] local POD info OK
[2021/08/09 06:56:30] [ info] [filter_kube] testing connectivity with API server...
[2021/08/09 06:56:30] [ info] [filter_kube] API server connectivity OK
[2021/08/09 06:56:30] [ info] [http_server] listen iface=0.0.0.0 tcp_port=2020
[2021/08/09 06:56:30] [ info] [sp] stream processor started
[engine] caught signal (SIGTERM)
[2021/08/09 06:59:09] [ info] [input] pausing tail.0
[2021/08/09 06:59:09] [ warn] [engine] service will stop in 5 seconds
[2021/08/09 06:59:13] [ info] [engine] service stopped
[2021/08/09 06:59:13] [ info] [input] pausing tail.0
rpc error: code = NotFound desc = an error occurred when try to find container "a1ccb520e0c106b0dd7c2e899721f4b4d3fe666da98e1e52a93b826b357c2096": not found
```

**To Reproduce**
- Running on AKS, 1.18 version
- ordinary app for producing log in stdout and stderr.
- fluentbit.yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: kube-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: kube-system
  labels:
    k8s-app: fluent-bit-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: fluent-bit-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluent-bit-logging
        version: v1
        kubernetes.io/cluster-service: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "2020"
        prometheus.io/path: /api/v1/metrics/prometheus
        k8s-logging.exclude: "true"
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 2020
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "elasticsearch.default.svc.cluster.local"
        - name: FLUENT_ELASTICSEARCH_PORT 
          value: "9200"
        - name: FLUENT_CONTAINER_TAIL_EXCLUDE_PATH
          value: /var/log/containers/fluent*
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        # - name: varlibdockercontainers
        #   mountPath: /var/lib/docker/containers
        #   readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
        # - name: mnt
        #   mountPath: /mnt
        #   readOnly: true
        - name: dockercontainerlogdirectory
          mountPath: /var/log/pods
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      # - name: varlibdockercontainers
      #   hostPath:
      #     path: /var/lib/docker/containers
      - name: dockercontainerlogdirectory
        hostPath:
          path: /var/log/pods
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      # - name: mnt
      #   hostPath:
      #     path: /mnt
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule

---

apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    k8s-app: fluent-bit-logging
  name: fluent-bit-config
  namespace: kube-system

data:
   # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/*.log
        Exclude_Path      /var/log/kube-system_fluent*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     15MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Replace_Dots    On
        Retry_Limit     False

  parsers.conf: |
    [PARSER]
        Name   apache
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache2
        Format regex
        Regex  ^(?<host>[^ ]*) [^ ]* (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   apache_error
        Format regex
        Regex  ^\[[^ ]* (?<time>[^\]]*)\] \[(?<level>[^\]]*)\](?: \[pid (?<pid>[^\]]*)\])?( \[client (?<client>[^\]]*)\])? (?<message>.*)$

    [PARSER]
        Name   nginx
        Format regex
        Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)")?$
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On

    [PARSER]
        # http://rubular.com/r/tjUt3Awgg4
        Name cri
        Format regex
        Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    [PARSER]
        Name        syslog
        Format      regex
        Regex       ^\<(?<pri>[0-9]+)\>(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\])?(?:[^\:]*\:)? *(?<message>.*)$
        Time_Key    time
        Time_Format %b %d %H:%M:%S
```
- elasticSearch.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:6.4.0
        env:
        - name: discovery.type
          value: "single-node"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: azure
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: azure
        azureFile:
          secretName: azure-secret
          shareName: aksshare
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch-svc
  namespace: default
spec:
  ports:
  - name: elasticsearch-rest
    nodePort: 30920   #(2)Node의 port
    port: 9200        #(3)Service의 port
    protocol: TCP
    targetPort: 9200  #(4)Pod의 port
  - name: elasticsearch-nodecom
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300
  selector:
    app: elasticsearch
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  type: LoadBalancer
  ports:
  - port: 9200
  selector:
    app: elasticsearch
```
(for security, I didnt post pvc and configmap for ES and my App.
but I checked with `fluent/fluentd-kubernetes-daemonset` to insert, and it work fine.)

no matter what I set on configmap(although I dont know how to set yet), it appears to be dead after 1-3 minutes after start daemonset.

**Expected behavior**

best is working, at least it display more clearly error log for debug.

**Screenshots**

![image](https://user-images.githubusercontent.com/12273678/128790077-62434c3f-a6bf-4b1f-95f1-f5fc32f8d7a3.png)

**Your Environment**

* Version used: k8s 1.18 / fluent-bit 1.2 / elastic-search 6.4.0
* Configuration: 
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: AKS
* Operating System and version:
* Filters and plugins: not sure

**Additional context**

Frankly, kubernetes and logging system is totally new to me.
therefore i might be missing or totally wrong.
But i want to collect my pods log espacially my server's

i tried fluentd first, and it have quite same error,
fluentd will keep trying to read fluendt's own log at `/var/log/pods/fluentd-*` and somehow, always crashed after 1-5 minutes.
therefore I set ENV for exclude pod for tail as `/var/log/pods/fluentd-*`.
after I set, it stop producing error. 

accroading to previous experience, i trying to exclude fluent-bit's pod log, just in case.
but seems like i set wrong, or that is not a probloms.

error log said: it failed to tail specificated container "a1ccb520e0c106b0dd7c2e899721f4b4d3fe666da98e1e52a93b826b357c2096" I guess.

but I have no idea what is  container "a1ccb520e0c106b0dd7c2e899721f4b4d3fe666da98e1e52a93b826b357c2096" mean.

![image](https://user-images.githubusercontent.com/12273678/128790976-331c49c3-6407-4335-8ca1-727518b136f5.png)
<for just in case, I upload my pods list>

these steps are all I tried till today.
any help will appreciated.

Thanks!
