### ISSUE TITLE
Datadog output failing to flush chunks

### ISSUE THREAD

**Issue by ssplatt** [fluent/fluent-bit#4157]
Fluent-bit 1.8.7, AWS for fluent 2.20.0.  Running in AWS Fargate using Firelens.

Datadog output does deliver some logs but drops many.

Many messages per minute like `[2021/10/04 13:56:07] [ warn] [engine] failed to flush chunk '1-1633355763.278469126.flb', retry in 10 seconds: task_id=0, input=forward.1 > output=datadog.1 (out_id=1)` followed by `[2021/10/04 13:56:17] [ warn] [engine] chunk '1-1633355763.278469126.flb' cannot be retried: task_id=0, input=forward.1 > output=datadog.1`. All of our services running fb 1.8.7/awsffb 2.20.0 are throwing this same error, in multiple environments.

cloudformation example:
```
...
        LogConfiguration:
            LogDriver: awsfirelens
            Options:
              Name: datadog
              TLS: 'on'
              compress: gzip
              apikey: '${DD_API_KEY}'
              dd_service: !Ref ServiceName
              dd_source: nginx
              Log_Level: warning
...
       - Name: log_router
          Image: public.ecr.aws/aws-observability/aws-for-fluent-bit:2.20.0
          Essential: true
          MemoryReservation: 50
          Secrets:
            - Name: DD_API_KEY
              ValueFrom: DdApiKey
          FirelensConfiguration:
            Type: fluentbit
            Options:
              enable-ecs-log-metadata: 'true'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGroup
              awslogs-stream-prefix: ecs
```
