### ISSUE TITLE
Build failure on ubuntu 20.4 (focal) with fluentbit 1.8

### ISSUE THREAD

**Issue by zenbones** [fluent/fluent-bit#4180]
Our previously working ansible install now gives this error...

FAILED! => {"changed": false, "msg": "Failed to update apt cache: E:The repository 'https://packages.fluentbit.io/ubuntu/focal focal Release' does not have a Release file."}

Maybe there a missing or corrupt package?

**Comment by aaabdallah** [comment]
> 
> 
> Same here.
> 
> `apt-get update && apt-get install ca-certificates` fixed this.

Thanks for that, this worked for me as well... in spite of getting 404, etc. via curl.

**Comment by FlorinAndrei** [comment]
I am still seeing this issue on Ubuntu 20.04. The part that fails is an Ansible task:

```
- name: add fluentbit repository
  apt_repository:
    repo: "deb https://packages.fluentbit.io/ubuntu/{{ ubuntu_version_name }} {{ ubuntu_version_name }} main"
    update_cache: true
    filename: fluentbit
    state: present
```

The task creates a repo file with the content shown below, and then performs `apt-get update`. This is the repo file:

```
deb https://packages.fluentbit.io/ubuntu/focal focal main
```

Installing `ca-certificates` and `apt-transport-https` does not help.

**Comment by Friz-zy** [comment]
@FlorinAndrei try `apt-get update && apt-get upgrade` maybe, or even `apt-get dist-upgrade`

**Comment by FlorinAndrei** [comment]
@Friz-zy yes, `apt-get update && apt-get upgrade` fixes it, thank you. That means one of the packages is outdated. But which one? A lot of them are upgraded when I do that.

```
accountsservice
alsa-ucm-conf
apport
apt
apt-utils
base-files
bind9-host
busybox-initramfs
busybox-static
ca-certificates
cloud-init
cloud-initramfs-copymods
cloud-initramfs-dyn-netconf
command-not-found
cpio
curl
dirmngr
distro-info-data
ec2-hibinit-agent
ec2-instance-connect
friendly-recovery
git
git-man
gnupg
gnupg-l10n
gnupg-utils
gpg
gpg-agent
gpg-wks-client
gpg-wks-server
gpgconf
gpgsm
gpgv
grub-common
grub-pc
grub-pc-bin
grub2-common
initramfs-tools
initramfs-tools-bin
initramfs-tools-core
isc-dhcp-client
isc-dhcp-common
krb5-locales
landscape-common
libaccountsservice0
libapt-pkg6.0
libasound2
libasound2-data
libc-bin
libcurl3-gnutls
libcurl4
libdrm-common
libdrm2
libefiboot1
libefivar1
libgcrypt20
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libgnutls30
libgssapi-krb5-2
libhogweed5
libicu66
libk5crypto3
libkrb5-3
libkrb5support0
libldap-2.4-2
libldap-common
liblz4-1
libmaxminddb0
libnetplan0
libnettle7
libnss-systemd
libntfs-3g883
libp11-kit0
libpam-modules
libpam-modules-bin
libpam-runtime
libpam-systemd
libpam0g
libparted2
libpci3
libplymouth5
libpolkit-agent-1-0
libpolkit-gobject-1-0
libprocps8
libproxy1v5
libseccomp2
libssh-4
libssl1.1
libsystemd0
libtdb1
libudev1
libuv1
libx11-6
libx11-data
libxml2
libxmlb1
libzstd1
linux-base
linux-libc-dev
locales
login
lshw
lsof
lz4
motd-news-config
netplan.io
networkd-dispatcher
ntfs-3g
open-iscsi
open-vm-tools
openssh-client
openssh-server
openssh-sftp-server
openssl
overlayroot
parted
passwd
pciutils
plymouth
plymouth-theme-ubuntu-text
policykit-1
pollinate
procps
python-apt-common
python3-apport
python3-apt
python3-commandnotfound
python3-cryptography
python3-distupgrade
python3-distutils
python3-gdbm
python3-lib2to3
python3-problem-report
python3-software-properties
python3-twisted
python3-twisted-bin
python3-update-manager
python3-yaml
rsync
screen
snapd
software-properties-common
sosreport
squashfs-tools
sudo
systemd
systemd-sysv
systemd-timesyncd
tar
tmux
tzdata
ubuntu-keyring
ubuntu-release-upgrader-core
udev
ufw
update-manager-core
update-notifier-common
vim
vim-common
vim-runtime
vim-tiny
wget
xxd
```

**Comment by FlorinAndrei** [comment]
@Friz-zy Got it fixed by making sure this task actually updates these packages if an update is available (as opposed to just making sure they are installed). So it must be one of these:

```
- name: install extra apps
  apt:
    name:
      - mc
      - nmap
      - bind9
      - jq
      - zip
      - adduser
      - libfontconfig1
      - binutils
      - python3
      - python3-pip
      - apt-transport-https
      - ca-certificates
    state: latest
    update_cache: yes
```

My bet is on `ca-certificates`.
