### ISSUE TITLE
windows deployment not work when the actual docker container logs located in diffirent drive

### ISSUE THREAD

**Issue by xiaoping8385** [fluent/fluent-bit#4202]
## Bug Report

**Describe the bug**
According to the guide of windows deployment, https://docs.fluentbit.io/manual/installation/kubernetes, user may need to set deploy yaml as 
```
 spec:
  containers:
    - name: fluent-bit
      ..
      volumeMounts:
      - mountPath: C:\k
        name: k
      - mountPath: C:\var\log
        name: varlog
      - mountPath: C:\ProgramData
        name: progdata
  volumes:
  - name: k
    hostPath:
      path: C:\k
  - name: varlog
    hostPath:
      path: C:\var\log
  - name: progdata
    hostPath:
      path: C:\ProgramData
```
where it is by default expect that the  "C:\var\log\containers\<pod>_<namespace>_<container>-<docker>.log"  is actually a symlink to the Docker log file in C:\ProgramData\, with some additional metadata on its file name."
However, in our windows environment, 
we don't write the docker logs to  C:\ProgramData\, check that in our env, we get:

```
PS C:\ProgramData\docker> ls


    Directory: C:\ProgramData\docker


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/14/2021   3:17 AM                config
d-----       10/14/2021   3:17 AM                exec-root
-a----       10/14/2021   3:17 AM              4 docker.pid

C:\var\log\containers>dir /a 
 Volume in drive C has no label. 
 Volume Serial Number is C8E1-8AD7

 Directory of C:\var\log\containers

10/19/2021  12:40 PM    <DIR>          .
10/19/2021  12:40 PM    <DIR>          ..
10/19/2021  09:07 AM    <SYMLINK>      fluent-bit-windows-248nl_pks-system_fluent-bit-e877ee5c5e0311b55dcbbcde5a17b0ae29b393aa9f8f2b633f4b33f15dc95cd7.log [\var\log\pods\pks-system_fluent-bit-windows-248nl
_52dc990b-aeeb-429f-a689-7c8658227ddb\fluent-bit\23.log]
10/19/2021  03:29 AM    <SYMLINK>      logspewer-d47c9d5df-rms4k_pks-system_logspewer-673553a263e3fefe7929d6b782d551228028cbcc8f7b4c551253934c53cf0215.log [\var\log\pods\pks-system_logspewer-d47c9d5df-rms4
k_1b522a57-ca4f-4273-a1eb-a0e59b5cded1\logspewer\0.log]
10/19/2021  06:41 AM    <SYMLINK>      logspewer2-75fdb89fd7-6sxrr_pks-system_logspewer-6ce025999f8b069dab0e02146bba875c1b487bc2f7a86b974dab7261622d9f74.log [\var\log\pods\pks-system_logspewer2-75fdb89fd7-
6sxrr_6c649a5f-9626-4033-8c16-e41229c41244\logspewer\0.log]
               3 File(s)              0 bytes
               2 Dir(s)  30,893,711,360 bytes free
```
as we can see it points to the /var/log/pods as it's target, if we check that targets, we found it as well a symbolic path, which point to a target E:\docker-root\containers 
```
C:\var\log\pods>dir /a 
 Volume in drive C has no label. 
 Volume Serial Number is C8E1-8AD7

 Directory of C:\var\log\pods

10/19/2021  07:28 AM    <DIR>          .
10/19/2021  07:28 AM    <DIR>          ..
10/19/2021  07:27 AM    <DIR>          pks-system_fluent-bit-windows-248nl_52dc990b-aeeb-429f-a689-7c8658227ddb
10/19/2021  03:29 AM    <DIR>          pks-system_logspewer-d47c9d5df-rms4k_1b522a57-ca4f-4273-a1eb-a0e59b5cded1
10/19/2021  06:41 AM    <DIR>          pks-system_logspewer2-75fdb89fd7-6sxrr_6c649a5f-9626-4033-8c16-e41229c41244
               0 File(s)              0 bytes
               5 Dir(s)  30,893,711,360 bytes free

C:\var\log\pods\pks-system_fluent-bit-windows-248nl_52dc990b-aeeb-429f-a689-7c8658227ddb\fluent-bit>dir /a 
 Volume in drive C has no label. 
 Volume Serial Number is C8E1-8AD7

 Directory of C:\var\log\pods\pks-system_fluent-bit-windows-248nl_52dc990b-aeeb-429f-a689-7c8658227ddb\fluent-bit

10/19/2021  09:07 AM    <DIR>          .
10/19/2021  09:07 AM    <DIR>          ..
10/19/2021  09:07 AM    <SYMLINK>      23.log [E:\docker-root\containers\e877ee5c5e0311b55dcbbcde5a17b0ae29b393aa9f8f2b633f4b33f15dc95cd7\e877ee5c5e0311b55dcbbcde5a17b0ae29b393aa9f8f2b633f4b33f15dc95cd7-js
on.log]
               1 File(s)              0 bytes
               2 Dir(s)  30,893,711,360 bytes free
```
and if we check that target, we get:
```
E:\docker-root\containers\884a59b1a64d4f32083b4118e6017e0fd91df3736684df10ebe848ac4ef7f169> ls


    Directory: E:\docker-root\containers\884a59b1a64d4f32083b4118e6017e0fd91df3736684df10ebe848ac4ef7f169


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       10/19/2021   6:41 AM                checkpoints
-a----       10/19/2021   1:12 PM        2333695 884a59b1a64d4f32083b4118e6017e0fd91df3736684df10ebe848ac4ef7f169-json.log
-a----       10/19/2021   6:41 AM           2815 config.v2.json
-a----       10/19/2021   6:41 AM           1239 hostconfig.json
```

```
If I mount this E:\docker-root\containers\  like this:
```volumeMounts:
        - mountPath: /var/log
          name: varlog
          readOnly: false
        - mountPath: /fluent-bit/etc
          name: fluent-bit-windows-config
        - mountPath: E:/docker-root/containers
          name: rootcontainers
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: rootcontainers
        hostPath:
          path: E:/docker-root/containers
      - configMap:
          defaultMode: 420
          name: fluent-bit-windows-config
        name: fluent-bit-windows-config
      serviceAccountName: fluent-bit-win
```
and set the fluent.conf as this:
```fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     debug
        Daemon        off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Tag               kube.*
        Path              C:/var/log/containers/*.log
        Parser            docker
        DB                /var/log/flb_kube1.db
        Skip_Long_Lines   On
        Refresh_Interval  60

    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc.cluster.local:443
        Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
        Merge_Log           On
        Merge_Log_Key       log_processed
        K8S-Logging.Parser  On
        K8S-Logging.Exclude Off
        Kube_Tag_Prefix     kube.C.ProgramData.Docker.containers

    [OUTPUT]
        Name          syslog
        Match          *
        Host          10.199.70.173
        Port          9543
        Mode          tcp
  parsers.conf: |
    [PARSER]
        Name   json
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
```
then if I deploy fluent-bit,  I will get a pod failure as 
```
NAMESPACE     NAME                                                              READY   STATUS             RESTARTS        AGE
pks-system    fluent-bit-windows-kf5sn                                          0/1     CrashLoopBackOff   7 (3m37s ago)   15m
```
and check the log, I get:
 ```
kubo@jumper:~/fluentbit-test$ kubectl logs fluent-bit-windows-kf5sn -n pks-system
failed to try resolving symlinks in path "\\var\\log\\pods\\pks-system_fluent-bit-windows-kf5sn_34fbad6f-c6f1-497c-9914-03d736c63e81\\fluent-bit\\7.log": CreateFile \var\log\pods\pks-system_fluent-bit-windows-kf5sn_34fbad6f-c6f1-497c-9914-03d736c63e81\fluent-bit\7.log: The system cannot find the file specified.
```

**To Reproduce**
see above

**Expected behavior**
it should worked.

**Your Environment**
* Version used: fluent-bit:  1.8 ,k8s: 1.22, docker version:client/server: 1.41
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?):k8s 1.22, windows version:
```

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      17763  0

```
So it looks like fluent-bit can not resolve the E: dirve as it's symbolic path's  target, I also check if there is a E drive been created inside container, and the answer is NO.
Could someone take a look at this, thanks!
