### ISSUE TITLE
in_tail data loss with low Mem_Buf_Limit and single line files

### ISSUE THREAD

**Issue by pcolazurdo** [fluent/fluent-bit#4273]
## Bug Report

**Describe the bug**
With 1.8.9 I'm seeing Data Loss (records missing) in in_tail when a low ```Mem_Buf_Limit``` and ```Multiline  On``` but the files are single line. The problem is manifested with any Output plugin but is exacerbated if Workers are above 1.
The only obvious evidence of this is a lower number of ```records``` in the tail plugin metrics and a message in the log file that looks like:
```
[2021/11/03 09:37:07] [ warn] [input] tail.0 paused (mem buf overlimit)
[2021/11/03 09:37:07] [ info] [input] tail.0 resume (mem buf overlimit)
```

**This doesn't seem to happen with 1.8.2-debug (docker) - will bisect later** 

**To Reproduce**

- Example log message if applicable:
```
[2021/11/03 09:37:07] [ warn] [input] tail.0 paused (mem buf overlimit)
[2021/11/03 09:37:07] [ info] [input] tail.0 resume (mem buf overlimit)
```
- Steps to reproduce the problem:
* Set ```fluent-bit.conf``` like this:
```
[SERVICE]
    Flush                     1
    Daemon                    off
    Log_Level                 info
    Parsers_File              parser.conf
    HTTP_Server               On
    HTTP_Listen               0.0.0.0
    HTTP_PORT                 2020
    storage.path              /storage
    storage.metrics           on
    storage.backlog.mem_limit 1000MB

[INPUT]
    Name              tail
    Path              /data/**/*.txt
    Path_Key          file_name
    Tag               perf
    Buffer_Chunk_Size 1MB
    Buffer_Max_Size   100MB
    Skip_Long_Lines   On
    Multiline         On
    Rotate_Wait       9
    Parser_Firstline  multiline_perf
    Refresh_Interval  1
    Mem_Buf_Limit     20MB
    storage.type     filesystem
    #storage.max_chunks_pause On
    #storage.pause_on_chunks_overlimit On 
    DB                /storage/tail-0.db
    DB.sync           Off
    DB.locking        true
    DB.journal_mode   WAL
    Read_from_Head    True

[OUTPUT]
    Name        null
    Match       *
```
* Create a large file with single line records (1.5GB)
* Count the number of lines in your file
* Monitor ```localhost:2020/api/v1/metrics``` and you'd see that the number of records is lower than the lines in your file. Also if you search for the error message you'll see a repeat of those along the log file.

The key parameters combination that seems to trigger this bug is:
```
[INPUT]
	Name 					tail
	Multiline 				On
	Mem_Buf_Limit 	20MB
```

**Expected behavior**
No data loss should happen even if file is single line file is parsed even if Multiline is on

**Screenshots**

```
# cat /data/test-perf/* | wc -l
9231000
```
```
# du -b  /data/test-perf/
14160378576     /data/test-perf/
```
```
# curl -s localhost:2020/api/v1/metrics | jq -r '.input."tail.0"'
{
  "records": 8831174,
  "bytes": 14005296000,
  "files_opened": 1000,
  "files_closed": 0,
  "files_rotated": 0
}
```

**Your Environment**

* Version used: 1.8.9-debug (docker)
* Configuration: (see above)
* Environment name and version (e.g. Kubernetes? What version?): docker-compose 
```
services:
  fluent-bit:
          #logging:
          #driver: none
    image: fluent/fluent-bit:1.8.9-debug
    #image: fluent-bit:1.9.0p
    volumes:
      - data:/data
      - .:/chunkio:ro
      - storage:/storage:rw
    command: /fluent-bit/bin/fluent-bit -c /chunkio/fluent-bit.conf
    ports:
      - 2020:2020
  perf-tool:
    build:
      context: .
    volumes:
      - data:/data
      - storage:/storage:rw
    depends_on:
      - prometheus
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command:
      - --enable_load_reader=true
    ports:
      - 8081:8080
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - fluent-bit
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    ports:
      - 9090:9090
    command:
      - --config.file=/app/config/prometheus.yml
    volumes:
      - ./:/app/config:ro
      - ./data/prometheus/config:/etc/prometheus/
      - ./data/prometheus/data:/prometheus
    depends_on:
      - cadvisor
volumes:
  data:
  storage:
```
* Server type and version: x86_64 
* Operating System and version: Amazon Linux 2: 5.4.149-73.259.amzn2.x86_64 #1 SMP Mon Sep 27 12:48:12 UTC 2021 x86_64 x86_64
* Filters and plugins: go_gstdout was used but disabling it, it didn't solve the problem

**Additional context**
I was testing reported issues with [#4207](https://github.com/fluent/fluent-bit/pull/4207) and came up with a set of different tests until able to reproduce the reported error consistently. I was able to repro with and without the proposed PR and with even a single file test as noted above.
