### ISSUE TITLE
Fluentbit to Splunk HEC forwarding issue

### ISSUE THREAD

**Issue by IgorEulalio** [fluent/fluent-bit#4585]
## Bug Report

**Describe the bug**
I was using ecs driver logs to forward my logs to splunk. Now, im changing to use firelens, with fluentbit built-in, to send the logs to the same splunk server, using a side car approach.

**To Reproduce**
My configuration using ecs driver logs:
```
          LogConfiguration:
            LogDriver: splunk
            Options:
              splunk-url: <MYHOST>
              splunk-index: <MYINDEX>
              splunk-format: 'raw'
              splunk-token: <MYTOKEN>
```

Now, i have this configuration to fluentbit image:
```
[SERVICE]
    Log_Level debug
[OUTPUT]
    Name                splunk
    Match               *
    Host                <MYHOST>
    Splunk_Token        <MYTOKEN>
    Splunk_Send_Raw     On
    TLS                 On
    TLS.Verify          Off  
[OUTPUT]
    Name                firehose
    Match               *
    region              us-east-1
    delivery_stream     my-kinesis-firehose
```

I configure my task definition like this:
**Fluentbit container definitions**
```
        - Name: FluentBitImage
          Essential: True
          MemoryReservation: 256
          FirelensConfiguration:
            Type: "fluentbit"
            Options:
              config-file-type: "file"
              config-file-value: "/logDestinations.conf"
          Image: <MYCUSTOMIMAGE>
```
**Application:**
```
          LogConfiguration:
            LogDriver: awsfirelens  
```

Running in the same ecs cluster, without modifying network configuration, i cannot reach the domain of my splunk server.

```
 [2022/01/07 00:50:27] [ warn] [net] getaddrinfo(host='<MYHOST>', err=4): Domain name not found
```

**Expected behavior**
Connect with success in splunk and send logs.

**Additional context**
I am running this inside corporate environment, but the previous configuration works well.
Does ECS log driver connect with splunk in a different way?
In the past, we use lambda blueprint to forward logs to splunk, in this case, we use <MYHOST/collector/services> endpoint to send log data. I ve tried with both and still no success.
