### ISSUE TITLE
Unable to install on Raspbian

### ISSUE THREAD

**Issue by walbers** [fluent/fluent-bit#4688]
## Bug Report

**Describe the bug**
I am following the [guide](https://docs.fluentbit.io/manual/installation/linux/raspbian-raspberry-pi) and it doesn't work when I try this with ansible or when I run it manually.

**To Reproduce**
- After adding the key and running `echo "deb https://packages.fluentbit.io/raspbian/buster buster main" >> /etc/apt/sources.list` I get: 
```
Ign:3 https://packages.fluentbit.io/raspbian/buster buster InRelease 
Err:5 https://packages.fluentbit.io/raspbian/buster buster Release 
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Reading package lists... Done                                                                                                                                                                                                                                                                                    E: The repository 'https://packages.fluentbit.io/raspbian/buster buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default. 
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
- This makes it impossible to install `td-agent-bit`
- I also tried these ansible modules:
```
- name: 'Server GPG key'
    become: true                                                                                                                                                                                                                                                                                     
    ansible.builtin.apt_key:
      url: 'https://packages.fluentbit.io/fluentbit.key'
      state: present

- name: 'Update your sources lists Raspbian/Debian'
    become: true                                                                                                                                                                                                                                                                                                     
    ansible.builtin.apt_repository:                                                                                                                                                                                                                                                                                    
      repo: 'deb https://packages.fluentbit.io/raspbian/buster buster main'                                                                                                                                                                                                                                            
      state: present
- 
```
- This also failed with:
```
 msg: 'Failed to update apt cache: E:The repository ''https://packages.fluentbit.io/raspbian/buster buster Release'' does not have a Release file.'
```
- Both of these also happen with `deb https://packages.fluentbit.io/raspbian/stretch stretch main`

**Expected behavior**
To install normally like the ubuntu version did.

**Your Environment**
<!--- Include as many relevant details about the environment you experienced the bug in -->
* Version used: Latest fluent bit version
* Configuration: Defatult everything
* Operating System and version: Raspbian stretch
* Filters and plugins: None

**Additional context**
I am trying to run fluent bit on a raspberry pi.
