### ISSUE TITLE
kafka output contains new timestamp since 1.9.0

### ISSUE THREAD

**Issue by sjpalf** [fluent/fluent-bit#5097]
## Bug Report

**Describe the bug**
Since upgrading to FluentBit 1.9.0 our log pipeline is broken by the kafka output adding an additional field containing the timestamp. The field is added to the json message but is invalid as it contains no name, e.g {"":1647457453.307707}

- Previously the output would have been:
```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","@timestamp":"2018-06-11T14:37:30.681701731Z"}
```
- This is the new output since 1.9.0:
```
{"":1647457453.307707,"log":"YOUR LOG MESSAGE HERE","stream":"stdout","@timestamp":"2018-06-11T14:37:30.681701731Z"}
```
**To Reproduce**
This can be replicated with docker-compose.
docker-compose.yaml:
```
version: "3.7"
services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - 9000:9000
    environment:
      - KAFKA_BROKERCONNECT=kafka:9092
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    hostname: zookeeper
    ports:
      - "32181:32181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:4.1.1
    hostname: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:4.1.1
    hostname: schema-registry
    ports:
      - "38081:38081"
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:32181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:38081
      SCHEMA_REGISTRY_DEBUG: "true"
  fluent-bit:
    image: fluent/fluent-bit:1.9.0
    ports:
      - "2021:2021"
      - "5170:5170"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on:
      - kafka
```
fluent-bit.conf:
```
[SERVICE]
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_PORT    2021
[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Format      json
    Buffer_Size 32M
    Chunk_Size  1024
[OUTPUT]
    Name     kafka
    Match    *
    Brokers  kafka:9092
    Topics   test
```
Then run 
```
nc localhost 5170
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","@timestamp":"2018-06-11T14:37:30.681701731Z"}
```
Then you can view the output messages in kafkdrop by browsing to http://localhost:9000/

**Expected behavior**
* The output sent to kafka should not contain invalid json
* The output sent to kafka should match the output before upgrading to 1.9.0, i.e. it should not contain an additional timestamp field

**Screenshots**
N/A

**Your Environment**
* Version used: 1.9.0
* Configuration:
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    HTTP_Server  On
    HTTP_Listen  127.0.0.1
    HTTP_PORT    2020

[INPUT]
    Name        tcp
    Listen      0.0.0.0
    Port        5170
    Format      json
    Buffer_Size 32M
    Chunk_Size  1024

[OUTPUT]
    Name        kafka
    Match       *
    Brokers     kafka:9092
    Topics      logs
    Retry_Limit 2
```
* Environment name and version (e.g. Kubernetes? What version?): AWS ec2
* Server type and version:
* Operating System and version: Ubuntu 18.04
* Filters and plugins: None

**Additional context**
After processing in kafka we use logstash to write these log records to elasticsearch, but logstash fails to parse the log due to the field with a name of an empty string
