### ISSUE TITLE
Allow specifying Kubelet host

### ISSUE THREAD

**Issue by wmedlar** [fluent/fluent-bit#5143]
**Is your feature request related to a problem? Please describe.**

In order to query pod metadata from the Kubelet, fluent-bit pods must be granted host networking so they can [communicate with the Kubelet over localhost](https://github.com/fluent/fluent-bit/blob/1fa0e94a09e4155f8a6d8a0efe36a5668cdc074e/plugins/filter_kubernetes/kube_conf.h#L58). Host networking is a highly privileged capability, and pods with host networking enabled have a much wider attack surface than those without. There are [other, far more secure, methods](https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables) to communicate with the host's Kubelet.

**Describe the solution you'd like**

Allow the Kubelet host to be specified, similar to the `Kube_URL` setting for the Kubernetes apiserver. We can then inject the Kubelet host with the Downward API. This will allow fluent-bit to communicate with the host's Kubelet over the host's IP and will not require host networking.

```ini
[FILTER]
    Name          kubernetes
    Match         kube.*
    Use_Kubelet   true
    Kubelet_Host  ${KUBELET_HOST}
```

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
spec:
  template:
    spec:
      hostNetwork: false
      containers:
      - name: fluent-bit
         image: fluent/fluent-bit
         env:
         - name: KUBELET_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
```

**Describe alternatives you've considered**

N/A

**Additional context**

Host networking is not just insecure, it also exempts a pod from CNI-based controls such as NetworkPolicy, making it unsuitable for many enterprise environments.
