### ISSUE TITLE
Http input crashes with SIGSEGV on headers from nginx-ingress set to verify client certificate

### ISSUE THREAD

**Issue by jan-hudec** [fluent/fluent-bit#5355]
## Bug Report

Fluent-bit crashes with SIGSEGV when http input is behind an nginx-ingress controller configured to require client certificate.

**To Reproduce**

Deploy with `https://fluent.github.io/helm-charts/fluent/fluent-bit` helm chart, with following values (replace `http-in.monitoring.example.com` for whatever the cluster has):

```
kind: Deployment
ingress:
  enabled: true
  ingressClassName: nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "2"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: http-in.monitoring.example.com
      port: 9880
  tls:
    - hosts:
        - http-in.monitoring.example.com
      secretName: http-in-tls
extraPorts:
  - containerPort: 9880
    name: http-in
    port: 9880
    protocol: TCP
config:
  inputs: |
    [INPUT]
        Name http
# and some output, of course; I have loki, but I don't think it depends on that.
```

Then test with curl
```
curl -i -d @monitoring/json.json -XPOST -H 'content-type: application/json' --cert certs/service-generic-1.crt --key certs/service-generic-1.key https://http-in.monitoring.example.com/something
```

That request results in a 502 bad gateway response and the following appearing in the fluent-bit pod kubernetes log:

```
[2022/04/25 07:24:12] [engine] caught signal (SIGSEGV)
#0  0x55bae4f07351      in  mk_string_itop() at lib/monkey/mk_core/mk_string.c:552
#1  0x55bae4ef4f8d      in  mk_header_prepare() at lib/monkey/mk_server/mk_header.c:316
#2  0x55bae4efcce6      in  mk_http_error() at lib/monkey/mk_server/mk_http.c:1325
#3  0x55bae4efeb55      in  mk_http_parser() at lib/monkey/mk_server/mk_http_parser.c:672
#4  0x55bae4a6c7fd      in  http_conn_event() at plugins/in_http/http_conn.c:83
#5  0x55bae4a15748      in  flb_engine_start() at src/flb_engine.c:766
#6  0x55bae49f6f58      in  flb_lib_worker() at src/flb_lib.c:627
#7  0x7f0f0f836ea6      in  ???() at ???:0
#8  0x7f0f0f138dee      in  ???() at ???:0
#9  0xffffffffffffffff  in  ???() at ???:0
```

- When I connect to the service's port 9880 via kubectl port-forward and send the request directly (without TLS), it works (returns 201 created)
- When I remove the auth-tls annotations and not send a client cert, it also works (201 created).

I didn't try to capture the exact header nginx adds when verifying the client certificate (I can try), but the generated Nginx config says:

```
proxy_set_header ssl-client-verify      $ssl_client_verify;
proxy_set_header ssl-client-subject-dn  $ssl_client_s_dn;
proxy_set_header ssl-client-issuer-dn   $ssl_client_i_dn;
```

**Your Environment**

* Version used: 1.8.15, via `https://fluent.github.io/helm-charts` chart `fluent/fluent-bit` version 1.19.23
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): Azure AKS, kubernetes api 1.21.2
* Ingress controller: ingress-nginx chart version 4.0.2, app version 1.0.1
* Operating System and version: Linux
* Filters and plugins: only default from the chart

**Additional context**

I am trying to connect log collection from devices deployed at customers to central monitoring solution. The devices have outbound connectivity only (so has to be ingress on the central server), and they are (well, will) getting client certificates for authentication also to the application server.
