### ISSUE TITLE
fluent-bit repo data not available for RHEL/CentOS/AlmaLinux/Rocky 9

### ISSUE THREAD

**Issue by vwbusguy** [fluent/fluent-bit#5478]
## Bug Report

**Describe the bug**
While the el8 package appears to work on el9 for now, the default repo config will reference version 9 in the repo URL which doesn't exist.  Adding packages to support the current version of these distributions will make improve the experience of installing fluent-bit.

**To Reproduce**
Attempt to follow any install instructions from https://docs.fluentbit.io/manual/installation/linux/redhat-centos using any EL9 distribution.  

- Steps to reproduce the problem:
Either:
* Run the setup script and note that it fails due to missing packages for the current version
* Follow the manual steps in setting up a repo and note that it fails to install 

**Expected behavior**
The setup script and instructions successfully result in fluent-bit being installed for the current version of these supported distros.

**Your Environment**

* Version used: fluent-bit-1.9.3-1.x86_64
* Configuration: Native RPM install
* Environment name and version (e.g. Kubernetes? What version?): Native RPM install
* Server type and version: Linux
* Operating System and version: CentOS Stream 9
* Filters and plugins: n/a

**Additional context**
For now we've implemented a hacky workaround in Ansible to attempt to identify an EL9 box and override the yum repo to point to the EL8 repos.  The package installs fine for now, but it definitely added to the complexity of adopting fluent-bit to our environment.

Here's our current Ansible workaround in case others are similarly affected by this:
```
- name: Set fluentbit repo release version
  set_fact:
    fb_rel_ver: "{{ ansible_distribution_major_version }}"

- name: Set fluentbit repo release version (EL9)
  set_fact:
    fb_rel_ver: "8"
  when: ansible_distribution_major_version|int == 9

- name: Setup yum repo
  yum_repository:
    name: fluentbit
    description: Fluentbit Repo
    baseurl: "https://packages.fluentbit.io/centos/{{ fb_rel_ver }}/$basearch/"
    enabled: yes
    file: fluentbit
    gpgcheck: yes
    gpgkey: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Import rpm_key
  rpm_key:
    key: https://packages.fluentbit.io/fluentbit.key
    state: present

- name: Install fluentbit
  yum:
    name: fluent-bit
    state: latest
  ```
