### ISSUE TITLE
Parsing issues with docker logs

### ISSUE THREAD

**Issue by Lord-Y** [fluent/fluent-bit#5491]
Hello guys, I think there is an issue with fluentbit parsing with docker logs. It's only docker logs so no kubernetes cluster is involved.
I'm running fluentbit version 1.9.3.
I also have a docker nginx image and the stdout is a structured log like so:
```
{"remote_addr": "172.17.0.1", "remote_user": "", "time_local": "24/May/2022:13:08:42 +0000", "request": "GET / HTTP/1.1", "request_length": 70, "request_time": 0.000, "http_status_code": 200, "bytes_sent": 853, "body_bytes_sent": 615, "http_referer": "", "http_user_agent": "curl/7.68.0", "http_x_forwarded_for": "", "gzip_ratio": , "upstream_addr": "", "upstream_status": "", "upstream_response_length": "", "upstream_response_time": "", "upstream_connect_time": "", "upstream_header_time": "", "request_id": "b8e0e6341a97c407e6ddc634aa71050e"}
```

The docker log file content is:
```
{"log":"{\"remote_addr\": \"172.17.0.1\", \"remote_user\": \"\", \"time_local\": \"24/May/2022:13:08:42 +0000\", \"request\": \"GET / HTTP/1.1\", \"request_length\": 70, \"request_time\": 0.000, \"http_status_code\": 200, \"bytes_sent\": 853, \"body_bytes_sent\": 615, \"http_referer\": \"\", \"http_user_agent\": \"curl/7.68.0\", \"http_x_forwarded_for\": \"\", \"gzip_ratio\": , \"upstream_addr\": \"\", \"upstream_status\": \"\", \"upstream_response_length\": \"\", \"upstream_response_time\": \"\", \"upstream_connect_time\": \"\", \"upstream_header_time\": \"\", \"request_id\": \"b8e0e6341a97c407e6ddc634aa71050e\"}\n","stream":"stdout","time":"2022-05-24T13:08:42.315839142Z"}
```

My fluentbit config is that simple:
```
[INPUT]
    Name             tail
    Path             /var/lib/docker/containers/8278f83dd7dd4982fd57ae65dbcb2c3278abe63ddea54f265f420037eb2f0478/8278f83dd7dd4982fd57ae65dbcb2c3278abe63ddea54f265f420037eb2f0478-json.log
    Parser           docker

#[FILTER]
#    Name         parser
#    Parser       docker
#    Match        *
#    Key_Name     log
#    Reserve_Data On

[OUTPUT]
    #Name  stdout
    #Match *


    Name        es
    Alias       nomad_docker_output
    Match       *
    Host        127.0.0.1
    Port        9200
    Retry_Limit False
    Suppress_Type_Name On
    Logstash_Format On
    Logstash_Prefix docker
    Index       ""
    #Include_Tag_Key On
    #Tag_Key         tag
    HTTP_User   elastic
    HTTP_Passwd elastic
    tls On
    tls.verify Off
    Trace_Error On

```

My parser config:
```
[PARSER]
    Name         docker
    Format       json
    Time_Key     time
    Time_Format  %Y-%m-%dT%H:%M:%S.%L
    Time_Keep    On
    # Command       |  Decoder  | Field | Optional Action   |
    # ==============|===========|=======|===================|
    Decode_Field_As    escaped     log
```

<details>
<summary>My elasticsearch config `~/elasticsearch/docker-compose.yaml` is:</summary>

  ```yml

  version: "2.2"

  services:
    setup:
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      volumes:
        - certs:/usr/share/elasticsearch/config/certs
      user: "0"
      command: >
        bash -c '
          if [ x${ELASTIC_PASSWORD} == x ]; then
            echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
            exit 1;
          elif [ x${KIBANA_PASSWORD} == x ]; then
            echo "Set the KIBANA_PASSWORD environment variable in the .env file";
            exit 1;
          fi;
          if [ ! -f config/certs/ca.zip ]; then
            echo "Creating CA";
            bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
            unzip config/certs/ca.zip -d config/certs;
          fi;
          if [ ! -f config/certs/certs.zip ]; then
            echo "Creating certs";
            echo -ne \
            "instances:\n"\
            "  - name: es01\n"\
            "    dns:\n"\
            "      - es01\n"\
            "      - localhost\n"\
            "    ip:\n"\
            "      - 127.0.0.1\n"\
            "  - name: es02\n"\
            "    dns:\n"\
            "      - es02\n"\
            "      - localhost\n"\
            "    ip:\n"\
            "      - 127.0.0.1\n"\
            "  - name: es03\n"\
            "    dns:\n"\
            "      - es03\n"\
            "      - localhost\n"\
            "    ip:\n"\
            "      - 127.0.0.1\n"\
            > config/certs/instances.yml;
            bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
            unzip config/certs/certs.zip -d config/certs;
          fi;
          echo "Setting file permissions"
          chown -R root:root config/certs;
          find . -type d -exec chmod 750 \{\} \;;
          find . -type f -exec chmod 640 \{\} \;;
          echo "Waiting for Elasticsearch availability";
          until curl -s --cacert config/certs/ca/ca.crt https://es01:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
          echo "Setting kibana_system password";
          until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:${ELASTIC_PASSWORD} -H "Content-Type: application/json" https://es01:9200/_security/user/kibana_system/_password -d "{\"password\":\"${KIBANA_PASSWORD}\"}" | grep -q "^{}"; do sleep 10; done;
          echo "All done!";
        '
      healthcheck:
        test: ["CMD-SHELL", "[ -f config/certs/es01/es01.crt ]"]
        interval: 1s
        timeout: 5s
        retries: 120

    es01:
      depends_on:
        setup:
          condition: service_healthy
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      volumes:
        - certs:/usr/share/elasticsearch/config/certs
        - esdata01:/usr/share/elasticsearch/data
      ports:
        - ${ES_PORT}:9200
      environment:
        - node.name=es01
        - cluster.name=${CLUSTER_NAME}
        - cluster.initial_master_nodes=es01,es02,es03
        - discovery.seed_hosts=es02,es03
        - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
        - bootstrap.memory_lock=true
        - xpack.security.enabled=true
        - xpack.security.http.ssl.enabled=true
        - xpack.security.http.ssl.key=certs/es01/es01.key
        - xpack.security.http.ssl.certificate=certs/es01/es01.crt
        - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.http.ssl.verification_mode=certificate
        - xpack.security.transport.ssl.enabled=true
        - xpack.security.transport.ssl.key=certs/es01/es01.key
        - xpack.security.transport.ssl.certificate=certs/es01/es01.crt
        - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.transport.ssl.verification_mode=certificate
        - xpack.license.self_generated.type=${LICENSE}
      mem_limit: ${MEM_LIMIT}
      ulimits:
        memlock:
          soft: -1
          hard: -1
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
          ]
        interval: 10s
        timeout: 10s
        retries: 120

    es02:
      depends_on:
        - es01
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      volumes:
        - certs:/usr/share/elasticsearch/config/certs
        - esdata02:/usr/share/elasticsearch/data
      environment:
        - node.name=es02
        - cluster.name=${CLUSTER_NAME}
        - cluster.initial_master_nodes=es01,es02,es03
        - discovery.seed_hosts=es01,es03
        - bootstrap.memory_lock=true
        - xpack.security.enabled=true
        - xpack.security.http.ssl.enabled=true
        - xpack.security.http.ssl.key=certs/es02/es02.key
        - xpack.security.http.ssl.certificate=certs/es02/es02.crt
        - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.http.ssl.verification_mode=certificate
        - xpack.security.transport.ssl.enabled=true
        - xpack.security.transport.ssl.key=certs/es02/es02.key
        - xpack.security.transport.ssl.certificate=certs/es02/es02.crt
        - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.transport.ssl.verification_mode=certificate
        - xpack.license.self_generated.type=${LICENSE}
      mem_limit: ${MEM_LIMIT}
      ulimits:
        memlock:
          soft: -1
          hard: -1
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
          ]
        interval: 10s
        timeout: 10s
        retries: 120

    es03:
      depends_on:
        - es02
      image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
      volumes:
        - certs:/usr/share/elasticsearch/config/certs
        - esdata03:/usr/share/elasticsearch/data
      environment:
        - node.name=es03
        - cluster.name=${CLUSTER_NAME}
        - cluster.initial_master_nodes=es01,es02,es03
        - discovery.seed_hosts=es01,es02
        - bootstrap.memory_lock=true
        - xpack.security.enabled=true
        - xpack.security.http.ssl.enabled=true
        - xpack.security.http.ssl.key=certs/es03/es03.key
        - xpack.security.http.ssl.certificate=certs/es03/es03.crt
        - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.http.ssl.verification_mode=certificate
        - xpack.security.transport.ssl.enabled=true
        - xpack.security.transport.ssl.key=certs/es03/es03.key
        - xpack.security.transport.ssl.certificate=certs/es03/es03.crt
        - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
        - xpack.security.transport.ssl.verification_mode=certificate
        - xpack.license.self_generated.type=${LICENSE}
      mem_limit: ${MEM_LIMIT}
      ulimits:
        memlock:
          soft: -1
          hard: -1
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
          ]
        interval: 10s
        timeout: 10s
        retries: 120

    kibana:
      depends_on:
        es01:
          condition: service_healthy
        es02:
          condition: service_healthy
        es03:
          condition: service_healthy
      image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
      volumes:
        - certs:/usr/share/kibana/config/certs
        - kibanadata:/usr/share/kibana/data
      ports:
        - ${KIBANA_PORT}:5601
      environment:
        - SERVERNAME=kibana
        - ELASTICSEARCH_HOSTS=https://es01:9200
        - ELASTICSEARCH_USERNAME=kibana_system
        - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
        - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      mem_limit: ${MEM_LIMIT}
      healthcheck:
        test:
          [
            "CMD-SHELL",
            "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
          ]
        interval: 10s
        timeout: 10s
        retries: 120

  volumes:
    certs:
      driver: local
    esdata01:
      driver: local
    esdata02:
      driver: local
    esdata03:
      driver: local
    kibanadata:
      driver: local
  ```
</details>

My `~/elasticsearch/.env` content is:
```
# Password for the 'elastic' user (at least 6 characters)
ELASTIC_PASSWORD=elastic

# Password for the 'kibana_system' user (at least 6 characters)
KIBANA_PASSWORD=kibana_system

# Version of Elastic products
STACK_VERSION=8.2.0

# Set the cluster name
CLUSTER_NAME=docker-cluster

# Set to 'basic' or 'trial' to automatically start the 30-day trial
LICENSE=basic
#LICENSE=trial

# Port to expose Elasticsearch HTTP API to the host
ES_PORT=9200
#ES_PORT=127.0.0.1:9200

# Port to expose Kibana to the host
KIBANA_PORT=5601
#KIBANA_PORT=80

# Increase or decrease based on the available host memory (in bytes)
MEM_LIMIT=1073741824

# Project namespace (defaults to the current folder name if not set)
#COMPOSE_PROJECT_NAME=myproject
```

and then:
```
cd ~/elasticsearch/ && sudo docker-compose up -d
```

My `~/elasticsearch/nginx.conf` config is:
```
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    map $http_x_request_id $req_id {
        default   $http_x_request_id;
        ""        $request_id;
    }

    log_format main escape=json '{'
          '"remote_addr": "$remote_addr", '
          '"remote_user": "$remote_user", '
          '"time_local": "$time_local", '
          '"request": "$request", '
          '"request_length": $request_length, '
          '"request_time": $request_time, '
          '"http_status_code": $status, '
          '"bytes_sent": $bytes_sent, '
          '"body_bytes_sent": $body_bytes_sent, '
          '"http_referer": "$http_referer", '
          '"http_user_agent": "$http_user_agent", '
          '"http_x_forwarded_for": "$http_x_forwarded_for", '
          '"gzip_ratio": $gzip_ratio, '
          '"upstream_addr": "$upstream_addr", '
          '"upstream_status": "$upstream_status", '
          '"upstream_response_length": "$upstream_response_length", '
          '"upstream_response_time": "$upstream_response_time", '
          '"upstream_connect_time": "$upstream_connect_time", '
          '"upstream_header_time": "$upstream_header_time", '
          '"request_id": "$req_id"'
          '}';


    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

```

Run it with:
```
sudo docker run -d -v ~/elasticsearch/nginx.conf:/etc/nginx/nginx.conf -p 8080:80 nginx:latest
```

When I try stdout output is ALWAYS:
```
[0] tail.0: [1653396183.873300175, {"log"=>"{"remote_addr": "172.17.0.1", "remote_user": "", "time_local": "24/May/2022:12:43:02 +0000", "request": "GET / HTTP/1.1", "request_length": 70, "request_time": 0.000, "http_status_code": 200, "bytes_sent": 853, "body_bytes_sent": 615, "http_referer": "", "http_user_agent": "curl/7.68.0", "http_x_forwarded_for": "", "gzip_ratio": , "upstream_addr": "", "upstream_status": "", "upstream_response_length": "", "upstream_response_time": "", "upstream_connect_time": "", "upstream_header_time": "", "request_id": "5bd4fa16a6f3dd3fb6615199d5151511"}", "stream"=>"stdout", "time"=>"2022-05-24T12:43:03.873300175Z"}]
```

instead of a true json:
```
[0] tail.0: [1653396183.873300175, {"log"=>{"remote_addr": "172.17.0.1", "remote_user": "", "time_local": "24/May/2022:12:43:02 +0000", "request": "GET / HTTP/1.1", "request_length": 70, "request_time": 0.000, "http_status_code": 200, "bytes_sent": 853, "body_bytes_sent": 615, "http_referer": "", "http_user_agent": "curl/7.68.0", "http_x_forwarded_for": "", "gzip_ratio": , "upstream_addr": "", "upstream_status": "", "upstream_response_length": "", "upstream_response_time": "", "upstream_connect_time": "", "upstream_header_time": "", "request_id": "5bd4fa16a6f3dd3fb6615199d5151511"}, "stream"=>"stdout", "time"=>"2022-05-24T12:43:03.873300175Z"}]
```

Is is something normal? Following the doc [here](https://docs.fluentbit.io/manual/pipeline/parsers/decoders) we are supposed to have a well parsed json object.

I tried to use some filters in order to have a true json or playing with Decode_Field_As (escaped/escaped_utf8 etc) but it just does work.
I'm opening this issue because I thing something is wrong with the parser.

With the elasticsearch output and the filter uncommented, the log key is parsed as a text because the inital parsing is not a true json but a string.
The result in elasticsearch is:
```
# curl -u elastic:elastic -kv https://127.0.0.1:9200/docker-2022.05.24/_search -H "content-type: application/json" | jq -r .
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 3,
    "successful": 3,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 15,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "docker-2022.05.24",
        "_id": "qmqZ9oABp7RKph9vhdeg",
        "_score": 1,
        "_ignored": [
          "log.keyword"
        ],
        "_source": {
          "@timestamp": "2022-05-24T15:04:57.072Z",
          "log": "{\"remote_addr\": \"172.17.0.1\", \"remote_user\": \"\", \"time_local\": \"24/May/2022:15:04:57 +0000\", \"request\": \"GET / HTTP/1.1\", \"request_length\": 70, \"request_time\": 0.000, \"http_status_code\": 200, \"bytes_sent\": 853, \"body_bytes_sent\": 615, \"http_referer\": \"\", \"http_user_agent\": \"curl/7.68.0\", \"http_x_forwarded_for\": \"\", \"gzip_ratio\": , \"upstream_addr\": \"\", \"upstream_status\": \"\", \"upstream_response_length\": \"\", \"upstream_response_time\": \"\", \"upstream_connect_time\": \"\", \"upstream_header_time\": \"\", \"request_id\": \"c4e32919530ddbbc3cf86109427f5332\"}\n",
          "stream": "stdout",
          "time": "2022-05-24T15:04:57.072177639Z"
        }
      },
```
The expected result is:
```
{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 3,
    "successful": 3,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 15,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "docker-2022.05.24",
        "_id": "qmqZ9oABp7RKph9vhdeg",
        "_score": 1,
        "_ignored": [
          "log.keyword"
        ],
        "_source": {
          "@timestamp": "2022-05-24T15:04:57.072Z",
          "log": {"remote_addr": "172.17.0.1", "remote_user": "", "time_local": "24/May/2022:15:04:57 +0000", "request": "GET / HTTP/1.1", "request_length": 70, "request_time": 0.000, "http_status_code": 200, "bytes_sent": 853, "body_bytes_sent": 615, "http_referer": "", "http_user_agent": "curl/7.68.0", "http_x_forwarded_for": "", "gzip_ratio": , "upstream_addr": "", "upstream_status": "", "upstream_response_length": "", "upstream_response_time": "", "upstream_connect_time": "", "upstream_header_time": "", "request_id": "c4e32919530ddbbc3cf86109427f5332"},
          "stream": "stdout",
          "time": "2022-05-24T15:04:57.072177639Z"
        },
         "fields": {
           "remote_addr": [
               "172.17.0.1"
           ],
           "remote_user": [
               ""
           ],
           ...
           ......
           .........
         }
      },

OS:
```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```

Docker logging driver:
```
Logging Driver: json-file
```

Docker version
```
docker version
Client: Docker Engine - Community
 Version:           20.10.14
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 24 01:48:21 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.14
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       87a90dc
  Built:            Thu Mar 24 01:46:14 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.11
  GitCommit:        3df54a852345ae127d1fa3092b95168e4a88e2f8
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

Feel free to tell me if I'm doing something wrong or if it's really a bug :-)
Thx.
