### ISSUE TITLE
read error, check permissions & error scanning path

### ISSUE THREAD

**Issue by da-head0** [fluent/fluent-bit#5501]
## Bug Report

**Describe the bug**

I collect logs by fluent-bit, in custom path like `/var/log/containers/mycustompath/` not only from `/var/log/containers/~`.
but I've seen those logs from few days ago. 

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
```
[2022/05/24 00:46:18] [error] [input:tail:tail.0] read error, check permissions: /var/log/containers/*/custom*.log
[2022/05/24 00:46:18] [ warn] [input:tail:tail.0] 32we: /var/log/containers/*/custom*.log
[2022/05/25 09:51:58] [error] [input:tail:tail.0] read error, check permissions: /var/log/containers/*/custom*.log
[2022/05/25 09:51:58] [ warn] [input:tail:tail.0] error scanning path: /var/log/containers/*/custom*.log
```
- Steps to reproduce the problem:

**Expected behavior**

Fluent-bit should collect logs as usual, without those logs above.
**But in overall, fluent-bit collect & send logs like in normal way.** 
But **those error happens like 1-2 times in a day, in few pods**

**Screenshots**

**Your Environment**

* Version used: 1.8.14 (aws-for-fluent-bit:2.23.2)
* Configuration: 

This is my configmap file.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: de
  labels:
    app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         5
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020
        storage.path  /var/log/flb-storage/

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-s3.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Buffer_Chunk_Size 2MB
        Buffer_Max_Size   50M
        Tag               appexception.*
        Path              /var/log/containers/*/custom_a*.log, /var/log/containers/*/custom_b*.log
        Multiline         On
        Parser_Firstline  multiline
        Skip_Empty_Lines  On
        Skip_Long_Lines   Off
        storage.type      filesystem
        DB                /var/log/flb_kube.db
        Path_Key          path
        Refresh_Interval  10
        Ignore_Older      10h

    [INPUT]
        Name              tail
        Tag               etc.*
        Path              /var/log/containers/*/custom*.log
        Exclude_Path      /var/log/containers/*/custom_a*.log, /var/log/containers/*/custom_b*.log
        DB                /var/log/flb_etc.db
        Multiline         On
        Parser_Firstline  multiline
        Skip_Empty_Lines  On
        Skip_Long_Lines   Off
        storage.type      filesystem
        #Path_Key          path
        Refresh_Interval  10
        Ignore_Older      10h

  filter-kubernetes.conf: |
    [FILTER]
        Name    modify
        Match   *
        Rename  log  message

    [FILTER]
        Name          parser
        Match         appexception.*
        Key_Name      path
        Parser        kube_meta
        Reserve_Data  On
        Preserve_key  On

    [FILTER]
        Name    lua
        Match   appexception.*
        script  check_end.lua
        call    check_null_end

  output-s3.conf: |
    [OUTPUT]
        Name                         s3
        Match                        appexception*
        bucket                       {{ .Values.s3.bucket }}
        region                       ap-northeast-2
        s3_key_format                {{ .Values.s3.userlog_path }}
        s3_key_format_tag_delimiters +
        upload_timeout               30m

    [OUTPUT]
        Name                         s3
        Match                        etc*
        bucket                       {{ .Values.s3.bucket }}
        region                       ap-northeast-2
        s3_key_format                {{ .Values.s3.userlog_path }}
        s3_key_format_tag_delimiters +
        upload_timeout               30m

    [OUTPUT]
        Name  kinesis_streams
        Match appexception*
        region ap-northeast-2
        stream {{ .Values.kinesis_streams }}

  parsers.conf: |
    [PARSER]
        Name kube_meta
        Format regex
        Regex ns_(?<namespace>.*?)\+pn_(?<container_name>.*?).{20}$

    [PARSER]
        Name multiline
        Format regex
        Regex /(?<message>^\* \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}([.,]\d{1,6})(.|\n)*)/
        Time_Key  time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        
    [PARSER]
        Name multiline_etc
        Format regex
        Regex /(?<message>^\*(.|\n)*)/
        Time_Key  time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        
    [PARSER]
        Name userlog_parser
        Format regex
        Regex ^* (?<time_local>[0-9-]+ [0-9:,]+) \[(?<thread>.*?)\] (?<level>\S+) (?<marker>.*?)?\|(?<logger>.*?)\: (?<log_message>.*)$

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%LZ
        Time_Keep   On
```

Daemonset
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: "fluent-bit-config"
  name: fluent-bit
  namespace: de
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: amazon/aws-for-fluent-bit:2.23.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 2020
        env:
        - name: node_name
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      serviceAccountName: fluent-bit
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Exists"
        effect: "NoExecute"
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.20 (EKS)
* Server type and version: 
* Operating System and version: EC2
* Filters and plugins:

**Additional context**

I tried to search every related page in google search & fluent slack channel on this issue.
I first try add volumemount `/mnt`, but it's no use.

I checked the directory `/var/log/containers/custom`, and there is a read permisson on folder. (755)
and file in the directory has a read permisson.
and I run fluent-bit pod as a root user. 

Maybe it's related to this option on daemonset? 
https://v1-20.docs.kubernetes.io/docs/tasks/configure-pod-container/security-context/
```
securityContext:
  privileged: true
```

or SELinux? 
Please help...
