### ISSUE TITLE
Tail logging not works

### ISSUE THREAD

**Issue by ahvahsky2008** [fluent/fluent-bit#5502]
Why tail-logging still not works in docker-compose?
```
  fluent-bit:
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit-conf/index_formation.conf:/fluent-bit/etc/fluent-bit.conf
      - C:\Users\Admin\projects\index_formation\logs:/fluent-bit/log
```

```
[INPUT]
    name                  tail
    path                  /fluent-bit/logs/*.log
    Path_Key              filename
    Mem_Buf_Limit         10MB
    Buffer_Chunk_Size     8k
    Buffer_Max_Size       32k
    Refresh_Interval      5

[FILTER]
    name                  multiline
    match                 *
    multiline.key_content log
    multiline.parser      python

[OUTPUT]
    Name  http
    Match *
    Host  host.docker.internal
    Port  8000
    URI   /api/v1/
    header content-type application/json
    format json
	Retry_Limit     			15
	net.connect_timeout			20
	net.keepalive               on
    net.dns.mode                TCP
    net.connect_timeout         5
```
