### ISSUE TITLE
fluent-bit win_service win32_exit_code 1067

### ISSUE THREAD

**Issue by markuman** [fluent/fluent-bit#5519]
## Bug Report

**Describe the bug**

running fluent-bit from powershell works fine with the provided config

```
.\fluent-bit.exe -c ..\conf\fluent-bit.conf  
```

the cloudwatch group is also created automatically as expected. So the requirements for the output filter are also met

But starting via windows service is failing with exit code `WIN32_EXIT_CODE 1067` using fluent-bit 1.9.3

**To Reproduce**

- Steps to reproduce the problem:

deployed via ansible

```yml
---
- hosts: all

  vars:
    fluent_bit_config: |
      [SERVICE]
          flush        5
          daemon       Off
          log_level    info

      [INPUT]
          Name         winevtlog
          Channels     Setup,Windows PowerShell
          Interval_Sec 1
          DB winevtlog.sqlite
          Tag security

      [OUTPUT]
          Name cloudwatch_logs
          Match security
          region eu-central-1
          log_group_name /windows/security.log
          log_stream_name ${HOSTNAME}
          auto_create_group On
          log_retention_days 14

  tasks:
    - name: Get whoami information
      ansible.windows.win_whoami:
      register: me

    - debug:
        var: me.account.account_name

    - name: install fluent-bit
      ansible.windows.win_package:
        path: https://fluentbit.io/releases/1.9/fluent-bit-1.9.3-win64.exe
        arguments:
        - /S
        wait_for_children: yes

    - name: Copy fluent-bit config
      ansible.windows.win_copy:
        content: "{{ fluent_bit_config }}"
        dest: C:\Program Files\fluent-bit\conf\fluent-bit.conf
                                    
    - name: Create a new service
      ansible.windows.win_service:
        name: fluent-bit
        path: C:\Program Files\fluent-bit\bin\fluent-bit.exe -c 'C:\Program Files\fluent-bit\conf\fluent-bit.conf' 
        state: started
        username: .\Administrator
        password: "{{ ansible_password }}"

    - name: Get info for a single service
      ansible.windows.win_service_info:
        name: fluent-bit
      register: service_info
```

**Expected behavior**

**Screenshots**

![Screenshot from 2022-05-31 17-41-35](https://user-images.githubusercontent.com/3920157/171215463-f7d8c229-a8b0-4a32-a626-314eb93b94e6.png)

![Screenshot from 2022-05-31 17-42-13](https://user-images.githubusercontent.com/3920157/171215482-0a3a0a0a-c43b-4176-b9f4-e03112f72b75.png)

**Your Environment**

* Version used: 1.9.3
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: windows server 2019
* Operating System and version:
* Filters and plugins:

**Additional context**

**Comment by patrick-stephens** [comment]
It looks like it is complaining about the AWS credentials, presumably you don't get that when run directly?

**Comment by markuman** [comment]
There are not aws credentials. It's right and just a warning. It took the EC2 IAM Role credentials.

**Comment by markuman** [comment]
> There are not aws credentials. It's right and just a warning. It took the EC2 IAM Role credentials.

This warning I receive also on linux instances. IMO it's fine.

**Comment by patrick-stephens** [comment]
https://github.com/fluent/fluent-bit/issues/5615 seems to have the same error code due to a space in the path.

**Comment by markuman** [comment]
@patrick-stephens the command from the FAQ failed in powershell windows server 2019

```
PS C:\Program Files\fluent-bit> sc.exe create fluent-bit binpath= "\"C:\Program Files\fluent-bit\bin\fluent-bit.exe\" -c \"C:\Program Files\fluent-bit\conf\fluent-bit.conf\""
DESCRIPTION:
        Creates a service entry in the registry and Service Database.
USAGE:
        sc <server> create [service name] [binPath= ] <option1> <option2>...

OPTIONS:
NOTE: The option name includes the equal sign. 
      A space is required between the equal sign and the value.
 type= <own|share|interact|kernel|filesys|rec|userown|usershare>
       (default = own)
 start= <boot|system|auto|demand|disabled|delayed-auto>
       (default = demand)
 error= <normal|severe|critical|ignore>
       (default = normal)
 binPath= <BinaryPathName to the .exe file>
 group= <LoadOrderGroup>
 tag= <yes|no>
 depend= <Dependencies(separated by / (forward slash))>
 obj= <AccountName|ObjectName>
       (default = LocalSystem)
 DisplayName= <display name>
 password= <password>
```

**Comment by markuman** [comment]
Installing it to a none-space directory works for me

```yml
- name: create and start service if not exist
  when: service_info.services | length == 0
  block:
    # some serious windows path issue: https://docs.fluentbit.io/manual/installation/windows#faq-fluent-bit-fails-to-start-up-when-installed-under-c-program-files
    # # - name: Create a new service
    # #   ansible.windows.win_service:
    # #     name: fluent-bit
    # #     path: 'C:\windos\fluent-bit\bin\fluent-bit.exe -c C:\windos\fluent-bit\conf\fluent-bit.conf'
    # #     state: started
    # #     username: .\Administrator
    # #     password: "{{ ansible_password }}"
    - name: create fluent-bit service
      ansible.windows.win_shell: sc.exe create fluent-bit binpath="C:\windos\fluent-bit\bin\fluent-bit.exe -c C:\windos\fluent-bit\conf\fluent-bit.conf"

    - name: start fluent-bit service
      ansible.windows.win_shell: sc.exe start fluent-bit

```

**Comment by patrick-stephens** [comment]
I try to avoid Windows if I can @markuman so I'll leave the FAQ failure with @cosmo0920!
It sounds like this is a duplicate then of #5615 so going to combine the two into this one.

**Comment by cosmo0920** [comment]
> @patrick-stephens the command from the FAQ failed in powershell windows server 2019

For PowerShell (showing `PS>` terminal), you should use the following command:
```powershell
PS> New-Service fluent-bit -BinaryPathName "C:\fluent-bit\bin\fluent-bit.exe -c C:\fluent-bit\conf\fluent-bit.conf" -StartupType Automatic
```
ref: https://docs.fluentbit.io/manual/installation/windows#faq-how-can-i-manage-fluent-bit-service-via-powershell

And `ansible.windows.win_shell` uses powershell by default. If you want to use cmd.exe you must specify `args.executable: cmd` in cmd preferable lines.

**Comment by cosmo0920** [comment]
And I digging into handling for spaces included paths, it is difficult to accept for them. This is because spaces included paths are separately handled as command line arguments. It _is_ expected behavior for spaces containing command line arguments.

**Comment by markuman** [comment]
@cosmo0920 ah ok.  So the `ansible.windows.win_service` module works also for me now

```yml
    - name: Create a new service
      ansible.windows.win_service:
        name: fluent-bit
        path: C:\fluent-bit\bin\fluent-bit.exe -c C:\fluent-bit\conf\fluent-bit.conf
        state: started
```
