### ISSUE TITLE
prometheus_scrape error decoding Prometheus Text format

### ISSUE THREAD

**Issue by fellipecmwbc** [fluent/fluent-bit#5541]
## Bug Report

**Describe the bug**

The prometheus_scraper is unable to parse valid Prometheus entries.  

**To Reproduce**
- Example log message:
```
[2022/06/06 23:42:25] [error] [input:prometheus_scrape:prometheus_scrape.0] error decoding Prometheus Text format
```
- Steps to reproduce the problem:
  1. Deploy something that exposes Prometheus metrics with a fluent-bit sidecar and configs
  2. The scrapping gives the error message above

Sample output from the `/metrics` endpoint:
```text
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 101306368.0
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 25112576.0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1654558876.4
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.38
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 6.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1048576.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="6",patchlevel="3",version="3.6.3"} 1.0
# HELP http_requests_total Total HTTP Requests (count)
# TYPE http_requests_total counter
http_requests_total{endpoint="/metrics",method="GET",status_code="200"} 2.0
http_requests_total{endpoint="/",method="GET",status_code="200"} 1.0
# HELP http_requests_inprogress Number of in progress HTTP requests
# TYPE http_requests_inprogress gauge
http_requests_inprogress 1.0
# HELP http_request_duration_seconds HTTP request latency (seconds)
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_bucket{le="0.005"} 2.0
http_request_duration_seconds_bucket{le="0.01"} 2.0
http_request_duration_seconds_bucket{le="0.025"} 2.0
http_request_duration_seconds_bucket{le="0.05"} 2.0
http_request_duration_seconds_bucket{le="0.075"} 2.0
http_request_duration_seconds_bucket{le="0.1"} 2.0
http_request_duration_seconds_bucket{le="0.25"} 2.0
http_request_duration_seconds_bucket{le="0.5"} 2.0
http_request_duration_seconds_bucket{le="0.75"} 2.0
http_request_duration_seconds_bucket{le="1.0"} 2.0
http_request_duration_seconds_bucket{le="2.5"} 2.0
http_request_duration_seconds_bucket{le="5.0"} 2.0
http_request_duration_seconds_bucket{le="7.5"} 2.0
http_request_duration_seconds_bucket{le="10.0"} 2.0
http_request_duration_seconds_bucket{le="+Inf"} 2.0
http_request_duration_seconds_count 2.0
http_request_duration_seconds_sum 0.0006913102697581053
```

**Expected behavior**
The `http://127.0.0.1:5000/metrics` output parsed by the scraper

**Your Environment**
* Version used: `1.9.4` and `1.9.3`
* Reference "app": https://github.com/philwinder/prometheus-python
* Configuration:
`prometheus-configmap.yaml`
```yaml
apiVersion: v1
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     trace
        Parsers_File  parsers_json.conf

    @INCLUDE input_*.conf
    [FILTER]
        Name modify
        Match *       
        Add environment some_env
    [OUTPUT]
        Name stdout
        Match *
  input_envoy.conf: |
    [INPUT]
        name prometheus_scrape
        host 127.0.0.1
        port 5000
        tag envoy
        metrics_path /metrics
        scrape_interval 30s
    [OUTPUT]
        name stdout
        match *
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/part-of: logger
  name: pltf-fluent-bit-config
```

`deployment.yaml`
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pytest
  name: pytest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pytest
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pytest
    spec:
      containers:
      - image: philwinder/prometheus-python
        name: prometheus-python
        ports:
        - containerPort: 5000
      - args:
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        command:
        - /fluent-bit/bin/fluent-bit
        image: fluent/fluent-bit:1.9.3-debug
        imagePullPolicy: IfNotPresent
        name: logger
        resources:
          limits:
            cpu: 50m
            memory: 200Mi
          requests:
            cpu: 14m
            memory: 80Mi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsUser: 900
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluent-bit/etc/fluent-bit.conf
          name: pltf-fluent-bit-envoy-config
          subPath: input_envoy.conf
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: input_envoy.conf
            path: input_envoy.conf
          name: pltf-fluent-bit-config
        name: pltf-fluent-bit-envoy-config
```

* Environment name and version: Azure Kubernetes Service `v1.22.4`
* Server type and version: Linux
* Operating System and version: N/A
* Filters and plugins: as above

**Additional context**

The main goal is to use Prometheus Scrapper to capture [Consul envoy sidecar metrics](https://www.consul.io/docs/k8s/connect/observability/metrics). We have used the example above as it is simpler and shows the same behavior.
