### ISSUE TITLE
Loki Output - remove_keys skipped if used in labels

### ISSUE THREAD

**Issue by DevSusu** [fluent/fluent-bit#5546]
## Bug Report

**Describe the bug**
Using Loki output, `remove_keys` don't work as expected when values within `remove_keys` are used by `labels`

using `fluent/fluent-bit:1.9.4`

**To Reproduce**

```yaml
# docker-compose.yaml
version: "3.7"

services:
  fluent-bit:
    image: fluent/fluent-bit
    network_mode: "host"
    volumes:
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml
    command: "/fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.yaml"
```

```yaml
# fluent-bit.yaml
env:
  log_level: debug
  flush_interval: 5

pipeline:
  inputs:
  - dummy:
      dummy: '{"log":"blahblah","kubernetes":{"pod_name":"nginx", "namespace_name":"default"}}'

  outputs:
  - loki:
      match: '*'
      auto_kubernetes_labels: off
      labels: pod=$kubernetes['pod_name']
      remove_keys: kubernetes
```

```bash
$ docker-compose up

$ nc -l 3100
POST /loki/api/v1/push HTTP/1.1
Host: 127.0.0.1:3100
Content-Length: 148
User-Agent: Fluent-Bit
Content-Type: application/json

{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\",\"kubernetes\":{\"namespace_name\":\"default\"}}"]]}]}
```

- Steps to reproduce the problem:

**Expected behavior**
```
# expected
{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\"}"]]}]}

# actual
{"streams":[{"stream":{"pod":"nginx"},"values":[["1654686265055834768","{\"log\":\"blahblah\",\"kubernetes\":{\"namespace_name\":\"default\"}}"]]}]}
```

**Your Environment**
* Version used: 1.9.4
* Configuration: given above
* Environment name and version: docker
* Server type and version:
* Operating System and version: ubuntu 20.04
* Filters and plugins: Loki

**Additional context**
using `tail` input and `kubernetes` filter and `loki` output in kubernetes environment, and ran into this problem. There are a lot of useless labels and annotations included in logs. I want only relevant information and remove key `kubernetes`

**Comment by DevSusu** [comment]
adding more context.

when not referencing `kubernetes` from labels, keys are removed as configured

```yaml
# fluent-bit.yaml
env:
  log_level: debug
  flush_interval: 5

pipeline:
  inputs:
  - dummy:
      dummy: '{"log":"blahblah","kubernetes":{"pod_name":"nginx", "namespace_name":"default"}}'

  outputs:
  - loki:
      match: '*'
      auto_kubernetes_labels: off
      remove_keys: kubernetes
```

```bash
$ docker-compose up

$ nc -l 3100
POST /loki/api/v1/push HTTP/1.1
Host: 127.0.0.1:3100
Content-Length: 105
User-Agent: Fluent-Bit
Content-Type: application/json

{"streams":[{"stream":{"job":"fluent-bit"},"values":[["1654685781055956259","{\"log\":\"blahblah\"}"]]}]}
```

please help me out identifying if this is intentional, or a bug
