### ISSUE TITLE
[Feature Request] Logging.parser: none -> /dev/null

### ISSUE THREAD

**Issue by marckamerbeek** [fluent/fluent-bit#555]
Hi Eduardo,

Could you add "none" as possible value to the K8S-Logging.Parser. If the annotation is logging.parser : "none" then all the logging will be flushed to e.a /dev/null. 

Logging intensive applications can be excluded this way. 

I tried to achieve that with the grep Exclude filter, but that doesn't work with nested fields like kubernetes.annotations.logging.parser

Thanks in advance!

**Comment by edsiper** [comment]
Thanks for suggesting this improvement.

The recent change https://github.com/fluent/fluent-bit/commit/cd85e34072e70ada5277b228a6f4e21691aeee17 implement such feature and will be part of 0.13 final release. Configuration example:

__fluent-bit.conf__
```
  [FILTER]
      Name kubernetes
      ...
      K8S-Logging.exclude True
```

__pod.yaml__
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: apache-logs
  labels:
    app: apache-logs
  annotations:
    fluentbit.io/exclude: "true"
spec:
  containers:
  - name: apache-exclude
    image: edsiper/apache_logs
```

Note that the annotation prefix has changed from _logging._ to _fluentbit.io/_.
