### ISSUE TITLE
[ES Output] fluentbit causes many "Connection reset by peer" to elasticsearch

### ISSUE THREAD

**Issue by falau** [fluent/fluent-bit#573]
### Problem
I'm evaluating using fluentbit to replace fluentd as the node-level logging agent, but when I turned on fluentbit to catch logs from Kubernetes such as the API server, lots of `Connection reset by peer` were observed at ES logs:
```
[2018-04-26T08:43:08,396][DEBUG][o.e.h.n.Netty4HttpServerTransport] [es-logging-7bf8854cb-d8rfp] caught exception while handling client http traffic, closing connection [id: 0xb8746a9c, L:/100.99.105.78:9200 - R:/100.99.105.85:40798]
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:?]
...
(long java exception stacks)
...
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.13.Final.jar:4.1.13.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
```
The result from tcpdump also shows that the RESET is sent by fluentbit as well:
```
...
08:43:08.211124 IP 100.99.105.78.9200 > 100.99.105.85.40798: Flags [.], seq 7241:14481, ack 146488, win 631, options [nop,nop,TS val 20442057 ecr 20442008], length 7240
08:43:08.211138 IP 100.99.105.85.40798 > 100.99.105.78.9200: Flags [.], ack 14481, win 114, options [nop,nop,TS val 20442057 ecr 20442057], length 0
08:43:08.211519 IP 100.99.105.85.40798 > 100.99.105.78.9200: Flags [R.], seq 146488, ack 14481, win 114, options [nop,nop,TS val 20442057 ecr 20442057], length 0
```
After some investigation, I found it might cause by the following situation. Hope my understanding is correct. If a response size of the ES `/_bulk` API is larger than the `Buffer_Size` of fluentbit, which is default to 4k bytes, the excess response won't be consumed by fluentbit according to this [code](https://github.com/fluent/fluent-bit/blob/v0.12.18/src/flb_http_client.c#L812-L819) . Afterwards, the [socket fd is closed](https://github.com/fluent/fluent-bit/blob/v0.12.18/plugins/out_es/es.c#L521) with unconsumed values in the socket buffer. As a result, RST is sent from fluentbit rather than FIN to the elasticsearch.

If I increase the `Buffer_Size` in es_output, elasticsearch doesn't cry anymore. But I'd like to know if there is any suggest way to make elasticsearch calm while keeping the fluentbit's memory footprint small.

### Environment
- k8s: 1.9.6
- fluentbit: 0.12.18
- elasticsearch: 5.6.1

### Reproduce
---
fluent-bit
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    app: fluent-bit-logging
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-elasticsearch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name              tail
        Tag               kube.*
        Path              /var/log/containers/test-pod-*.log
        Parser            docker
        DB                /var/log/flb_kube.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  filter-kubernetes.conf: |
    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc:443
        Merge_JSON_Log On

  output-elasticsearch.conf: |
    [OUTPUT]
        Name            es
        Match           *
        Host            ${FLUENT_ELASTICSEARCH_HOST}
        Port            ${FLUENT_ELASTICSEARCH_PORT}
        Logstash_Format On
        Retry_Limit     False
        # Buffer_Size     1M

  parsers.conf: |
    [PARSER]
        Name   json-test
        Format json
        Time_Key time
        Time_Format %d/%b/%Y:%H:%M:%S %z

    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
        Time_Keep   On
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit-logging
  namespace: logging
  labels:
    app: fluent-bit-logging
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: fluent-bit-logging
  template:
    metadata:
      labels:
        app: fluent-bit-logging
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: fluentbit
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:0.12
        env:
        - name: FLUENT_ELASTICSEARCH_HOST
          value: "es-logging-svc"
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        resources:
          requests:
            cpu: 50m
            memory: 60Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc/
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - name: fluent-bit-config
        configMap:
          name: fluent-bit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
rules:
- apiGroups: [""]
  resources:
  - pods
  - namespaces
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluentbit
  namespace: logging
  labels:
    app: fluentbit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluentbit
subjects:
- kind: ServiceAccount
  name: fluentbit
  namespace: logging
```
test pod:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-pod
  template:
    metadata:
      labels:
        app: test-pod
    spec:
      containers:
      - image: alpine
        name: test-pod
        command:
        - /bin/sh
        - -c
        - |
          while :; do
            echo "$(date) : $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)"
            sleep 0.01
          done
        resources:
          requests:
            memory: 30Mi
            cpu: 30m
          limits:
            memory: 30Mi
```
---
ES:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config-file
  namespace: logging
  labels:
    app: es-logging
data:
  log4j2.properties: |-
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n

    rootLogger.level = debug
    rootLogger.appenderRef.console.ref = console
    rootLogger.action = debug

  elasticsearch.yml: |-
    cluster.name: "es-logging"
    network.host: 0.0.0.0

    node.name: ${HOSTNAME}
    node.master: ${IS_MASTER_NODE}
    node.data: ${IS_DATA_NODE}
    node.ingest: ${IS_INGEST_NODE}

    discovery.zen.minimum_master_nodes: ${MINIMUM_MASTER_NODES}

    # bootstrap.memory_lock: true

    # xpack.security.enabled: false
    # xpack.monitoring.enabled: false
    # xpack.ml.enabled: false
    # xpack.graph.enabled: false
    # xpack.watcher.enabled: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-logging
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-logging
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: es-logging
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - image: busybox
        name: adjust-heap
        securityContext:
          privileged: true
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
        name: es-logging
        command:
        - /bin/bash
        - -c
        - |
          cp /config-file/* /usr/share/elasticsearch/config/ ;
          bin/elasticsearch-plugin remove x-pack ;
          bin/es-docker
        env:
        - name: ES_JAVA_OPTS
          value: "-Des.enforce.bootstrap.checks=true -Xms512m -Xmx512m"
        - name: IS_MASTER_NODE
          value: "true"
        - name: IS_DATA_NODE
          value: "true"
        - name: IS_INGEST_NODE
          value: "true"
        - name: MINIMUM_MASTER_NODES
          value: "1"
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        volumeMounts:
        - name: config-file
          mountPath: /config-file
      volumes:
      - name: config-file
        configMap:
          name: es-config-file
---
apiVersion: v1
kind: Service
metadata:
  name: es-logging-svc
  namespace: logging
spec:
  ports:
  - port: 9300
    name: transport
  - port: 9200
    name: http
  selector:
    app: es-logging
```
