### ISSUE TITLE
chunk cannot be retried

### ISSUE THREAD

**Issue by fooflington** [fluent/fluent-bit#5795]
## Bug Report

When using fluent-bit configured to forward events using the `http` plugin in `gelf` mode to a Graylog server behind a reverse https proxy (caddy), if the upstream is unavailable then events are not queued in the `storage.path` despite having `storage.type=filesystem` in the `[INPUT]` section.

```
[2022/07/27 07:52:13] [error] [upstream] connection #55 to upstream:443 timed out after 10 seconds
[2022/07/27 07:52:13] [error] [tls] error: unexpected EOF
[2022/07/27 07:52:13] [error] [output:http:http.0] no upstream connections available to upstream:443
[2022/07/27 07:52:13] [ warn] [engine] chunk '1-1658908305.690681371.flb' cannot be retried: task_id=3, input=forward.0 > output=http.0
```

**Expected behavior**
Chunk should be cached to filesystem ready to be sent later.

**Your Environment**
* Version used: `fluent/fluent-bit:1.9`  (`Fluent Bit v1.9.6`)
* Configuration: below
* Environment name and version (e.g. Kubernetes? What version?): `Docker version 20.10.16, build aa7e414fdcb23a66e8fabbef0a560ef1769eace5` under Alpine Linux v3.16
* Server type and version: Raspberry Pi (armv7l)
* Operating System and version: Alpine Linux v3.16
* Filters and plugins: none other than provided by docker image

**docker-compose.yml**
```yaml
version: '3'
services:
  fluent_node:
    image: fluent/fluent-bit:1.9
    volumes:
      - fluent_cache:/cache
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /var/run/fluent-bit:/run
    environment:
      HOSTNAME: "myhostname"

volumes:
  fluent_cache:
```

**fluent-bit.conf**
```
[SERVICE]
    flush        1
    daemon       Off
    log_level    info
    parsers_file parsers.conf
    plugins_file plugins.conf
    http_server  Off
    storage.path /cache

[INPUT]
    Name forward
    Unix_path /run/incoming.socket
    storage.type  filesystem

[FILTER]
    Name record_modifier
    Match *
    Record host ${HOSTNAME}

[OUTPUT]
    Name http
    Match *
    Host upstream
    Port 443
    Uri /gelf
    Format gelf
    http_user <removed>
    http_passwd <removed>
    tls on
    gelf_short_message_key log
    gelf_host_key host
    log_response_payload false
```
