### ISSUE TITLE
Add override_timestamp to prometheus scrape metrics input plugin

### ISSUE THREAD

**Issue by benjaminhuo** [fluent/fluent-bit#5984]
**Is your feature request related to a problem? Please describe.**

When using fluentbit [prometheus scrape metrics](https://docs.fluentbit.io/manual/pipeline/inputs/prometheus-scrape-metrics) to scrape container metrics on KubeEdge Edge node like below:

https://github.com/fluent/fluent-operator/blob/master/manifests/kubeedge/input-prometheus-scrape-metrics-edge.yaml
```yaml
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: prometheus-scrape-metrics-edge
  labels:
    fluentbit.fluent.io/enabled: "true"
    node-role.kubernetes.io/edge: "true"
spec:
  prometheusScrapeMetrics:
    tag: kubeedge.*
    host: 127.0.0.1
    port: 10350
    scrapeInterval: 30s
    metricsPath : /metrics/cadvisor
```

Some sample's timestamp is not the latest timestamp(for example, 20 minutes or earlier) which causes the [prometheus remote write](https://github.com/fluent/fluent-operator/blob/master/manifests/kubeedge/output-prometheus-remote-write-edge.yaml) fails with an error like below (The error is from the Prometheus server side):
<img width="418" alt="image" src="https://user-images.githubusercontent.com/18525465/188096465-f2a9efff-4512-4c33-a169-bebcf6e7d8b5.png">

**Describe the solution you'd like**

Add a field like `override_timestamp true` to the [prometheus scrape metrics](https://docs.fluentbit.io/manual/pipeline/inputs/prometheus-scrape-metrics), replace Prometheus metrics' timestamp with the current time for each sample scraped before send it to Prometheus remote write output plugin if `override_timestamp` is set to true. The default value should be false

**Describe alternatives you've considered**

**Additional context**
