### ISSUE TITLE
[2.0.0] length of environment variable keys are limited more restrictiv

### ISSUE THREAD

**Issue by a-thaler** [fluent/fluent-bit#6313]
## Bug Report

**Describe the bug**

With the upgrade to fluentbit 2.0.0 it seems that the variables templating is not working anymore with keys which are longer then a certain amount.

**To Reproduce**

- Use the official helm chart here: https://github.com/fluent/helm-charts/tree/main/charts/fluent-bit
- Create a values.yaml file like that:
   ```yaml
  image:
  tag: 2.0.3

  config:
    outputs: |
      [OUTPUT]
          Name http
          Match kube.*
          Host ${ABC_APPLICATION_TEST_TEST_ABC_FLUENT_BIT_SECRET_FLUENTD_HTTP_HOST}
          Retry_Limit True
  
  env:
    - name: ABC_APPLICATION_TEST_TEST_ABC_FLUENT_BIT_SECRET_FLUENTD_HTTP_HOST
      value: "dummy.com"
   ```
- Install it with the values.yaml like
  ```bash
  helm install fluent-bit fluent/fluent-bit -f values.yaml
  ```
- Then check the logs of fluentbit, you will find something like:
   ```bash
   [2022/10/31 09:54:36] [ warn] [net] getaddrinfo(host='${ABC_APPLICATION_TEST_TEST_ABC_FLUENT_BIT_SECRET_FLUENTD_HTTP_HOST}', err=8): Misformatted domain name
   [2022/10/31 09:54:36] [error] [output:http:http.0] no upstream connections available to ${ABC_APPLICATION_TEST_TEST_ABC_FLUENT_BIT_SECRET_FLUENTD_HTTP_HOST}:80
   ```

Changing the image tag in the values.yaml to "1.9.9" will fix the problem. You can see in the logs that the configured URL gets resolved and called.
Also a shorter key will fix the problem, like: `ABC_APP_TEST_ABC_FLUENT_BIT_SECRET_FLUENTD_HTTP_HOST`

**Expected behavior**
I expect to get a behavior with 2.0 as before with 1.9.9 or alternatively to have a statement in the release notes. I'm not asking to get it fixed necessarily, a statement with the new limit will be acceptable as well.

**Your Environment**
GKE kubernetes cluster with k8s 1.24

**Additional context**
I have some automation in place which generates some placeholder and the related environment variables. Here, the used keys are constructed out of several elements and might be quite long.
