### ISSUE TITLE
Fluentbit on Docker Failes to Find Parser

### ISSUE THREAD

**Issue by almasria** [fluent/fluent-bit#6397]
## Bug Report

**Describe the bug**

I have Docker compose for Fluentbit, OpenSearch and PostgresSQL. I am planning to collect the logs from PostgreSQL container using Docker Logging driver, parse them using Fluentbit regex parser and ingest them in OpenSearch, I am running Docker on Windows 11 machine. My setup works well without parser, but the moment I configure the parser it stops working! 

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
`[2022/11/13 22:05:30] [error] [filter:parser:parser.0] requested parser 'postgres' not found`
`[2022/11/13 22:05:30] [error] [filter:parser:parser.0] Invalid 'parser'`
`[2022/11/13 22:05:30] [error] Failed initialize filter parser.0`
`[2022/11/13 22:05:30] [error] [lib] backend failed`

```
{"log":"YOUR LOG MESSAGE HERE","stream":"stdout","time":"2018-06-11T14:37:30.681701731Z"}
```
- Steps to reproduce the problem:
Config file:

      [SERVICE]
          Log_Level debug
          Parsers_File parsers.conf
      
      [INPUT]
          Name              forward
          Listen            0.0.0.0
          Port              24224
      
      [FILTER]
          Name parser
          Match *
          Key_Name log
          Parser postgres
      
      [OUTPUT]
          Name opensearch
          Match *
          Host opensearch-node1
          Port 9200
          HTTP_User password
          HTTP_Passwd password
          Suppress_Type_Name On
          Logstash_Format On

Parsers file:

      [PARSER]
          Name postgres
          Format regex         
          Regex (?<time>[\d\-\:\. ]+) [^ ]* \[(?<process>[\d]*)\] (?<db>[^ ]*) (?<ip>[\d\.]*)(\()(?<port>[\d]*)(\)) (\[)?(?<application>[\w ]*)(\])? (postgres)(?<severity>[^ ]*) (?<description>[\s\S]*)?$
          Time_Key    time
          Time_Format %d/%b/%Y:%H:%M:%S %z

**Expected behavior**

Parse Postgres logs and ingest them in OpenSearch

**Screenshots**

**Your Environment**

* Version used: Fluent Bit v1.9.9
* Configuration: Docker container and Fluented log driver
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Docker on Windows 11
* Filters and plugins: Forwarder and Parser

**Additional context**

**Comment by patrick-stephens** [comment]
Are you sure you've mounted the file in the right location?
Can you use an absolute path to the parsers file to see if that works?

Run with `debug` and attach the full logs.

**Comment by patrick-stephens** [comment]
I have no idea, where are you mounting your parsers - that is entirely controlled by your docker compose definition. Please provide the full compose stack and use an absolute path that matches wherever you have mounted them.

**Comment by almasria** [comment]
Here is the current compose stack, I am just interested in collecting the logs from the postgres container. 

```


version: '3'
services:
  opensearch-node1:    
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" 
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144 
        hard: 262144
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 
    networks:
      - opensearch-net
  opensearch-node2:    
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - opensearch-net
  opensearch-dashboards:
    image: opensearch-dashboards-no-security
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-node1:9200","http://opensearch-node2:9200"]'
    networks:
      - opensearch-net
  postgres:
    container_name: postgres     
    image: postgres:13.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db # DB for testing
    ports:
      - 5432:5432
    volumes: 
      - postgres:/var/lib/postgresql/data      
      - ./postgres.conf:/etc/postgresql/postgresql.conf 
    command: postgres -c config_file=/etc/postgresql/postgresql.conf 
    networks:
      - opensearch-net
    depends_on:
      - fluent-bit    
    logging:
      driver: fluentd 
      options:
        tag: postgres
        fluentd-address: localhost:24224 
        fluentd-async-connect: "true"
        fluentd-retry-wait: 1s
        fluentd-max-retries: 30
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on: 
      - postgres
    networks:
      - opensearch-net
  fluent-bit:
    image: fluent/fluent-bit:1.9.9
    container_name: fluent-bit
    ports:
      - "24224:24224" 
      - "24224:24224/udp" 
    volumes:
      - type: bind
        source: /c/temp/docker/fluentbit.conf
        target: /fluent-bit/etc/fluent-bit.conf
    networks:
      - opensearch-net
    depends_on:
      - opensearch-node1

volumes:
  opensearch-data1:
  opensearch-data2:
  postgres:
    

networks:
  opensearch-net:


```

**Comment by patrick-stephens** [comment]
The only file you mount is the config file, nothing else here:
```
    volumes:
      - type: bind
        source: /c/temp/docker/fluentbit.conf
        target: /fluent-bit/etc/fluent-bit.conf
```
You should mount the directory if that's what you want.
