### ISSUE TITLE
YAML documentation for inputs out of date

### ISSUE THREAD

**Issue by braunsonm** [fluent/fluent-bit#6408]
## Bug Report

**Describe the bug**
Previously, the following YAML config would work:

```yaml
service:
    flush: 5
    daemon: off
    log_level: debug

pipeline:
    inputs:
        - cpu:
            tag: my_cpu
    outputs:
        - stdout:
            match: my*cpu
```

Now it returns an error:
```
section 'input' is missing the 'name' property
```

**To Reproduce**
- Run with the above configuration

**Expected behavior**
Fluent should work as it did with 1.9.x

**Comment by braunsonm** [comment]
The above configuration is taken from the documentation as well: https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file#example-collecting-cpu-metrics

**Comment by braunsonm** [comment]
It seems like either intentionally or not, the format of this configuration has changed and not been documented. This works:

```yaml
service:
    flush: 5
    daemon: off
    log_level: debug

pipeline:
    inputs:
        - name: cpu 
          cpu:
            tag: my_cpu
    outputs:
        - name: stdout
          stdout:
            match: my*cpu
```
