### ISSUE TITLE
oracle s3  get error Could not find ETag in UploadPart response

### ISSUE THREAD

**Issue by laileman** [fluent/fluent-bit#6538]
## Bug Report

**Describe the bug**
I use s3 output to push logs to oracle s3, get error: 
`Could not find ETag in UploadPart response`

**To Reproduce**
docker-compose:
```
version: "3"
services:
  fluent-bit:
    image: fluent/fluent-bit:latest-debug
    volumes:
    - /docker-compose/fluent-bit/config:/root/.aws/config
    - /docker-compose/fluent-bit/credentials:/root/.aws/credentials
    - /docker-compose/fluent-bit/cdn-cache:/root/cdn-cache
    - /docker-compose/fluent-bit/fluent-bit.conf:/etc/fluent-bit.conf
    command: "/fluent-bit/bin/fluent-bit -c /etc/fluent-bit.conf"
```
.aws/config
```
[profile default]
region = us-ashburn-1
output = json
```
.aws/credentials
```
[default]
aws_access_key_id = xxxx
aws_secret_access_key = xxxx
```
fluent-bit.conf
```
[Service]
    Daemon    false
    Flush    5
    Http_Listen    0.0.0.0
    Http_Port    2020
    Http_Server    true
    Log_Level    info
    Parsers_File    parsers.conf
[Input]
    Name    tail
    Alias    tail
    Path    /root/cdn-cache/*.json
    Refresh_Interval    5
    Skip_Long_Lines    true
    Tag    tail

[Output]
    Name    s3
    Match    tail
    Alias    s3
    region    us-ashburn-1
    bucket    xxxxxx
    json_date_key    @timestamp
    total_file_size    20M
    upload_chunk_size    9M
    upload_timeout    5m
    endpoint https://idbouya3cw7e.compat.objectstorage.us-ashburn-1.oraclecloud.com
    s3_key_format    /test/date=%Y%m%d/hour=%H/cdn-cache.%Y-%m-%dT%H.%M-$UUID.json
    s3_key_format_tag_delimiters    _.
    static_file_path    true
    preserve_data_ordering    false
    tls    On
    tls.verify    false
```
env:
```
fluent-bit version: 2.0.6
os:  macos 1.13.1
```
logs :
[logs.txt](https://github.com/fluent/fluent-bit/files/10214866/logs.txt)
