### ISSUE TITLE
[error] [input:tail:tail.0] read error - Custom log path returns read permission issue even when the folder and the files within have read permissions.

### ISSUE THREAD

**Issue by berry2012** [fluent/fluent-bit#7085]
Custom log path returns read permission issue even when the folder and the files within have read permissions.
I reproduced the same errors. 

```
[root@ip-192-168-106-82 ~]# ls -l /opt/service_logs/customlogging
total 512
-rwxrwxrwx 1 root root 154347 Mar 28 17:56 1.log
-rwxrwxrwx 1 root root 172215 Mar 28 17:56 2.log
```

Fluent-bit configMap has two folders and one is a custom path.
```
data:
  application-log.conf: |
    [INPUT]
        Name                tail
        Tag                 application.*
        Exclude_Path        /var/log/containers/cloudwatch-agent*, /var/log/containers/fluent-bit*, /var/log/containers/aws-node*, /var/log/containers/kube-proxy*
        Path                /var/log/containers/*.log, /opt/service_logs/customlogging/*.log
```

Restarted the fluent-bit pods. 

```
[2023/03/28 16:28:54] [error] [input:tail:tail.0] read error, check permissions: /opt/service_logs/customlogging/*.log
[2023/03/28 16:28:54] [ warn] [input:tail:tail.0] error scanning path: /opt/service_logs/customlogging/*.log
[2023/03/28 16:28:54] [error] [input:tail:tail.0] read error, check permissions: /opt/service_logs/customlogging/*.log
[2023/03/28 16:28:54] [ warn] [input:tail:tail.0] error scanning path: /opt/service_logs/customlogging/*.log
```

Also created Symbolic links to the default log path but still faced the error.
```
ls -l /var/log/containers
lrwxrwxrwx 1 root root  37 Mar 28 17:38 customlogging-1.log -> /opt/service_logs/customlogging/1.log
lrwxrwxrwx 1 root root  37 Mar 28 17:39 customlogging-2.log -> /opt/service_logs/customlogging/2.log
```

_Originally posted by @berry2012 in https://github.com/fluent/fluent-bit/issues/5501#issuecomment-1488137656_

**Comment by patrick-stephens** [comment]
Can you confirm it is still an issue on 2.0.10?
The original issue was for 1.8 which has not been supported for a while.

**Comment by berry2012** [comment]
Yes, still happening. Tested in the ffg:
- 2.0.9
- 1.9.10


To be sure it is not the case of folders not existing before fluent bit pods can scan the folders, I created the folder in all the nodes and also confirmed they exist on each node.
```
for pod in $(kg po | grep create | awk '{print $1}'); do k logs $pod; echo '-------'; done
ip-192-168-117-246.eu-west-1.compute.internal
total 8
drwxrwxrwx 2 root root    6 Apr  2 06:02 customlogging
-------
ip-192-168-156-77.eu-west-1.compute.internal
total 28
drwxrwxrwx 2 root root     6 Apr  2 06:02 customlogging
-------
ip-192-168-187-54.eu-west-1.compute.internal
total 0
drwxrwxrwx 2 root root 6 Apr  2 06:02 customlogging
-------
ip-192-168-128-198.eu-west-1.compute.internal
total 0
drwxrwxrwx 2 root root 6 Apr  2 06:02 customlogging
-------

```

Fluentbit pod
```
kg po fluent-bit-97pg8 -n amazon-cloudwatch -o yaml | grep securityContext -A4
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      tolerations:
```

Pods that created the custom folder
```
kg daemonset customfolder  -o yaml | grep securityContext -A4 
--
        securityContext:
          privileged: true
        stdin: true
        stdinOnce: true
        terminationMessagePath: /dev/termination-log
```

Pod writing to custom location on the host
```
kg pod customlogging -o yaml | grep securityContext -A4
--
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
```

Modified the permission of Fluentbit pod but still no difference
```
kg po fluent-bit-5z6pc -n amazon-cloudwatch -o yaml | grep securityContext -A4
--
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
--
  securityContext: {}
  serviceAccount: fluent-bit
  serviceAccountName: fluent-bit
  terminationGracePeriodSeconds: 10
  tolerations:
```
