### ISSUE TITLE
YAML configuration file requires invalid YAML format

### ISSUE THREAD

**Issue by ps-aux** [fluent/fluent-bit#7290]
**Version**: 2.1.2

**Is your feature request related to a problem? Please describe.**
When configuring filters which can have multiple values for one key in YAML config file, the only format which seems to work is

![image](https://user-images.githubusercontent.com/4789301/235300467-31a91e18-30d1-4cd8-8b01-6379159384ba.png)

This go against [YAML spec](https://yaml.org/spec/1.2.2/). Where the keys should be unique:
![image](https://user-images.githubusercontent.com/4789301/235300559-0d3b2b23-a8ee-46ad-bd49-d77401e93f87.png)

**Describe the solution you'd like**
Supporting list (sequence node) as a way how to add multiple values for the same key. E.g:

![image](https://user-images.githubusercontent.com/4789301/235300619-1366ee2b-e74b-4683-bca6-e09f26625c78.png)

**Describe alternatives you've considered**
Supporting encoding of the list into a single string with a separator. E.g:

![image](https://user-images.githubusercontent.com/4789301/235300661-d46d04ce-406d-4f29-a38f-0b5ac7a00d18.png)

**Comment by pwhelan** [comment]
I believe this PR of mine addresses that issue: https://github.com/fluent/fluent-bit/pull/6133. It seems to already have been merged.

**Comment by stevehipwell** [comment]
I'd also like to see the YAML config be idiomatic so it should use `true` or `false` for boolean values and the keys should be normalised to camel case.

```
[SERVICE]
    # This is a commented line
    Daemon    off
    log_level debug
```
```yaml
service:
  daemon: false
  logLevel: debug
```

**Comment by iolate** [comment]
**Version**: 2.1.4 (I also tested on 2.1.0)

still not working :(

---
```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key: hostname
      allowlist_key: Mem.total
      allowlist_key: Mem.used
      allowlist_key: Mem.free
```
→ working

---
```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key:
        - hostname
        - Mem.total
        - Mem.used
        - Mem.free
```
```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key: Mem.total Mem.used Mem.free
```
→ not working (all keys are visible)

---
```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key:
        - Mem.total
        - Mem.used
        - Mem.free
```
→ error,
`[config] YAML error found in file ...: unexpected event 'sequence-end-event' (8) in state 23.`

**Comment by pwhelan** [comment]
This example will never ever work in YAML:

```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key: hostname
      allowlist_key: Mem.total
      allowlist_key: Mem.used
      allowlist_key: Mem.free
```

Maps in YAML cannot have duplicate keys.

```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key: Mem.total Mem.used Mem.free
```

That one would require `allowlist_key` would need to be rewritten as:

```yaml
allowlist_key: [Mem.total, Mem.used, Mem.free]
```

The documentation could use an example of that syntax though, for clarity.

The last one seems to be a bug caused some how when there are odd numbers of values in the list. I will have to look into it.

**Comment by iolate** [comment]
you're right, odd numbers cause a bug!

however, the first one (duplicate keys) only works even it cannot have duplicates.. :(

---
this example is still not working. all other keys are still visible in output:
```yaml
  filters:
    - name: record_modifier
      match: '*.system.mem'
      allowlist_key: [Mem.total, Mem.used, Mem.free, dummy]
```

**Comment by pwhelan** [comment]
This example with inline lists works for me:

```yaml
---
pipeline:
  inputs:
    - name: dummy
      dummy: '{"MESSAGE": "FOOBAR", "ID": "#FOO", "_HOSTNAME": "HYDRA"}'
  filters:
    - name: record_modifier
      match: '*'
      allowlist_key: [MESSAGE, _HOSTNAME]
  outputs:
    - name: stdout
      format: json_lines
```

I have an open PR to fix the problem with lists of properties with an odd number of values here: #7563.

```bash
./bin/fluent-bit -c even-inline.yaml
Fluent Bit v2.1.5
* Copyright (C) 2015-2022 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

[2023/06/14 11:15:26] [ info] [fluent bit] version=2.1.5, commit=cbdb8df34b, pid=90163
[2023/06/14 11:15:26] [ info] [storage] ver=1.1.6, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2023/06/14 11:15:26] [ info] [cmetrics] version=0.6.1
[2023/06/14 11:15:26] [ info] [ctraces ] version=0.3.1
[2023/06/14 11:15:26] [ info] [input:dummy:dummy.0] initializing
[2023/06/14 11:15:26] [ info] [input:dummy:dummy.0] storage_strategy='memory' (memory only)
[2023/06/14 11:15:26] [ info] [sp] stream processor started
[2023/06/14 11:15:26] [ info] [output:stdout:stdout.0] worker #0 started
{"date":1686755727.2701,"MESSAGE":"FOOBAR","_HOSTNAME":"HYDRA"}
{"date":1686755728.271157,"MESSAGE":"FOOBAR","_HOSTNAME":"HYDRA"}
{"date":1686755729.275214,"MESSAGE":"FOOBAR","_HOSTNAME":"HYDRA"}
^C[2023/06/14 11:15:30] [engine] caught signal (SIGINT)
[2023/06/14 11:15:30] [ info] [input] pausing dummy.0
[2023/06/14 11:15:30] [ info] [output:stdout:stdout.0] thread worker #0 stopping...
[2023/06/14 11:15:30] [ info] [output:stdout:stdout.0] thread worker #0 stopped
```
