### ISSUE TITLE
Fluent-bit deadlock issue (forward input, loki output)

### ISSUE THREAD

**Issue by anosulchik** [fluent/fluent-bit#7329]
## Bug Report

**Describe the bug**
We're observing an issue with fluent-bit that in our setup acts as aggregator - it's configured with `forward input` accepting logs from other fluent-bit and with `loki output` to ingest logs into Loki. In our pre production load tests we emulate Loki outage when fluent-bit legitimately accumulates chunks as a backlog on a filesystem and retries flushing them into Loki based on our retry backoff settings (see below).

But after accumulating certain amount of unflushed chunks we observe that fluent-bit stops accepting traffic to forward input, and client fluent-bits start seeing timeouts, in other words aggregator fluent-bit gets stuck in some deadlock since it doesn't retry to flush chunks anymore but shows infinite `re-schedule retry` in the logs that you can see below:

```
[2023/05/01 20:05:09] [error] [output:loki:loki.0] loki-gateway.<redacted>.net:443, HTTP status=503
[2023/05/01 20:05:09] [error] [output:loki:loki.0] loki-gateway.<redacted>.net:443, HTTP status=503
...
<forward input gets stuck here>
...
[2023/05/01 20:06:28] [ info] [task] re-schedule retry=0x7f87987724f8 227 in the next 12 seconds
[2023/05/01 20:06:29] [ info] [task] re-schedule retry=0x7f87977e6b50 110 in the next 14 seconds
[2023/05/01 20:06:32] [ info] [task] re-schedule retry=0x7f879824c6d8 219 in the next 13 seconds
[2023/05/01 20:06:32] [ info] [task] re-schedule retry=0x7f8797a12e78 156 in the next 16 seconds
[2023/05/01 20:06:32] [ info] [task] re-schedule retry=0x7f879842d868 190 in the next 14 seconds
[2023/05/01 20:06:32] [ info] [task] re-schedule retry=0x7f87991f05e8 153 in the next 11 seconds
[2023/05/01 20:06:33] [ info] [task] re-schedule retry=0x7f87975167a0 155 in the next 20 seconds
[2023/05/01 20:06:36] [ info] [task] re-schedule retry=0x7f879755fdd0 252 in the next 18 seconds
[2023/05/01 20:06:41] [ info] [task] re-schedule retry=0x7f87987724f8 227 in the next 20 seconds
[2023/05/01 20:06:41] [ info] [task] re-schedule retry=0x7f8798a0d530 204 in the next 15 seconds
[2023/05/01 20:06:41] [ info] [task] re-schedule retry=0x7f87983c1548 144 in the next 13 seconds
[2023/05/01 20:06:44] [ info] [task] re-schedule retry=0x7f8795e2f260 162 in the next 12 seconds
[2023/05/01 20:06:44] [ info] [task] re-schedule retry=0x7f87977e6b50 110 in the next 15 seconds
[2023/05/01 20:06:44] [ info] [task] re-schedule retry=0x7f87991f05e8 153 in the next 17 seconds
[2023/05/01 20:06:45] [ info] [task] re-schedule retry=0x7f879824c6d8 219 in the next 19 seconds
[2023/05/01 20:06:46] [ info] [task] re-schedule retry=0x7f879842d868 190 in the next 19 seconds
[2023/05/01 20:06:46] [ info] [task] re-schedule retry=0x7f87976143f0 175 in the next 18 seconds
[2023/05/01 20:06:48] [ info] [task] re-schedule retry=0x7f8797a12e78 156 in the next 14 seconds
```

At the same time, fluent-bit successfully responds to rest API requests like `/api/v1/health` or `/api/v1/metrics`. We can resolve this issue by restart of fluent-bit process.

**To Reproduce**
We're seeing this problem when sending logs at the rate of 30MB/s, it doesn't seem to be related to any specific kind of logs. It does look like a problem backoff with retries when fluent-bit is busy with running retries so it can't accept incoming traffic via forward plugin.

**Expected behavior**
Fluent-bit should continue retrying to flush chunks and accumulate logs in its backlog until there're resources (e.g. disk space or available memory) allows.

**Your Environment**
* Version used: 2.1.2
* Configuration:

```
 [SERVICE]
        Daemon Off
        Flush 5
        Grace -1
        Log_Level info
        Parsers_File parsers.conf
        Parsers_File custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check Off
        storage.path /var/lib/fluent-bit
        storage.sync full
        storage.checksum off
        storage.metrics true
        storage.max_chunks_up 2048
        storage.backlog.mem_limit 256M
        storage.checksum on
        scheduler.base 45
        scheduler.cap 1440

    [INPUT]
        Name forward
        Listen 0.0.0.0
        Port 2021
        storage.type filesystem

    [INPUT]
        Name fluentbit_metrics
        Tag internal_metrics
        storage.type filesystem

    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [OUTPUT]
        name loki
        match *
        host loki-gateway.<redacted>.net
        port 443
        tls on
        tls.verify on
        label_map_path /fluent-bit/etc/map.json
        auto_kubernetes_labels on
        net.connect_timeout 60
        net.connect_timeout_log_error true
        retry_limit false
        workers 5

    [OUTPUT]
        Name prometheus_exporter
        Match internal_metrics
        Port 2022
```

* Environment name and version (e.g. Kubernetes? What version?): EKS 1.25
* Server type and version: `c6i.xlarge` x64
* Operating System and version: Ubuntu Focal
* Filters and plugins: 

```
    [PARSER]
        Name docker_no_time
        Format json
        Time_Keep Off
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S.%L
```

**Additional context**
Our setup implies that aggregator fluent-bit should accumulate unflushed chunks and increase timeout between every retry but never discard chunk until they get flushed into Loki. We believe that fluent-bit input plugin should remain active at a time chunks cannot be flushed so that any issues with output(s) should not affect input's availability.

**Comment by stevehipwell** [comment]
CC @patrick-stephens

**Comment by patrick-stephens** [comment]
Not sure what I can add here, although I note you're not enabling the healthcheck functionality which may detect this issue: `        Health_Check On`

**Comment by stevehipwell** [comment]
@patrick-stephens I thought you might be interested as this is related to using Fluent Bit as an aggregator and nobody has triaged it yet. We plan on starting to test this functionality out and I was looking through relevant issue before we do so.

**Comment by patrick-stephens** [comment]
I think @tarruda was looking at some improvements to healthcheck so he may have some insights.

**Comment by anosulchik** [comment]
Go away you stale bot!

**Comment by carlosrmendes** [comment]
I'm having the same issue, in my case, a fluent bit with tail plugin outputting through tcp to a logstash server. Simulating an outage on logstash, after some time the fluentbit simply stop (also error and retry logging stop), even after the logstash come up, the fluentbit does not flush the chunks saved in the filesystem buffer.

This is my config:
```yaml
service:
  flush: 5
  http_server: on
  log_level: warn
  storage.sync: full
  storage.path: /data/buffer/

pipeline:
  inputs:
    - name: tail
      refresh_interval: 5
      buffer_max_size: 256k
      db: /data/logs.db
      storage.type: filesystem
      multiline.parser: docker, cri
      tag: <namespace>.<workload>.<container>
      tag_regex: (?<workload>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container>.+)-([a-z0-9]{64})\.log$
      path: /var/log/containers/*_kelvin-admin_*.log,/var/log/containers/*_kelvin_*.log,/var/log/containers/*_app_*.log

  filters:
    - name: record_modifier
      match: "*"
      remove_key: _p

    - name: record_modifier
      match: "*"
      remove_key: stream

    - name: modify
      match: "*"
      add: cluster ${CLUSTER_NAME}

    - name: modify
      match: "*"
      add: node ${KUBERNETES_NODE_NAME}

    - name: lua
      match: "*"
      call: tag_fields
      code: |
        function tag_fields(tag, timestamp, record)
          tags = {}

          for t in string.gmatch(tag, "[^%.]+") do
            table.insert(tags, t)
          end

          record["namespace"] = tags[1]
          record["pod"] = tags[2]

          if record["namespace"] == "app" then
            record["workload"] = string.gsub(tags[2], "-0$", "")
          end

          record["container"] = tags[3]

          return 1, timestamp, record
        end

    - name: lua
      match: "*"
      call: log_fields
      code: |
        function log_fields(tag, timestamp, record)
          cjson = require("cjson")

          log = record["log"]
          status, parsed_log = pcall(cjson.decode, log)

          if status and type(parsed_log) == "table" then
            if parsed_log["level"] then
              record["level"] = string.lower(parsed_log["level"])
            end
            if parsed_log["logger"] then
              record["logger"] = parsed_log["logger"]
            end
          end

          return 1, timestamp, record
        end

  outputs:
    - name: http
      match: "*"
      host: logstash-001
      port: 443
      tls: on
      tls.verify: off
      compress: gzip
      format: json_lines
      retry_limit: no_limits
      log_response_payload: false
      storage.total_limit_size: 5G
```
