### ISSUE TITLE
S3 storage.total_limit_size necessary to bound memory and FS

### ISSUE THREAD

**Issue by msolters** [fluent/fluent-bit#7390]
## Bug Report
Currently, the S3 Output plugin emits the following warning if you include the parameter `storage.total_limit_size`:
```
[ warn] [output:s3:s3] Please use 'store_dir_limit_size' with s3 output instead of 'storage.total_limit_size'. S3 has its own buffer files located in the store_dir.
```

For our config, we define both parameters, and set them equal to the same value.  However, we have found that if the `storage.total_limit_size` is actually _removed_, and not explicitly defined, then Fluent Bit's RAM and Filesystem util will stop being bounded.  For example, with `store_dir_limit_size  600M`, removing `storage.total_limit_size  600M` causes the following FS buffer usage:

![image](https://github.com/fluent/fluent-bit/assets/4452380/c4d5a0c3-926d-48b6-9d9c-df2b5d4cdb4f)

If `storage.total_limit_size  600M` is included along with `store_dir_limit_size`, then the FS usage gets clamped at 600M as expected, but the output begins firing the warning telling us to remove the parameter.

**Expected behavior**
If the warning indicates the property should be removed, removing it should be safe and not change resource utilization, especially in so dramatic a fashion.  

**Your Environment**
* Version used: v2.1.2 
* Environment name and version (e.g. Kubernetes? What version?): EKS - Kubernetes filter not being used, we are not ingesting containerlogs
* Filters and plugins: tail input -> lua filter -> s3 output

**Comment by PettitWesley** [comment]
What is your full config? Do you have filesystem storage enabled? Do you have other outputs?

As explained here, S3 basically has its own EXTRA layer of filesytem buffering: https://docs.fluentbit.io/manual/pipeline/outputs/s3#differences-between-s3-and-other-fluent-bit-outputs

**Comment by msolters** [comment]
We are using filesystem storage for all inputs.  The only outputs in this system are a single Kafka output and a single S3 output.  The S3 config is as follows:

```
      outputs:
        - alias: s3
          name: s3
          match: kube-logs-for-s3,*
          bucket: ${S3_LOG_BUCKET}
          log_key: message
          region: ${REGION}
          retry_limit: 5
          s3_key_format: /$TAG[1]/$TAG[2]/$TAG[3]/%Y/%m/%d/$TAG[4]/$TAG[5]/${LOG_VOLUME_NAME}/$TAG[6].$UUID
          s3_key_format_tag_delimiters: ","
          store_dir: /flb-storage/s3
          total_file_size: 10M
          upload_timeout: 600s
          storage.total_limit_size: 600M
          store_dir_limit_size: 600M
```

I am aware that this output simply acks incoming chunks and then handles buffering with its own subsystem.  Nevertheless, when I remove `storage.total_limit_size`, the memory and filesystem usage exceeds `store_dir_limit_size`.  It seems only to respect the boundary when `storage.total_limit_size` is likewise defined.
