### ISSUE TITLE
Filters in Input Processors do not Emit Metrics

### ISSUE THREAD

**Issue by msolters** [fluent/fluent-bit#7391]
## Bug Report

**Describe the bug**
When we move filters inside the `processors.logs` of a specific input, the `api/v1/metrics/prometheus` stops emitting metrics for those filters.  For example:

```
    pipeline:
      inputs:
        - name: tail
          alias: foo
          path: $the_paths
          db: /var/log/fluent-bit-s3.db
          db.sync: normal
          db.locking: true
          db.journal_mode: WAL
          key: message
          tag: foo.*
          buffer_chunk_size: 2MB
          buffer_max_size: 5MB
          mem_buf_limit: 50MB
          path_key: log_file_path
          skip_long_lines: On
          offset_key: offset
          storage.type: filesystem
          threaded: on
          processors:
            logs:
              - alias: lua-s3
                name: lua
                match: foo.*
                script: custom_filters.lua
                call: foo_rewrite_for_s3
```

In this configuration we see no filter metrics for the `lua-s3` filter.

**Expected behavior**
Filters should emit metrics whether or not they are in an input's thread-specific processor stack or not.

**Screenshots**

**Your Environment**
* Version used: v2.1.2
