### ISSUE TITLE
Input Forward Plugin can't user Parsers

### ISSUE THREAD

**Issue by excme** [fluent/fluent-bit#7440]
When using Fluent Id in Docker Compose, my Asp.Net Core or Java application sends logs to the Console. 
```
  loggertodockertoclickhouse:
    image: loggertodockertoclickhouse
    build:
      context: .
      dockerfile: samples/Logging/LoggerToDockerToClickHouse/Dockerfile
    networks:
      - logging-network
    logging:
        driver: fluentd
        options:
            fluentd-address: host.docker.internal:24224
```
```
[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level     trace
    Parsers_File parsers.conf

[INPUT]
    Name forward
    Listen 0.0.0.0
    Port 24224
```
```json
[{"timestamp":"2023-05-19T11:14:11.000000Z","source":"stdout","log":"{\"Timestamp\":\"2023-05-19 11:14:11.070865\",\"EventId\":0,\"LogLevel\":\"Information\"}"}]
```
The log Docker field escapes the quotes. I need to parse it, but I can't tell the Forward plugin to parse it. Add this feature please.
