### ISSUE TITLE
S3 Plugin by using IAM Role ARN without Access and Secret key in fluent-bit-0.30.3 

### ISSUE THREAD

**Issue by susikanth** [fluent/fluent-bit#7508]
## Bug Report

**Describe the bug**
try to push the logs to s3 by using IAM Role ARN without Accesskey and secretkey in the eks kubernetes cluster.
Confinguration file:

```aconf    
  [OUTPUT]
          Name s3
          Match *
          role_arn arn:aws:iam::899258264:role/pocs3-role
          bucket poctest03
          region ap-south-1
          total_file_size 800M
          s3_key_format /logs/%Y/%m/%d/%H
          s3_key_format_tag_delimiters .-_
          sts_endpoint https://sts.ap-south-1.amazonaws.com
          auto_retry_requests true
```

Passing ARN in Service Account.

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::899258264:role/pocs3-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    meta.helm.sh/release-name: monitoring
    meta.helm.sh/release-namespace: test
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/version: 2.0.8
    helm.sh/chart: fluent-bit-0.24.0
  name: fluentbit
  namespace: test
```

Role-policy:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EC2FullAccess",
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "*"
        },
        {
            "Sid": "ELBFullAccess",
            "Effect": "Allow",
            "Action": "sts:*",
            "Resource": "*"
        }
    ]
}
```
Trusted policy Created for the role :

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::<acc>:oidc-provider/oidc.eks.ap-south-1.amazonaws.com/id/8972357172805A6dff52317579741F3F"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.ap-south-1.amazonaws.com/id/<acc>:aud": "sts.amazonaws.com",
                    "oidc.eks.ap-south-1.amazonaws.com/id/<acc>:sub": "system:serviceaccount:test:fluentbit"
                }
            }
        }
    ]
}
```

**To Reproduce**
fluentbit logs:

[2023/06/01 08:04:50] [ info] [output:s3:s3.1] upload_timeout reached for kube.var.log.containers.nginx-nginx-ingress-controller-9ggbx_nginx_nginx-ingress-e5ba4dcb63f55af737cb51ca426fbcb1ed05d5706d19292a7cba3374af7af7e5.log
[2023/06/01 08:04:50] [error] [aws_credentials] STS assume role request failed
[2023/06/01 08:04:50] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will retry.
[2023/06/01 08:04:50] [error] [signv4] Provider returned no credentials, service=s3
[2023/06/01 08:04:50] [error] [aws_client] could not sign request
[2023/06/01 08:04:50] [error] [aws_credentials] STS assume role request failed
[2023/06/01 08:04:50] [ warn] [aws_credentials] No cached credentials are available and a credential refresh is already in progress. The current co-routine will retry.
[2023/06/01 08:04:50] [error] [signv4] Provider returned no credentials, service=s3
[2023/06/01 08:04:50] [error] [aws_client] could not sign request
[2023/06/01 08:04:50] [error] [output:s3:s3.1] PutObject request failed
[2023/06/01 08:04:50] [error] [engine] chunk '1-1685606678.250529958.flb' cannot be retried: task_id=0, input=tail.0 > output=s3.1
[2023/06/01 08:04:57] [ info] [engine] flush chunk '1-1685606627.329117193.flb' succeeded at retry 1: task_id=8, input=tail.0 > output=es.0 (out_id=0)

**Expected behavior**

**Screenshots**

**Your Environment**

* Version used: fluent-bit-0.30.3 
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version:
* Filters and plugins: s3

**Additional context**
