### ISSUE TITLE
Hability to disable node exporter core_throttle_count metric in VM's

### ISSUE THREAD

**Issue by gammore** [fluent/fluent-bit#7589]
**Is your feature request related to a problem? Please describe.**
When running the latest fluentbit, the node exporter input always writes to log file:
```
[error] [input:node_exporter_metrics:node_exporter_metrics.0] CPU is missing core_throttle_count: /sys/devices/system/cpu/cpu0
```

One line for each cpu core every scrape_interval seconds. This is regarding the cpu thermal throttle that won't be configured in a virtual machine where we are running it.

**Describe the solution you'd like**
I would like to disable such messages, maybe moving them to another log level (warning for example) that doesn't fill up the log output by default.

**Additional context**
I'm running fluentbit using docker-compose. These are my config files:

docker-compose.yaml
```yaml
version: '3.3'

services:
  fluentbit:
    image: fluent/fluent-bit:2.1.4-debug
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /fluent-bit/etc/fluent-bit.conf
    volumes:
      - /proc:/proc
      - /sys:/sys
      - ./fluent-bit/config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
```

fluent-bit.conf
```
[INPUT]
  name node_exporter_metrics
  tag metrics_node_exporter
  scrape_interval 5s

[OUTPUT]
  name                   prometheus_remote_write
  match                  metrics_*
  host                     prometheus
  port                     9090
  uri                       /api/v1/write
  http_user            xxx
  http_passwd      xxx
```
