### ISSUE TITLE
Support for add_label key on node_exporter_metrics and prometheus_scrape INPUTs

### ISSUE THREAD

**Issue by anderssynstad** [fluent/fluent-bit#7625]
**Is your feature request related to a problem? Please describe.**
Routing metrics through intermediate fluent-bit nodes is troublesome as the host/instance information is lost.
Example:
  node1-input-node_exporter_metrics -> node1-output-forward -> node2-input-forward  -> node2-output-prometheus_remote_write

**Describe the solution you'd like**
It would be useful if node_exporter_metrics and prometheus_scrape INPUTS supported `add_label` key similar to prometheus_remote_write.

**Describe alternatives you've considered**
An alternative would be a metrics filter, by why filter and modify if you can ensure the data is correct from the start.

**Comment by anderssynstad** [comment]
Using the new labels processor in the input, is also an alternative.

**Comment by anderssynstad** [comment]
Just for future persons wondering about the processor syntax for labels:
```
pipeline:

  inputs:

    - name: node_exporter_metrics
      tag: metrics.node
      scrape_interval: 10
      metrics: "cpu,meminfo,diskstats,filesystem,uname,stat,time,loadavg,vmstat,netdev,filefd"
      processors:
        metrics:
          - name: labels
            insert: mylabel blue
```
