### ISSUE TITLE
Opentelemetry INPUT plugin connection failure

### ISSUE THREAD

**Issue by smoms** [fluent/fluent-bit#7632]
## Bug Report

I am trying to use Fluentbit Opentelemetry INPUT plugin from Opentelemetry Collector Contrib both running as pods in K8s (in Docker Desktop, Windows 11).

Here the fluentbit yaml:

```

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: opentelemetry-fluent-bit
  namespace: myNs
  labels:
    app: opentelemetry-fluent-bit
spec:
  # replicas: 1
  selector:
    matchLabels:
      app: opentelemetry-fluent-bit
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      namespace: myNs
      labels:
        app: opentelemetry-fluent-bit
    spec:
      containers:
        - name: fluent-bit
          image: fluent/fluent-bit:2.1
          ports:
          - name: http
            containerPort: 4318
            protocol: TCP
          volumeMounts:
            - name: fluent-bit-config-vol
              mountPath: /fluent-bit/etc/
          resources:
            limits:
              memory: 1500Mi
              cpu: 500m
            requests:
              memory: 500Mi
              cpu: 500m
      serviceAccountName: otel-collector
      volumes:
        - name: fluent-bit-config-vol
          configMap:
            name: fluent-bit-config
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: myNs
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Parsers_File  parsers.conf

    [INPUT]
        name              opentelemetry
        listen            0.0.0.0
        port              4318
        successful_response_code 200

    [OUTPUT]
        name              stdout
        match             *

  parsers.conf: |
    [PARSER]
        Name               jsonparser
        Format             json

---
apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-fluent-bit
  namespace: myNs
  labels:
    app: opentelemetry-fluent-bit
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 4318
      protocol: TCP
      targetPort: http
  selector:
    app: opentelemetry-fluent-bit

```
Here the exporter config in Otel Contrib:

```
exporters:
     otlp/fb:
        endpoint: "0.0.0.0:4318"
        tls:
          insecure: true
```

And I get error:

```
2023-06-30T14:17:07.770Z    warn    zapgrpc/zapgrpc.go:191  [core] [Channel #3 SubChannel #4] grpc: addrConn.createTransport failed to connect to {
  "Addr": "opentelemetry-fluent-bit.myNs.svc.cluster.local:4318",
  "ServerName": "opentelemetry-fluent-bit.myNS.svc.cluster.local:4318",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "transport: Error while dialing dial tcp 10.96.150.150:4318: connect: connection refused"  {"grpc_log": true}
```

Also, in the log file of the Contrib pod I see the error, when I send a message to Contrib:

```
2023-06-30T15:20:06.119Z	warn	zapgrpc/zapgrpc.go:191	[core] [Channel #1 SubChannel #2] grpc: addrConn.createTransport failed to connect to {
  "Addr": "0.0.0.0:4318",
  "ServerName": "0.0.0.0:4318",
  "Attributes": null,
  "BalancerAttributes": null,
  "Type": 0,
  "Metadata": null
}. Err: connection error: desc = "error reading server preface: http2: frame too large"	{"grpc_log": true}

```

I understand that the OTel INPUT plugin in Fluentbit is stable, right? What's wrong here?

thanks
