### ISSUE TITLE
Add support for managing OpenTelemetry attributes

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluent-bit#7649]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to export logs to Grafana via the OpenTelemetry format and this [requires](https://grafana.com/docs/grafana-cloud/data-configuration/otlp/otlp-format-considerations/#logs) the ability to set OpenTelemetry attributes.

**Describe the solution you'd like**

I'd like the ability to both modify attributes as a filter and as part of the OpenTelemetry output.

**Describe alternatives you've considered**

I can use the Loki output but this isn't a documented log ingestion pattern in Grafana Cloud so support might be removed at any point.

**Additional context**

**Comment by r0mdau** [comment]
If you want `logRecords.attributes[]` you need to use fluentbit metadata and then, in the opentelemetry output you need to use `logs_attributes_metadata_key: $key` example:

```
pipeline:
  inputs:
    # - name: tail
    #   path: /log.json
    #   parser: json
    - name: dummy
      dummy: '{"message": "Hello World","verb": "GET"}'
      metadata: '{"meta": {"attribute1":"developper","attribute2":"networking"}}'

...

  outputs:

    - name: opentelemetry
...
      logs_attributes_metadata_key: meta
```

But if you need `resource.attributes[]` I need it too and we could work on a feature to fetch them from the metadata like

```
logs_resource_attributes_metadata_key: $key
```

**Comment by r0mdau** [comment]
I finally succeeded to have all resource and log attributes, configuration example:

```yaml
service:
  flush: 1
  log_level: info

pipeline:
  inputs:
    - name: dummy
      dummy: '{"resource":{"attributes":{"service.name":"devialet","online.project.key":"france"}},"message": "Hello World!","level": "info"}'
      metadata: '{"otlp":{"attributes":{"attr1":"value1"}}}'

  outputs:
    - name : stdout
      match: '*'

    - name: opentelemetry
      match: '*'
      host: localhost
      port: 3100
      logs_uri: /otlp/v1/logs
      logs_body_key: body
      logs_severity_text_message_key: level
```

So in the in_opentelemetry plugin, the `logRecords.attributes[]` are stored in the fluentbit metadata.

The out_opentelemetry plugin can extract `resource.attributes[]` from the log record and so `logRecords.attributes[]` from the metadata.

It is not consistent.

I haven't figured out why precisely the `opentelemetry_envelope` processor is not needed.
