### ISSUE TITLE
non-printable characters in the msg part of syslog output.

### ISSUE THREAD

**Issue by dElogics** [fluent/fluent-bit#7835]
The rsyslog output plugin produces some unprintable characters in the message body which are not found in the stdout or file plugin.

Config which has this issue -- 
```
service:
  log_level: warn
  parsers_file: /etc/fluentbit/cri_parser.conf
pipeline:
  inputs:
    - name: tail
      tag: kube
      path: /var/log/containers/*
      Path_Key: k8smeta
      Buffer_Max_Size: 10M
      Refresh_Interval: 5
      Rotate_Wait: 60
      Skip_Long_Lines: True
      Read_from_Head: True
      DB: /var/fluentbit/tail_db
  filters:
    - name: parser
      Parser: cri
      Key_Name: k8smeta
      match: '*'
      Reserve_Data: true
  outputs:
    - name: syslog
      host: 
      port: 514
      mode: tcp
      syslog_format: rfc5424
      syslog_hostname_key: pod
      syslog_appname_key: ns
      syslog_procid_key: conname
      syslog_severity_preset: 6
      syslog_facility_preset: 19
      syslog_message_key: log
```
parser file -- 
```
[PARSER]
    Name cri
    Format regex
    Regex ^/var/log/containers/(?<pod>[a-z0-9\-]+)_(?<ns>[a-z0-9\-]+)_(?<conname>[a-z0-9\-]+)-[a-z0-9\-]+\.log$
```

The destination is delivered to rsyslog. Logging on rsyslog works fine with the following commands --
`logger -p local3.info -t namespace --id=9823475 -P 514 -n 127.0.0.1 -T  -- asldkfjl`

With the message being delivered without any special characters.

Rsyslog config -- 
```
module(load="imtcp")
module(load="imudp")
module(load="builtin:omfile")
input(type="imtcp" port="514")
input(type="imudp" port="514")
global(parser.escapeControlCharactersOnReceive="off")

template(name="fluentBit" type="list") {
	property(name="timegenerated" dateformat="unixtimestamp")
	constant(value="|")
	constant(value="|")
	property(name="timegenerated")
	constant(value="|")
	constant(value="|")
	constant(value="|")
	property(name="timereported")
	constant(value="|")
	constant(value="|")
	property(name="timereported" dateformat="unixtimestamp")
	constant(value="|")
	property(name="app-name")
	constant(value="|")
	property(name="hostname")
	constant(value="|")
	property(name="procid")
	constant(value="|")
	property(name="msg")
	constant(value="\n")
}

template(name="hostnamefileFluentbit" type="list") {
	constant(value="/var/log/")
	property(name="procid" regex.expression="(^[A-Za-z0-9\\-]+$)" regex.type="ERE" regex.submatch="1" regex.nomatchmode="ZERO")
	constant(value=".log")
}

if ($syslogfacility == 19) then {
	action(name="logs" type="omfile" dynaFile="hostnamefileFluentbit" template="fluentBit")
	stop
}
```
