### ISSUE TITLE
Fluentbit PodMonitor endpoint HTTPS scheme is required

### ISSUE THREAD

**Issue by mbasha86** [fluent/fluent-bit#8153]
**Is your feature request related to a problem? Please describe.**

Hi there,

We've deployed the following podmonitor to use the HTTPS scheme instead of instructing Prometheus to use HTTP scheme to scrape metrics.

````yaml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ofd-prom-fluentbit
  namespace: logging
spec:
  namespaceSelector:
    matchNames:
    - logging
  podMetricsEndpoints:
  - metricRelabelings:
    - action: labeldrop
      regex: edition
    path: /api/v1/metrics/prometheus
    port: http
    relabelings:
    - action: labeldrop
      regex: endpoint|job|container
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      k8s-app: fluentbit
````
but scraping the metrics is not possible as per screenshot

<img width="1779" alt="Screenshot 2023-11-09 at 3 13 05 PM" src="https://github.com/fluent/fluent-bit/assets/37050826/459fc84a-8f03-4b54-90d1-3bee1b2620fb">

Also, here's how it's showing up from prometheus url-> status-> configuration:
````yaml
- job_name: podMonitor/logging/ofd-prom-fluentbit/0
  honor_timestamps: true
  scrape_interval: 30s
  scrape_timeout: 10s
  metrics_path: /api/v1/metrics/prometheus
  scheme: https
  tls_config:
    insecure_skip_verify: true
  follow_redirects: true
  enable_http2: true
  relabel_configs:
  - source_labels: [job]
    separator: ;
    regex: (.*)
    target_label: __tmp_prometheus_job_name
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_phase]
    separator: ;
    regex: (Failed|Succeeded)
    replacement: $1
    action: drop
  - source_labels: [__meta_kubernetes_pod_label_k8s_app, __meta_kubernetes_pod_labelpresent_k8s_app]
    separator: ;
    regex: (fluentbit);true
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_pod_container_port_name]
    separator: ;
    regex: http
    replacement: $1
    action: keep
  - source_labels: [__meta_kubernetes_namespace]
    separator: ;
    regex: (.*)
    target_label: namespace
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_container_name]
    separator: ;
    regex: (.*)
    target_label: container
    replacement: $1
    action: replace
  - source_labels: [__meta_kubernetes_pod_name]
    separator: ;
    regex: (.*)
    target_label: pod
    replacement: $1
    action: replace
  - separator: ;
    regex: (.*)
    target_label: job
    replacement: logging/ofd-prom-fluentbit
    action: replace
  - separator: ;
    regex: (.*)
    target_label: endpoint
    replacement: http
    action: replace
  - separator: ;
    regex: endpoint|job|container
    replacement: $1
    action: labeldrop
  - source_labels: [__address__]
    separator: ;
    regex: (.*)
    modulus: 1
    target_label: __tmp_hash
    replacement: $1
    action: hashmod
  - source_labels: [__tmp_hash]
    separator: ;
    regex: "0"
    replacement: $1
    action: keep
  metric_relabel_configs:
  - separator: ;
    regex: edition
    replacement: $1
    action: labeldrop
  kubernetes_sd_configs:
  - role: pod
    kubeconfig_file: ""
    follow_redirects: true
    enable_http2: true
    namespaces:
      own_namespace: false
      names:
      - logging
````

**BTW,  I have edited fluentbit config file and modified HTTP_Port value of HTTP server to make it listen to port 443 instead of 2020 and reflected that change in fluntbit daemonset (port name and value in container fluentbit) along with the same change for port name in podmonitor but same result exists.**  

**Describe the solution you'd like**
Using HTTPS Scheme to secure scrape endpoint on FluentBit. Please add TLS layer to this way (change HTTP scheme to HTTPS).

**Describe alternatives you've considered**
Using HTTP Scheme

**Additional context**
Fluentbit version: 2.1.8
