### ISSUE TITLE
out_loki is sending empty records to loki when receive records from in_forward without any modification

### ISSUE THREAD

**Issue by ansax4852** [fluent/fluent-bit#8184]
## Bug Report

**Describe the bug**
It seems that when we do not modify records from in_forward (like adding fields with FILTER record_modifier). the loki output plugin is sending an empty record.
I capture the HTTP POST request made by fluentbit to loki to detect this issue.

**To Reproduce**
- use the in_forward plugin
- **DO NOT** append fields
- use out_loki plugin

**Example fluentbit conf**
```
[INPUT]
    Name    forward
    Listen    XX.XX.XX.XX
    Port    24224
    Buffer_Chunk_Size    4M
    Buffer_Max_Size    32M

[FILTER]
    Name    record_modifier
    Match    exact.match.tag
    Record     application app

[OUTPUT]
    name    loki
    match    *
    labels    job=fluentbit, hostname=$hostname
```
In this example, only the record with tag `exact.match.tag` will be send correctly to loki with streams label 'job' and 'hostname' from record field

**Expected behavior**
The records is send to loki even if the record was not modified by fluentbit.

**Your Environment**

* Version used: 2.2.0
* Configuration: in_forward -> filter_record_modifier -> out_loki
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version:
* Operating System and version: Windows 2019
* Filters and plugins: record_modifier

**Comment by sam55silver** [comment]
I have also experienced this issue while using a tail input.

I was able to resolve the issue by going down a version to 2.1.10.

**Comment by ulexxander** [comment]
Same, version `2.2.0` no longer works, Loki is not receiving anything.

And even Prometheus metric `fluentbit_input_bytes_total` stays zero.

Downgrade to `2.1.10` helps as well.

```
[SERVICE]
  Flush 1
  HTTP_Server On
  HTTP_Listen 0.0.0.0
  HTTP_Port 2020

[INPUT]
  Name forward

[OUTPUT]
  Name loki
  Match *
  Host loki
  Port 3100
  Labels job=fluent-bit, $container_id, $container_name, $source
  Remove_Keys container_id, container_name, source
  Line_Format key_value
  Drop_Single_Key On
```

```yml
  fluent-bit:
    image: fluent/fluent-bit:2.2.0
    networks:
      - prometheus
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    restart: always
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
    labels:
      - prometheus.io/scrape=true
      - prometheus.io/path=/api/v1/metrics/prometheus
      - prometheus.io/port=2020
```
