### ISSUE TITLE
OpenTelemetry input plugin not working with Envoy Proxy - throws HTTP 400 Error

### ISSUE THREAD

**Issue by dceravigupta** [fluent/fluent-bit#8192]
## Bug Report

**Describe the bug**
I'm trying to use the opentelemetry input plugin (HTTP/Protobuf) to capture traces from Envoy Proxy. But fluentbit throws a 400 Bad Request error whenever Envoy tries to send a trace over.

![image](https://github.com/fluent/fluent-bit/assets/32182026/876199af-562f-406c-a200-1f992ade06e2)

**To Reproduce**
- Here is the envoy configuration I'm using:
```
static_resources:
  listeners:
    - address:
        socket_address:
          address: "0.0.0.0"
          port_value: 30443
      filter_chains:
        - filters:
            - name: "envoy.filters.network.http_connection_manager"
              typed_config:
                "@type": "type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager"
                codec_type: "auto"
                stat_prefix: "ingress_https"
                tracing:
                  provider:
                    name: "envoy.tracers.opentelemetry"
                    typed_config:
                      "@type": "type.googleapis.com/envoy.config.trace.v3.OpenTelemetryConfig"
                      http_service:
                        http_uri:
                          uri: "http://127.0.0.1:5317/v1/traces"
                          cluster: "opentelemetry_collector"
                          timeout: "0.250s"
                route_config:
                  virtual_hosts:
                    - name: "backend"
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: "Test"
                            auto_host_rewrite: true
                            timeout: "0s"
                http_filters:
                  - name: "envoy.filters.http.router"
                    typed_config:
                      "@type": "type.googleapis.com/envoy.extensions.filters.http.router.v3.Router"
          transport_socket:
            name: "envoy.transport_sockets.tls"
            typed_config:
              "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext"
              common_tls_context:
                tls_certificates:
                  - certificate_chain:
                      filename: "localhost.crt"
                    private_key:
                      filename: "localhost.key"
                tls_params:
                  tls_maximum_protocol_version: "TLSv1_3"
                  tls_minimum_protocol_version: "TLSv1_2"
  clusters:
    - name: "Test"
      connect_timeout: "30.0s"
      type: "STRICT_DNS"
      dns_lookup_family: "V4_ONLY"
      lb_policy: "ROUND_ROBIN"
      load_assignment:
        cluster_name: "Test"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "google.com"
                      port_value: 443
      transport_socket:
        name: "envoy.transport_sockets.tls"
        typed_config:
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext"
    - name: "opentelemetry_collector"
      type: "STRICT_DNS"
      lb_policy: "ROUND_ROBIN"
      load_assignment:
        cluster_name: "opentelemetry_collector"
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "127.0.0.1"
                      port_value: 5317
  admin:
    address:
      socket_address:
        address: "0.0.0.0"
        port_value: 8001
layered_runtime:
  layers:
    - name: "admin_layer_0"
      admin_layer: {}


```
- This configuration requires envoy version 1.28 or above.

**Your Environment**

* Version used: Fluent Bit 2.1.10
* Environment name and version (e.g. Kubernetes? What version?): Virtual Machine
* Server type and version: Envoy Proxy 1.28
* Operating System and version: Ubuntu 20.04LTS
* Filters and plugins: in_opentelemetry
