### ISSUE TITLE
When two multiline parsers are used in filters, the pipeline breaks

### ISSUE THREAD

**Issue by jmtt89** [fluent/fluent-bit#8312]
## Bug Report

**Describe the bug**
When two multiline analyzers are used in filters, the pipeline breaks, not need nothing more and don't care the log to process. 

EDIT: Fluent Bit stalls and uses high CPU.

**To Reproduce**

values.yaml
```yaml
logLevel: info
flush: 1
metricsPort: 2020

image:
  repository: fluent/fluent-bit
  tag: 2.2.0-debug

## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name   dummy
        Dummy {"message": "custom dummy"}

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        name                  multiline
        match                 *
        multiline.parser      multiline-pino-pretty
        multiline.key_content log

    [FILTER]
        name                  multiline
        match                 *
        multiline.parser      multiline-java-error
        multiline.key_content log

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |
    [OUTPUT]
        Name              stdout
        Match             *

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [MULTILINE_PARSER]
        name          multiline-pino-pretty
        type          regex
        flush_timeout 1000
        #
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules |   state name  | regex pattern                                                          | next state
        # ------|---------------|------------------------------------------------------------------------------------
        rule      "start_state"   "/^\[(?<logTime>[^ ]+)\] (?<level>[^ ]+) \((?<PID>[^ ]+)\): (?<msg>.*)$/"  "cont"
        rule      "cont"          "/^\s+.*$/"                                                                "cont"

    [MULTILINE_PARSER]
        name          multiline-java-error
        type          regex
        flush_timeout 1000
        #
        # Regex rules for multiline parsing
        # ---------------------------------
        #
        # configuration hints:
        #
        #  - first state always has the name: start_state
        #  - every field in the rule must be inside double quotes
        #
        # rules |   state name  | regex pattern                                                          | next state
        # ------|---------------|------------------------------------------------------------------------------------
        rule      "start_state"   "/^(?<logTime>[^ ]+) \[(?<thread>.*)\] (?<level>[^ ]+) (?<class>[^ ]+) - (?<msg>.*)$/"  "cont"
        rule      "cont"          "/^((([^ ]+Exception: )|(\s+)|(Caused by: )).*)$/"                     "cont"

```

**Expected behavior**
Use Two or more parsers on same pipeline

**Your Environment**
* Version used: 2.2.0
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes 1.27
