### ISSUE TITLE
fluent-bit prevents other pods on the same node from terminating gracefully

### ISSUE THREAD

**Issue by PetkoVasilev** [fluent/fluent-bit#8365]
## Bug Report

**Describe the bug**

**To Reproduce**
- run fluent-bit as a daemonset
- run another pod with a volume on the same node (in our case a mariadb server form a statefulset)
- setup fluent-bit to watch a file that is on the mounted volume from the other pod (in our case this is the slow query log file in `/var/log/mysql/slow_query.log`)
something like
```
[INPUT[]
    Name tail
    Tag raw.native.slow-query-log
    Path /var/lib/kubelet/pods/*/volumes/*/*/slow_query.log
    Path_Key  filepath
    Mem_Buf_Limit 5MB
    DB /var/log/containers/fluent-bit-native-slow.db
    DB.locking true
    DB.journal_mode WAL
    Offset_Key offset
    Read_from_Head true
    Ignore_Older 20
    Refresh_Interval 10
```
- try to delete the server pod
- the server pod is stuck in `Terminating` state forever

**Expected behavior**
the server pod terminates gracefully

**Screenshots**

**Your Environment**

* Version used: 2.1.9+
* Configuration:
* Environment name and version (e.g. Kubernetes? What version?): kubernetes 1.26
* Server type and version: mariadb 10.6 with `slow_query_log=ON` (server version does not matter actually)
* Operating System and version:
* Filters and plugins:

**Additional context**

Our goal is to export the `/var/log/mysql/slow_query.log` file from the volume. This used to work as expected with version `2.1.8` and older.
We upgraded recently to a newer version and noticed that our server pods get stuck in `Terminating` forever.

This is caused by fluent-bit keeping the watched file open. This means that k8s can't properly unmount the volume and terminate the server pod. When I also delete the fluent-bit pod, it closes the watched file ant the server pod can terminate as well.

This issue appeared with version `2.1.9`. I think specifically here https://github.com/fluent/fluent-bit/pull/7815 . In `2.1.8` an prior, setting `Ignore_Older 20` would force fluent-bit to close the file on interval, thus allowing k8s to unmount the volume.

NOTE: while the example here is about mariadb server, there is nothing in the bug that is specific to mariad. This can be replicated with any other pod that has a persistent volume, as long as fluent-bit is watching a file on it. The other pod doesn't even need to interact (create/read/write) with the file in any way, the file just needs to exist on the volume.

**Comment by PetkoVasilev** [comment]
A simple way to reproduce on minikube (mine is 1.32.0)
running k8s 1.26.0
- start and prepare minikube
```
minikube start --kubernetes-version=v1.26.0 --memory 8192 --cpus 4
# enable snapshots (not necessary, but for consistency)
minikube addons enable volumesnapshots
minikube addons enable csi-hostpath-driver
minikube addons disable storage-provisioner
minikube addons disable default-storageclass
kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
kubectl patch volumesnapshotclass csi-hostpath-snapclass --type=merge -p '{"metadata": {"labels":{"mariadb.com/snapshot.driver":"csi"}}}'
```
- use these helm values for fluentbit:
```
extraVolumes:
- name: kubelet
  hostPath:
    path: /var/lib/kubelet/pods
extraVolumeMounts:
- name: kubelet
  mountPath: /var/lib/kubelet/pods
  readOnly: true
  mountPropagation: HostToContainer
config:
  inputs: |
    [INPUT]
        Name tail
        Tag raw.csi.slow-query-log
        Path /var/lib/kubelet/pods/*/volumes/*/*/mount/my_test_file
        Path_Key  filepath
        Mem_Buf_Limit 5MB
        Offset_Key offset
        Read_from_Head true
        Ignore_Older 20
        Refresh_Interval 10
```
- install fluentbit:
```
helm repo add fluent https://fluent.github.io/helm-charts
helm upgrade --install fluent-bit fluent/fluent-bit -f fluent-values
```
- create a simple statefulset with a volume:
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: busy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy
  template:
    metadata:
      labels:
        app: busy
    spec:
      containers:
      - name: busy
        image: busybox:latest
        command:
        - tail
        args:
        - -f
        - /dev/null
        volumeMounts:
        - name: logs
          mountPath: /var/logs/mylogs
  volumeClaimTemplates:
  - metadata:
      name: logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
EOF
```
- write something to `my_test_file`:
```
kubectl exec -it busy-0 -- sh -c 'cat /var/logs/mylogs/my_test_file'
```
- wait a few seconds to be sure that fluentbit has picked up the file. fluent-bit will show something like this in the logs
```
[2024/01/25 14:17:39] [ info] [input:tail:tail.0] inotify_fs_add(): inode=27830974 watch_fd=1 name=/var/lib/kubelet/pods/cac81cdf-71d8-4b39-97be-b1cf059384ad/volumes/kubernetes.io~csi/pvc-a709ac5e-bb55-4a9d-b179-15d0e8940729/mount/my_test_file
```
- try do delete the busybox pod:
```
kubectl delete pods busy-0
```
- pods gets stuck in `Terminating` forever (or until the fluentbit pod is also deleted)

This does NOT happen with fluentbit `2.1.8` and older
