### ISSUE TITLE
Dynamically include configuration files

### ISSUE THREAD

**Issue by LeonD9** [fluent/fluent-bit#8375]
Hey,
I want to dynamically add config files to fluentbit using `HOT_RELOAD` and `@INCLUDE` functionallity.
When creating empty directory and pointing `@INCLUDE` to it like this:
```
@INCLUDE /fluent-bit/config/*.conf
```
 i receive the following error:
```
[2024/01/14 15:30:41] [ warn] [read_glob] glob: [/fluent-bit/config/*.conf] no match
[2024/01/14 15:30:41] [error] configuration file contains errors, aborting.
```
And when i try adding a temporary config file to that directory called `temp.conf` with the following configuration:
```
[OUTPUT]
    Name   stdout
    Match *
```

i get the following error:
```
[2024/01/14 10:48:59] [ warn] [config] Read twice. path=/fluent-bit/config/temp.conf
[2024/01/14 10:48:59] [error] configuration file contains errors, aborting.
```
Without `@INCLUDE` my configuration works correctly with no errors.

How can i add configuration files dynamically? how can i fix the `@INCLUDE` error?
I am using the latest fluentbit version v2.2.1 on AWS EKS v1.24.

**Comment by patrick-stephens** [comment]
@LeonD9 it's not clear if you have any config at all in the first instance - if you just have a config file that only includes other files and those files do not exist then it is a legitimate problem - what config would it be?

In the second case where you create a file with an input, the config you posted will not work - there is no `stdout` input and an error is reported along those lines for me. 

```bash
$ ls -lR
.:
total 14
drwxrwxr-x 2 pat pat  3 Jan 15 10:45 config
-rw-rw-r-- 1 pat pat 36 Jan 15 10:43 fluent-bit.conf

./config:
total 5
-rw-rw-r-- 1 pat pat 33 Jan 15 10:45 stdout.conf
$ cat fluent-bit.conf 
@INCLUDE /fluent-bit/config/*.conf

pat@calyptia-laptop:/tmp/test$ cat config/stdout.conf 
[INPUT]
  name stdout
  tag test

$ docker run --rm -it -v $PWD/config:/fluent-bit/config:ro -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro fluent/fluent-bit:2.2.2
Fluent Bit v2.2.2
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

____________________
< Fluent Bit v2.2.2 >
 -------------------
          \
           \
            \          __---__
                    _-       /--______
               __--( /     \ )XXXXXXXXXXX\v.
             .-XXX(   O   O  )XXXXXXXXXXXXXXX-
            /XXX(       U     )        XXXXXXX\
          /XXXXX(              )--_  XXXXXXXXXXX\
         /XXXXX/ (      O     )   XXXXXX   \XXXXX\
         XXXXX/   /            XXXXXX   \__ \XXXXX
         XXXXXX__/          XXXXXX         \__---->
 ---___  XXX__/          XXXXXX      \__         /
   \-  --__/   ___/\  XXXXXX            /  ___--/=
    \-\    ___/    XXXXXX              '--- XXXXXX
       \-\/XXX\ XXXXXX                      /XXXXX
         \XXXXXXXXX   \                    /XXXXX/
          \XXXXXX      >                 _/XXXXX/
            \XXXXX--__/              __-- XXXX/
             -XXXXXXXX---------------  XXXXXX-
                \XXXXXXXXXXXXXXXXXXXXXXXXXX/
                  ""VXXXXXXXXXXXXXXXXXXV""

[2024/01/15 10:47:13] [error] [config] section 'stdout' tried to instance a plugin name that don't exists
[2024/01/15 10:47:13] [error] configuration file contains errors, aborting.
```

If I use a valid input like `cpu` then it works fine:
```bash
$ cat config/stdout.conf 
[INPUT]
  name cpu
  tag test
$ docker run --rm -it -v $PWD/config:/fluent-bit/config:ro -v $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro fluent/fluent-bit:2.2.2
Fluent Bit v2.2.2
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

____________________
< Fluent Bit v2.2.2 >
 -------------------
          \
           \
            \          __---__
                    _-       /--______
               __--( /     \ )XXXXXXXXXXX\v.
             .-XXX(   O   O  )XXXXXXXXXXXXXXX-
            /XXX(       U     )        XXXXXXX\
          /XXXXX(              )--_  XXXXXXXXXXX\
         /XXXXX/ (      O     )   XXXXXX   \XXXXX\
         XXXXX/   /            XXXXXX   \__ \XXXXX
         XXXXXX__/          XXXXXX         \__---->
 ---___  XXX__/          XXXXXX      \__         /
   \-  --__/   ___/\  XXXXXX            /  ___--/=
    \-\    ___/    XXXXXX              '--- XXXXXX
       \-\/XXX\ XXXXXX                      /XXXXX
         \XXXXXXXXX   \                    /XXXXX/
          \XXXXXX      >                 _/XXXXX/
            \XXXXX--__/              __-- XXXX/
             -XXXXXXXX---------------  XXXXXX-
                \XXXXXXXXXXXXXXXXXXXXXXXXXX/
                  ""VXXXXXXXXXXXXXXXXXXV""

[2024/01/15 10:48:48] [ info] [fluent bit] version=2.2.2, commit=eeea396e88, pid=1
[2024/01/15 10:48:48] [ info] [storage] ver=1.5.1, type=memory, sync=normal, checksum=off, max_chunks_up=128
[2024/01/15 10:48:48] [ info] [cmetrics] version=0.6.6
[2024/01/15 10:48:48] [ info] [ctraces ] version=0.4.0
[2024/01/15 10:48:48] [ info] [input:cpu:cpu.0] initializing
[2024/01/15 10:48:48] [ info] [input:cpu:cpu.0] storage_strategy='memory' (memory only)
[2024/01/15 10:48:48] [ info] [sp] stream processor started
```

**Comment by LeonD9** [comment]
@patrick-stephens You are correct my mistake regarding the `INPUT` stdout i wrote it incorrectly in the description.
I tried using it as you mentioned, this is my fluent-bit.conf file:
```
[SERVICE]
    Flush         5
    Daemon        off
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020
    Health_Check On
    Hot_Reload   On
    HC_Errors_Count 5
    HC_Retry_Failure_Count 5
    HC_Period 5
    Log_Level     info
    Parsers_File  parsers.conf

@INCLUDE /fluent-bit/config/*.conf

[INPUT]
    Name                tail
    Alias               input-kube-pods-logs
    Path                /var/log/containers/*.log
    Path_Key            path
    Offset_Key          logs.offset
    multiline.parser    cri
    Refresh_Interval    5
    tag                 kubernetes.*
    db                  /etc/fluentbit/db/kubernetes-pods.db
    threaded            on

[INPUT]
    Name                tail
    Alias               input-kube-node-logs
    Path                /var/log/*.log, /var/log/syslog, /var/log/messages
    Path_Key            path
    Parser              syslog-rfc3164
    Refresh_Interval    5
    tag                 kubernetes-nodes.*
    db                  /etc/fluentbit/db/kubernetes-nodes.db
    threaded            on

[FILTER]
    Name                kubernetes
    Alias               filter-kubernetes
    Match               kubernetes.*
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Kube_Tag_Prefix     kubernetes.var.log.containers.
    Merge_Log           Off
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
    Kube_Meta_Cache_TTL 10
    Buffer_Size         100k

[FILTER]
    Name        parser
    Alias       parse-json
    Match       *
    Key_Name    log
    Parser      json
    Reserve_Data On
 
 [OUTPUT]
    Name        forward
    Alias       forward-to-fluentd
    Match       *
    Upstream    /fluent-bit/etc/upstream.conf
    Port        24224
    Retry_Limit False
```

and this is what i put in the /fluent-bit/config/temp.conf file:
```
[INPUT]
  name cpu
  tag test
```

And i receive the following error:
```
Fluent Bit v2.2.1
* Copyright (C) 2015-2023 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

       \ || /
       = ** =
        /__\ 
       /____\
      /______\
     /________\

```
Also this are my volume mounts:
```
  - name: tempdir
    emptyDir: {}
  - name: config
    projected:
      defaultMode: 0644
      configMaps:
      - name: $RELEASE-config
        items:
        - key: fluent-bit.conf.tpl
          path: fluent-bit.conf
  - name: parsers
    projected:
      defaultMode: 0644
      configMaps:
      - name: $RELEASE-config
        items:
        - key: parsers.conf.tpl
          path: parsers.conf
  - name: upstream
    projected:
      defaultMode: 0644
      configMaps:
      - name: $RELEASE-config
        items:
        - key: upstream.conf.tpl
          path: upstream.conf
  - name: temp
    projected:
      defaultMode: 0644
      configMaps:
      - name: $RELEASE-config
        items:
        - key: temp.conf.tpl
          path: temp.conf
      volumeMounts:
      - name: tempdir
        mountPath: /fluent-bit/config
      - name: temp
        mountPath: /fluent-bit/config/temp.conf
        subPath: temp.conf
      - name: config
        mountPath: /fluent-bit/etc/fluent-bit.conf
        subPath: fluent-bit.conf
      - name: parsers
        mountPath: /fluent-bit/etc/parsers.conf
        subPath: parsers.conf
      - name: upstream
        mountPath: /fluent-bit/etc/upstream.conf
        subPath: upstream.conf
      - name: varlog
        mountPath: /var/log
        readOnly: true
```
I do see `temp.conf` file with the correct configuration being mounted to the pod and without `@INCLUDE` the fluent-bit.conf configuration works correctly as well.

I just need a temporary config file in a new directory so i will be able to upload additional configs there and use there with `@INCLUDE` functionality, this way worked in the version before v2.
