### ISSUE TITLE
health check reports always health when it has backlog files, even the output http server is down

### ISSUE THREAD

**Issue by carlosrmendes** [fluent/fluent-bit#8391]
## Bug Report

**Describe the bug**
Health check reports always health when it has backlog files, even the output http server is down

**To Reproduce**
Set health_check, take the output server down, wait for the creation of some backlog files in filesystem, restart fluentbit. confirm the multiple log messages with "failed to flush chunk" but requesting http://localhost:2020/api/v1/health returns always "ok - 200".
```
```
my config:
```yaml
service:
flush: 5
http_server: on
#log_level: debug
scheduler.cap: 300
hot_reload: on
health_check: on
hc_period: 275
hc_errors_count: 5
hc_retry_failure_count: 5
storage.path: /data/logs/
storage.max_chunks_up: 256
storage.backlog.mem_limit: 256M
storage.delete_irrecoverable_chunks: on
#parsers_file: parsers.conf

pipeline:
inputs:
  - name: tail
    refresh_interval: 5
    read_from_head: true
    db: /data/fluentbit.db
    storage.type: filesystem
    buffer_max_size: 512K
    buffer_chunk_size: 256K
    static_batch_size: 256M
    multiline.parser: docker, cri
    tag: <namespace>.<workload>.<container>
    tag_regex: (?<workload>[a-z0-9](?:[-a-z0-9]*[a-z0-9])?(?:\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*)_(?<namespace>[^_]+)_(?<container>.+)-([a-z0-9]{64})\.log$
    path: /var/log/containers/*_kelvin-admin_*.log,/var/log/containers/*_kelvin_*.log,/var/log/containers/*_app_*.log

filters:
  - name: record_modifier
    match: "*"
    remove_key: _p

  - name: record_modifier
    match: "*"
    remove_key: stream

  - name: modify
    match: "*"
    add: cluster ${KELVIN_CLUSTER_NAME}

  - name: modify
    match: "*"
    add: node ${KUBERNETES_NODE_NAME}

  - name: lua
    match: "*"
    call: tag_fields
    code: |
      function tag_fields(tag, timestamp, record)
        tags = {}

        for t in string.gmatch(tag, "[^%.]+") do
          table.insert(tags, t)
        end

        record["namespace"] = tags[1]
        record["pod"] = tags[2]

        if record["namespace"] == "app" then
          record["workload"] = string.gsub(tags[2], "-0$", "")
        end

        record["container"] = tags[3]

        return 1, timestamp, record
      end

  - name: lua
    match: "*"
    call: log_fields
    code: |
      function log_fields(tag, timestamp, record)
        cjson = require("cjson")

        log = record["log"]
        status, parsed_log = pcall(cjson.decode, log)

        if status and type(parsed_log) == "table" then
          if parsed_log["level"] then
            record["level"] = string.lower(parsed_log["level"])
          end
          if parsed_log["logger"] then
            record["logger"] = parsed_log["logger"]
          end
        end
      
        return 1, timestamp, record
      end

outputs:
  - name: http
    match: "*"
    host: localhost
    port: 443
    workers: 5
    tls: on
    tls.verify: off
    compress: gzip
    format: json_lines
    retry_limit: no_limits
    net.connect_timeout: 150
    log_response_payload: false
    storage.total_limit_size: 5G
```

If I delete all backlog files, the health check starts to fail.
