### ISSUE TITLE
Inconsistent Behavior on DB Management

### ISSUE THREAD

**Issue by Saya47** [fluent/fluent-bit#8495]
## Bug Report

**Describe the bug**
If the Tail input plugin is declared before the Systemd input plugin, the DB for Systemd doesn't get created and the same DB used for Tail will be used for Systemd. You can see the DB file opened on my SQLite explorer on the picture below:
![image](https://github.com/fluent/fluent-bit/assets/35542834/49f8e8c0-eb94-4084-9c8a-0ee871182658)

But if you declare the Systemd input plugin first then declare the Tail plugin, then you will have a DB for Systemd and another DB for Tail. You can see the DB files created on the picture below:
![image](https://github.com/fluent/fluent-bit/assets/35542834/ac3b20d4-b307-488b-a2a2-dcd7beee90fc)

**To Reproduce**
I don't know if this applies to classic config too, but this happened to me on YAML configuration.

fluent-bit.yaml:
```yaml
includes:
    - env.yaml
    - files.yaml
    - metrics.yaml
    - output.yaml
    - services.yaml
...
```

files.yaml:
```yaml
pipeline:
  inputs:
    - Name: tail
      Path: "/var/log/*.log"
      Key: log_raw
      Tag: tail
      # Read_from_Head: True
      DB: /opt/fluent-bit/db/tail.db
...
```

services.yaml
```yaml
pipeline:
  inputs:
    - Name: systemd
      Tag: systemd
      DB: /opt/fluent-bit/db/systemd.db
...
```

**Expected behavior**
If user specifies different DB paths for Tail and Systemd, the user expects the path specified to be used for cursor management, regardless of the order of input plugins declarations.

**Your Environment**
Linux logserver 6.1.0-10-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.37-1 (2023-07-03) x86_64 GNU/Linux

Fluent Bit v2.2.2

**Additional context**
I was running into issues with Systemd with incorrect log timestamps, something similar to what happened here: https://github.com/systemd/systemd/issues/2738

I had some logs on Systemd which were dated for 2025! So When I ran Fluent-bit, it sent all logs from beginning till 2025 and then it stopped sending new logs that were created, due to the issue described on the Systemd issue on link above. This issue with Systemd along the Fluent-bit bug explained on this post caused a lot of confusion.

Thanks very much for reading.
