### ISSUE TITLE
out_loki: no escaping with `key_value` output format

### ISSUE THREAD

**Issue by savoiringfaire** [fluent/fluent-bit#8562]
## Bug Report

**Describe the bug**
I'm using fluent-bit to write to loki with the `key_value` `line_format` (which, in my head at least, is equivelent to `logfmt` and I'm opening this with the assumption that we want to support fluent-bit `key_value` output being parseable). E.g. the log line `tes"t` shows up in loki as `log="tes"t"` rather than `log="tes\"t"` as I would have expected. As far as I can tell the Grafana fluent-bit plugin does handle this through https://github.com/grafana/loki/blob/main/vendor/github.com/go-logfmt/logfmt/jsonstring.go#L51. Additionally, the `jsonstring.go` escapes other special characters too.

**To Reproduce**

Using the config:

```
pipeline:
  inputs:
    - name: tail
      tag: test
      path: ./test.log
  outputs:
    - name: stdout
      match: '*'
    - name: loki
      match: '*'
      host: -----
      port: 443
      tls: On
      http_user: -----
      http_passwd: -----
      line_format: key_value
```

and then running `echo "tes\"t" >> test.log` results in log lines showing up in Loki with `log="tes"t"`

**Expected behavior**

The `line_format` output is correctly parseable by the `loki` `logfmt` parser when it has quotes in by escaping any quotes (and possibly other special characters) inside of strings. E.g. the line `tes"t` in a log file would output `log="tes\"t"` to align with what the loki logfmt parser is able to parse, and what the Grafana-provided fluent-bit plugin provides.

**Your Environment**

* Version used: 2.2.2
* Configuration: as above
* Environment name and version (e.g. Kubernetes? What version?): locally with docker for testing, though first noticed in ECS with Firelens
* Server type and version: n/a
* Operating System and version: Docker
* Filters and plugins: only default

**Additional context**

We aren't always in control of the log lines that applications output, so having certain characters completely break our parsing ability for some lines makes it hard to use fluent-bit with the default plugin for our platform. Instead, we're likely going to switch to either the Grafana-provided plugin, or Fluentd. In this particular case the default Apache output format breaks our log messages as it uses quotes.
