### ISSUE TITLE
processor_content_modifier doesn't support some conversion rules

### ISSUE THREAD

**Issue by nokute78** [fluent/fluent-bit#8592]
## Bug Report

**Describe the bug**

processor_content_modifier doesn't support some conversion rules.
e.g. positive integer -> string, boolean -> string

**To Reproduce**
- Rubular link if applicable:
- Example log message if applicable:
- Steps to reproduce the problem:

a.yaml:
```yaml
pipeline:
  inputs:
    - name: dummy
      dummy: '{"message": "custom dummy", "a":100}'
      samples: 1
      processors:
        logs:
            - name: content_modifier
              action: convert
              context: message
              key: "a"
              converted_type: "string"
  outputs:
    - name: stdout
      match: '*'
```

**Expected behavior**

processor_content_modifier should convert it.

**Screenshots**

**Your Environment**

* Version used: [master](https://github.com/fluent/fluent-bit/tree/be857e992d39b54d0d5ac4230ff615dce37accb6)
* Configuration: See above.
* Environment name and version (e.g. Kubernetes? What version?):
* Server type and version: Linux 
* Operating System and version: Ubuntu 22.04
* Filters and plugins: See above.

**Additional context**

We already support `flb_typecast.c` to convert data type, however processor_content_modifier doesn't use it.
I think it is better to use/enhance flb_typecast.c to unify conversion rules.
