### ISSUE TITLE
InfluxDB output plugin fails with OpenTelemetry input

### ISSUE THREAD

**Issue by BenedekKoncz** [fluent/fluent-bit#8668]
## Bug Report

**Describe the bug**
Can not forward metrics received by the OpenTelemetry input plugin to InfluxDB v2 with the influxdb output plugin due to missing measurement name (the equivalent of table name in influx).

**To Reproduce**
- Run fluent bit locally and influx db locally in a docker containers with the following configuration
   docker-compose.yaml (shorted for brevity):
   ```
   fluentbit:
    image: fluent/fluent-bit:3.0.0
    environment:
      - FLUENT_BIT_CONFIG=/fluent-bit/etc/fluent-bit.conf
    ports:
      - "4318:4318"
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./logs:/fluent-bit/logs
    networks:
      - local-dev

  influx:
    image: influxdb:2.7-alpine
    volumes:
      - ./influx/data:/var/lib/influxdb2" \
      - ./influx/config:/etc/influxdb2" \
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=somecoolpassword
      - DOCKER_INFLUXDB_INIT_ORG=test
      - DOCKER_INFLUXDB_INIT_BUCKET=test
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - local-dev
   ```
    fluent-bit.conf:
   ```
    [SERVICE]
    Flush 5
    Daemon off
    Log_Level trace

    [INPUT]
    name opentelemetry
    listen 0.0.0.0
    port 4318
    tag otel

    [OUTPUT]
    Name stdout
    Match *

    [OUTPUT]
    Name influxdb
    Match *
    Host localhost
    Port 8086
    Org test
    Bucket test
    HTTP_Token my-super-secret-auth-token
    ```
    Both the stdout and influxdb output is configured for debugging.
- Start sending OTEL metrics from your app (e.g. sample app here: https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples/auto-instrumentation)
- Observ the stdout of the fluentbit container. The processed metrics record(?) show up in the output, see the example below.
```
2024-04-02T16:39:07.632200964Z 2024-04-02T16:39:04.812025630Z _http.server.active_requests{http.scheme="http",http.method="GET",http.host="172.24.0.6:8080",http.flavor="1.1",http.server_name="localhost:8080"} = 0
2024-04-02T16:39:07.632218964Z 2024-04-02T16:39:04.812025630Z _http.server.duration{http.scheme="http",http.method="GET",http.host="172.24.0.6:8080",http.flavor="1.1",http.server_name="localhost:8080",net.host.port="8080",http.target="/v2/chat/conversations"} = { buckets = { 0=0, 5=0, 10=4, 25=3, 50=2, 75=2, 100=0, 250=0, 500=0, 750=0, 1000=0, 2500=0, 5000=0, 7500=0, 10000=0, +Inf=0 }, sum=267, count=11 }
2024-04-02T16:39:07.632226006Z 2024-04-02T16:39:04.812025630Z _http.server.response.size{http.scheme="http",http.method="GET",http.host="172.24.0.6:8080",http.flavor="1.1",http.server_name="localhost:8080",net.host.port="8080",http.target="/v2/chat/conversations"} = { buckets = { 0=0, 5=0, 10=0, 25=0, 50=0, 75=0, 100=0, 250=0, 500=0, 750=0, 1000=0, 2500=11, 5000=0, 7500=0, 10000=0, +Inf=0 }, sum=13475, count=11 }
```
But there is also an error message from the influxdb output plugin that states that the insert has failed.
```
2024-04-02T16:39:07.639897089Z [2024/04/02 16:39:07] [error] [output:influxdb:influxdb.1] http_status=400
2024-04-02T16:39:07.639957464Z {"code":"invalid","message":"unable to parse ',http.scheme=http,http.method=GET,http.host=172.24.0.6:8080,http.flavor=1.1,http.server_name=localhost:8080 http.server.active_requests=0 1712075944812025630': missing measurement\nunable to parse ',http.scheme=http,http.method=GET,http.host=172.24.0.6:8080,http.flavor=1.1,http.server_name=localhost:8080,net.host.port=8080,http.target=/v2/chat/conversations 0=0,5=0,10=4,25=3,50=2,75=2,100=0,250=0,500=0,750=0,1000=0,2500=0,5000=0,7500=0,10000=0,+Inf=0,sum=267,count=11 1712075944812025630': missing measurement\nunable to parse ',http.scheme=http,http.method=GET,http.host=172.24.0.6:8080,http.flavor=1.1,http.server_name=localhost:8080,net.host.port=8080,http.target=/v2/chat/conversations 0=0,5=0,10=0,25=0,50=0,75=0,100=0,250=0,500=0,750=0,1000=0,2500=11,5000=0,7500=0,10000=0,+Inf=0,sum=13475,count=11 1712075944812025630': missing measurement"}
```
It seems the data to be inserted does not follow the InfluxDB lineprotocol, that should start with the measurement (=table) name, so it is rejected. `|measurement|,tag_set| |field_set| |timestamp|`. 

**Expected behavior**
The OpenTelemetry metrics are inserted into InfluxDB

**Your Environment**

* Version used: 3.0
* Configuration: 
```
    [SERVICE]
    Flush 5
    Daemon off
    Log_Level trace

    [INPUT]
    name opentelemetry
    listen 0.0.0.0
    port 4318
    tag otel

    [OUTPUT]
    Name stdout
    Match *

    [OUTPUT]
    Name influxdb
    Match *
    Host localhost
    Port 8086
    Org test
    Bucket test
    HTTP_Token my-super-secret-auth-token
```
* Environment name and version (e.g. Kubernetes? What version?): docker
* Operating System and version: macOS, 14.2.1
* Filters and plugins: opentelemetry, influxdb

**Additional context**
I new to fluentbit and tried to follow the documentation, but it is not obvious to me, why this setup is not working. Maybe I am only missing filter that could modify the internal data representation. I have tried to influxdb output plugin with a dummy input and a cpu input, and both are wokring but not the OpenTelemetry.
