### ISSUE TITLE
Tail plugin option Exclude_Path not working on YAML configuration

### ISSUE THREAD

**Issue by mfabricanti** [fluent/fluent-bit#8699]
## Bug Report

**Describe the bug**
We have a Kubernetes cluster and we're using Tail plugin to collect the logs, using Exclude_Path option to exclude some namespaces of it (put annotations in each pod is too overhead).

When using Exclude_Path of Tail input plugin in CONF configuration works normally. Like this:
```
    [INPUT]
      Name              tail
      Path              /var/log/containers/*.log
      Parser            cri
      Tag               kube.*
      Mem_Buf_Limit     5MB
      Skip_Long_Lines   On
      Skip_Empty_Lines  On
      Exclude_Path      *_kube-*_*,*_ingress*_*
```

We're trying to changing config file to YAML (so we can use processors), and the Exclude_Path option is not working, and makes fluent-bit impossible to startup.
```
pipeline:
      inputs:
        - name: tail
          tag: kube.*
          path: /var/log/containers/*.log
          parser: cri
          mem_buf_limit: 5MB
          skip_long_lines: on
          skip_empty_lines: on
          exclude_path: *_kube-*_*,*_ingress*_*
```
Removing the exclude_path option works ok.

With the option enabled, the only log I got from FB is:
```
Fluent Bit v3.0.0
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io

___________.__                        __    __________.__  __          ________  
\_   _____/|  |  __ __   ____   _____/  |_  \______   \__|/  |_  ___  _\_____  \ 
 |    __)  |  | |  |  \_/ __ \ /    \   __\  |    |  _/  \   __\ \  \/ / _(__  < 
 |     \   |  |_|  |  /\  ___/|   |  \  |    |    |   \  ||  |    \   / /       \
 \___  /   |____/____/  \___  >___|  /__|    |______  /__||__|     \_/ /______  /
     \/                     \/     \/               \/                        \/ 

[2024/04/10 13:54:01] [error] [config] invalid YAML format in file /fluent-bit/etc/conf/fluent-bit.yaml
[2024/04/10 13:54:01] [error] configuration file contains errors, aborting.
```

**To Reproduce**

Install fluent-bit v3.0.0 using a basic YAML configuration to get logs from Kubernetes using tail plugin (w/ exclude_path option using multplies paths) and output stdout plugin (for testing only).

- Install helm chart fluent-bit-0.46.0 (uses FB v.3.0.0) in some k8s cluster
- Change DS fluent-bit arg to reference yaml file 
```
--config=/fluent-bit/etc/conf/fluent-bit.yaml
```
- Apply configuration in cluster:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-yaml
  namespace: logging-teste
  labels:
    helm.sh/chart: fluent-bit-0.43.0
    app.kubernetes.io/name: fluent-bit
    app.kubernetes.io/instance: fluent-bit
    app.kubernetes.io/version: "2.2.2"
    app.kubernetes.io/managed-by: Helm
data:
  custom_parsers.conf: |
    [PARSER]
      Name cri
      Format regex
      Regex ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
      Time_Key    time
      Time_Format %Y-%m-%dT%H:%M:%S.%L%z

  fluent-bit.yaml: |
    service:
        flush:       5
        daemon:      off
        log_level:   debug
        http_server: off
        parsers_file /fluent-bit/etc/conf/custom_parsers.conf
        
    pipeline:
      inputs:
        - name: tail
          tag: kube.*
          path: /var/log/containers/*.log
          parser: cri
          mem_buf_limit: 5MB
          skip_long_lines: on
          skip_empty_lines: on
          exclude_path: *_kube-*_*,*_ingress*_*
      
      outputs:
        - name: stdout
          match: kube.*


```

**Expected behavior**
Fluent-bit working well with same behavior of CONF configuration, getting logs from kubernetes nodes excluding logs from specific namespaces in exclude_path option.

**Your Environment**
* Version used: Fluent-bit v3.0.0
* Kubernetes AWS EKS v1.27.5

**Additional Context**
Already tried onther syntaxes without success.

```
pipeline:
  inputs:
     - name: tail
        tag: kube.*
        exclude_path: *_kube-*_*,*_ingress*_*
```

```
pipeline:
  inputs:
     - name: tail
        tag: kube.*
        exclude_path:
          - *_kube-*_*
          - *_ingress*_*
```

```
pipeline:
  inputs:
     - name: tail
        tag: kube.*
        exclude_path: '*_kube-*_*,*_ingress*_*'
```

```
pipeline:
  inputs:
     - name: tail
        tag: kube.*
        exclude_path: 
          *_kube-*_*
          *_ingress*_*
```
