### ISSUE TITLE
tag_from_uri in opentelemetry input plugin has no effect

### ISSUE THREAD

**Issue by trondhindenes** [fluent/fluent-bit#8734]
## Bug Report

**Describe the bug**
if configuring `tag_from_uri` on the opentelemetry input plugin, tags are not updated

**To Reproduce**
- Steps to reproduce the problem:
given this config:
```
pipeline:
    inputs:
        - name: opentelemetry
          listen: 0.0.0.0
          port: 4320
          tag_from_uri: "true"
    outputs:
        - name: 'stdout'
          match: '*'
```

And this curl
```
curl --header "Content-Type: application/json" --request POST --data '{"resourceLogs":[{"resource":{},"scopeLogs":[{"scope":{},"logRecords":[{"timeUnixNano":"1660296023390371588","body":{"stringValue":"{\"message\":\"dummy\"}"},"traceId":"","spanId":""}]}]}]}'   http://localhost:4320/v1/logs
```
I would expect the message to be tagged with `v1_logs`. However, it's not retagged, the tag is still `opentelemetry.0`

**Expected behavior**
tags should be changed to reflect the uri

**Your Environment**

* Version used: current version in `cr.fluentbit.io/fluent/fluent-bit`
* Configuration: see above
* Environment name and version (e.g. Kubernetes? What version?): regular docker

**Additional context**
without this functionality it is very difficult to route opentelemetry data (for example logs to loki, metrics to prometheus etc) using fluent-bit.
