### ISSUE TITLE
Stackdriver Output When not on GCP/GCE

### ISSUE THREAD

**Issue by paulleroyza** [fluent/fluent-bit#8804]
## Bug Report

The stackdriver plugin appears to only want to use the google metadata service even if running off cloud. Reopening #5563

**To Reproduce**

- deploy fluentbit:3.0.3 daemonset on K3S cluster
- set `fluentbit.conf` as 
```
[SERVICE]
    Flush         5
    Grace         120
    Log_Level     trace
    #Log_File      /var/log/fluentbit.log
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_PORT     2020
    storage.backlog.mem_limit 5M

[INPUT]
    Name cpu
    Tag  my_cpu

[OUTPUT]
    Name        stackdriver
    Match       *
```

Error message
```
[2024/05/08 16:47:04] [ info]      stackdriver.0
[2024/05/08 16:47:04] [debug] [engine] coroutine stack size: 196608 bytes (192.0K)
[2024/05/08 16:47:05] [debug] [stackdriver:stackdriver.0] created event channels: read=850 write=896
[2024/05/08 16:47:05] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2024/05/08 16:47:05] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2024/05/08 16:47:05] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2024/05/08 16:47:05] [error] [output:stackdriver:stackdriver.0] failed to create metadata connection
[2024/05/08 16:47:05] [error] [output:stackdriver:stackdriver.0] can't fetch token from the metadata server
[2024/05/08 16:47:05] [ warn] [output:stackdriver:stackdriver.0] token retrieval failed
[2024/05/08 16:47:05] [error] [output:stackdriver:stackdriver.0] failed to create metadata connection
[2024/05/08 16:47:05] [error] [output:stackdriver:stackdriver.0] can't fetch project id from the metadata server
[2024/05/08 16:47:05] [error] [output] failed to initialize 'stackdriver' plugin
```

**Expected behavior**
The plugin should honour the GOOGLE_APPLICATION_CREDENTIALS environment variable and use the service account impersonation for workload identity federation from https://cloud.google.com/iam/docs/workload-identity-federation#oidc-credential-security

**Your Environment**
* Version used: fluentbit:3.0.3 (arm)
* Configuration: daemonset with Workload Identity Federation configured
* Environment name and version (e.g. Kubernetes? What version?): Raspberry Pi cluster running K3S 1.29
* Filters and plugins: stackdriver plugin

**Additional context**
I am setting up fluentbit logging to Google Cloud using workload identity federation. This would be for non-GCP non-GKE clusters to use GCP as a centralized log sink. I have tried adding the `google_service_credentials`, `project_id_key` and `export_to_project_id` keys in all variations and they have been ignored as the metadata service seems to be the only way the plugin gets the credentials.

The credential configuration file has the correct details for the KSA/GSA federation and I have changed the container from `fluentbit:3.0.3` to `gcloud-sdk:alpine` to test that the pod has connection to cloud logging and I can fetch the logs (I gave the SA logs writer and logs viewer in order to test). This is not a network or credential/federation issue but seems to be the plugin ignoring that it isn't in the cloud.

**Comment by ascopes** [comment]
Please can this be reopened? It is still an active issue affecting other thirdparty products depending on this.

**Comment by braydonk** [comment]
Hi @paulleroyza,

Thanks for bringing this to my attention in the community meeting.  
It seems like I was remembering correctly, and the intended behaviour is that `GOOGLE_APPLICATION_CREDENTIALS` is supposed to be chosen as the priority if it's there, but there was a detail I forgot. The service account key file does need to have a field `private_key`. I'm going to have to ask someone on my team why it only works if the private key is in the JSON file, I wasn't part of the development of this feature so I don't know offhand.

Is there any way you'd be able to try this again with a service account JSON file that has a `private_key` field?

**Comment by paulleroyza** [comment]
Hi Braydon,

I'll test it out, I think the issue is only if it's a federated identity
file.

Regards,
Paul

**Comment by braydonk** [comment]
I don't have an easy way to test for myself, but based on everything I've read I believe if you [create an impersonating Service Account](https://cloud.google.com/iam/docs/workload-download-cred-and-grant-access#impersonation) and [export a key for it](https://cloud.google.com/iam/docs/keys-create-delete) then the plugin should behave as expected. Let me know if it does not.

**Comment by paulleroyza** [comment]
If I use a download SA Key it works as expected, however when using a WIF credential key it fails. 
It works with an SA key formatted as: 
```json
{
  "type": "service_account",
  "project_id": "",
  "private_key_id": "",
  "private_key": "",
  "client_email": "logwriter@project_id.iam.gserviceaccount.com",
  "client_id": "",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/logwriter%40project_id.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}
```

but not with a federated service account formatted as:
```json
{
  "type": "external_account",
  "audience": "//iam.googleapis.com/projects/project_number/locations/global/workloadIdentityPools/pool-k8s-picluster-1/providers/oidc-provider-k8s-1",
  "subject_token_type": "urn:ietf:params:oauth:token-type:jwt",
  "token_url": "https://sts.googleapis.com/v1/token",
  "credential_source": {
    "file": "/var/run/service-account/token",
    "format": {
      "type": "text"
    }
  },
  "service_account_impersonation_url": "https://iamcredentials.googleapis.com/v1/projects/-/serviceAccounts/logwriter@project_id.iam.gserviceaccount.com:generateAccessToken"
}
```

When running a test workload with a `gcloud:alpine`  container, both federation and download key work with the following manifest:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wif-test
spec:
  selector:
    matchLabels:
      app: wif-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wif-test
    spec:
      serviceAccount: wif-test
      terminationGracePeriodSeconds: 0
      containers:
      - name: wif-test
        image: gcr.io/google.com/cloudsdktool/google-cloud-cli:470.0.0-alpine
        command: ["sleep","infinity"]
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/arch: arm64
        kubernetes.io/os: linux
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/etc/workload-identity/credential-configuration.json"
        volumeMounts:
        - name: token
          mountPath: "/var/run/service-account"
          readOnly: true
        - name: workload-identity-credential-configuration
          mountPath: "/etc/workload-identity"
          readOnly: true
      volumes:
      - name: token
        projected:
          sources:
          - serviceAccountToken:
              audience: https://iam.googleapis.com/projects/project_number/locations/global/workloadIdentityPools/pool-k8s-picluster-1/providers/oidc-provider-k8s-1
              expirationSeconds: 3600
              path: token
      - name: workload-identity-credential-configuration
        configMap:
          name: logging-sa-conf # Credential file as posted above
      serviceAccount: logging-sa
```

When using the federated file fluent-bit requests data from the metadata server. Currently I'm redirecting this to a side car which exposes the `project-id`, `project-number` and `token` (which uses federation to get it) as a webserver that looks like the VPC metadata server using the following `go` sidecar:
```
[OUTPUT]
    # write the log records that still have the 'kube.*' tags to Cloud Logging
    Name    stackdriver
    Match   kube.*
    # The following fields are necessary. They allow filtering in Cloud Logging
    # based on resource types. Change them accordingly based on your setup.
    resource  k8s_container
    k8s_cluster_name  picluster
    k8s_cluster_location  europe-west2
    project_id_key  project_id
    metadata_server http://127.0.0.1   # Direct query to sidecar metadata server
```

Sidecar code hack
```golang
package main

import (
    "context"
    "net/http"
    "time"
    "log"
    "os"
    "fmt"
    "strconv"

    "github.com/gin-gonic/gin" // or another Go web framework
    "golang.org/x/oauth2/google" // Google Cloud authentication
)

func secondsToFuture(futureTime time.Time) int {
    now := time.Now().UTC()
    diff := futureTime.Sub(now)
    secondsRemaining := int(diff.Seconds())
    return max(0, secondsRemaining)
}

func max(a, b int) int {
    if a > b {
        return a
    }
    return b
}

func getAccessToken() (map[string]interface{}, error) {
    ctx := context.Background()
    creds, err := google.FindDefaultCredentials(ctx, "https://www.googleapis.com/auth/cloud-platform")
    if err != nil {
        return nil, err
    }

    // Note: Google Cloud credentials typically auto-refresh
    token, err := creds.TokenSource.Token() 

    result := map[string]interface{}{
        "access_token": token.AccessToken,
        "expires_in":   secondsToFuture(token.Expiry),
        "token_type":   "Bearer",
    }
    return result, nil
}

func main() {
    log.Printf("Init") 
    router := gin.Default()

    // Port Configuration
    port := 8080 // Default port
    if portEnv := os.Getenv("PORT"); portEnv != "" {
        var err error
        port, err = strconv.Atoi(portEnv)
        if err != nil {
            log.Fatalf("Invalid port from environment: %v", err)
        }
    }
    log.Printf("Starting server on port %d\n", port) 

    // Routes
    router.GET("/computeMetadata/v1/instance/service-accounts/default/token", func(c *gin.Context) {
        log.Println("Request for token")
        token, err := getAccessToken()
        if err != nil {
            log.Printf("Error getting token: %v", err)
            c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
            return
        }
        c.JSON(http.StatusOK, token)
    })
    
    router.GET("/computeMetadata/v1/project/project-id", func(c *gin.Context) {
        log.Println("Request for project_id")
        c.String(http.StatusOK, "project_id")
    })

    router.GET("/computeMetadata/v1/instance/zone", func(c *gin.Context) {
        log.Println("Request for zone")
        c.String(http.StatusOK, "projects/project_number/zones/europe-west1-d")
    })

    router.GET("/computeMetadata/v1/instance/id", func(c *gin.Context) {
        log.Println("Request for instance-id")
        c.String(http.StatusOK, "some_random_id")
    })

    // Error Handling (with logging)
    router.NoRoute(func(c *gin.Context) {
        path := c.Request.URL.Path
        log.Printf("404 Not Found: %s", path)
        c.String(http.StatusNotFound, "Resource not found")
    })

    // Start Server
    router.Run(fmt.Sprintf(":%d", port))  // Dynamic port binding
}
```

Without the metadata sidecar, fluent-bit tries anyway (I removed the metadata server config pointing to `127.0.0.1`):
Logs:
```
$ k -n fluent-bit logs -f fluent-bit-sg7xk -c  fluent-bit | grep stackdriver
[2024/10/04 15:28:20] [ info] [output:stackdriver:stackdriver.0] metadata_server set to http://metadata.google.internal
[2024/10/04 15:28:20] [ warn] [output:stackdriver:stackdriver.0] client_email is not defined, using a default one
[2024/10/04 15:28:20] [ warn] [output:stackdriver:stackdriver.0] private_key is not defined, fetching it from metadata server
[2024/10/04 15:28:21] [error] [output:stackdriver:stackdriver.0] failed to create metadata connection
[2024/10/04 15:28:21] [error] [output:stackdriver:stackdriver.0] can't fetch token from the metadata server
[2024/10/04 15:28:21] [ warn] [output:stackdriver:stackdriver.0] token retrieval failed
[2024/10/04 15:28:21] [error] [output:stackdriver:stackdriver.0] failed to create metadata connection
[2024/10/04 15:28:21] [error] [output:stackdriver:stackdriver.0] can't fetch project id from the metadata server
[2024/10/04 15:28:21] [error] [output] failed to initialize 'stackdriver' plugin
```

**Comment by braydonk** [comment]
Thanks for all the info, the result makes sense to me. We only support a service account key file when reading the `GOOGLE_APPLICATION_CREDENTIALS`, not a WIF credentials file. So I think this result is not a bug and is expected. We don't have any plans at the moment to add WIF credential file support.

Another workaround that might work would be to use [Service Account Impersonation](https://cloud.google.com/iam/docs/workload-identity-federation-with-other-clouds#authenticate) to authenticate a service account to your WIF and use that service account key for Fluent Bit.

**Comment by paulleroyza** [comment]
There is a bug, but last feedback is it's not going to be fixed. :(

**Comment by braydonk** [comment]
Clarifying what I mean; no service account key is required for those docs to work, but I thought that [exporting a service account key](https://cloud.google.com/iam/docs/keys-create-delete) and using the JSON file from that would work. Authenticating directly with WIF credentials is not a supported feature of this plugin. I can't make any promises whether it will be added or not, as it is unlikely I will be allotted development time to do so. I am not opposed to supporting an external contributor or someone from the Fluent Bit team adding it.

**Comment by cagataygurturk** [comment]
@paulleroyza I've a solution for you.

1. Install https://github.com/salrashid123/gce_metadata_server as a sidecar proxy to fluent-bit. Configure it to use the WIF, and it then starts mimicking the GCE Metadata API Server. Make sure you are running it on port 80.
2. Add the following to the Pod spec:

````
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - metadata.google.internal
````

Now fluent-bit will connect to the sidecar to fetch the token, thinking it is actually connecting to the metadata server.

I have full working configuration if you can't figure out.
