### ISSUE TITLE
`Logstash_Prefix_Key` not working (any more?) in Fluent Bit 3.x

### ISSUE THREAD

**Issue by FireDrunk** [fluent/fluent-bit#8869]
## Bug Report

**Describe the bug**
Using the config option: `Logstash_Prefix_Key` mentioned here:
https://docs.fluentbit.io/manual/pipeline/outputs/elasticsearch#logstash_prefix_key
Results in errors: 
```
[2024/05/24 11:08:45] [error] [record accessor] syntax error, unexpected end of file, expecting STRING or INTEGER at '$kubernetes['
```

Changing the value to `$kubernetes['namespace_name']` fixes the issue.

**To Reproduce**
n/a

**Expected behavior**
Either the code accepts both single and double quotes, or the docs need to be more explicit about this.

**Your Environment**
* Version used: 3.0.3
* Configuration: 
```
      [OUTPUT]
          Name                es
          Match               *
          
          Retry_Limit         False

          Host                es-logging-es-http.logging.svc.cluster.local
          Port                9200
          HTTP_User           elastic
          HTTP_Passwd         <snip>
          tls                 On
          tls.verify          Off
          Trace_Error         On
          Trace_Output        Off

          Suppress_Type_Name  On
          Replace_Dots        On

          Logstash_Format     On
          Logstash_Prefix     k8s
          Logstash_Prefix_Key $kubernetes['namespace_name']
```
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes
* Server type and version: 1.27.13
* Operating System and version: Debian 12.5
* Filters and plugins: just `kubernetes`:
```
      [FILTER]
          Name                kubernetes
          Match               kube.*
          Merge_Log           Off
          Merge_Log_Trim      On
          Keep_Log            Off
          K8S-Logging.Parser  On
          K8S-Logging.Exclude On
          Labels              On
          Annotations         On
          Buffer_Size         4M
```

**Additional context**
I'm trying to output to an es index based on the kubernetes namespace, which seems impossible.
I was attempting to use the Logstash_Prefix_Key since that supports variables, which led me to this bug.

Fixing this, still won't give me dynamic indexes.

My ideal situation would be:

```
      [OUTPUT]
          Name                es
          Match               *
          
          Retry_Limit         False

          Host                es-logging-es-http.logging.svc.cluster.local
          Port                9200
          HTTP_User           elastic
          HTTP_Passwd         <snip>
          tls                 On
          tls.verify          Off
          Trace_Error         On
          Trace_Output        Off

          Suppress_Type_Name  On
          Replace_Dots        On
          
          Index               k8s-${kubernetes['namespace_name']:"fluent-bit"} #<-- Where the : sets the default value if the log entry doesn't contain a namespace.
```

**Comment by sparrowt** [comment]
I'm hitting this ame issue with 

```yaml
pipeline:
  outputs:
    - name: es
      match: '*'
      # This is what I wanted to do but `index` does not support record accessors
      #index: "$tag-datastream"
      # This is my workaround attempt, which also doesn't work despite `logstash_prefix_key` apparently supporting record accessors
      logstash_format: on
      logstash_prefix_key: $tag
      logstash_dateformat: 'datastream'  # deliberately don't include any strfime format symbols to exclude the date
```

Please can you re-open this issue? (the GH actions bot is unhelpfully agressive on this repo)
