### ISSUE TITLE
Fluentbit AWS S3 output replaces %2F as Date

### ISSUE THREAD

**Issue by shadowshot-x** [fluent/fluent-bit#8884]
## Bug Report

**Describe the bug**
I want to have %2F in my pipeline so I can replace this in downstream for a dynamic Configuration. However, %2F is replaced by Date in S3 path when Fluentbit sends the records.

**Expected behavior**
%2F should not be replaced by date

Output YAML File
```yaml
pipeline:
  outputs:
  - name: s3
    match: app.var.log.sidecar.app.*.txt
    bucket: xxx
    region: us-west-2
    total_file_size: 60M
    retry_limit: "10"
    upload_timeout: 20s
    net.keepalive_idle_timeout: "5"
    tls.verify: "false"
    log_key: log
    compression: gzip
    use_put_object: "true"
    store_dir_limit_size: 5G
    role_arn: xxx
    s3_key_format: /<some_s3_path>/stdout_FP_mylog%2F123%2F$TAG[5].$TAG[6]/%H%M%S-$UUID
    workers: "1"
```

This is the output I see in S3
`s3://<bucket>/<some_s3_path>/stdout_FP_mylog2024-05-281232024-05-28output1.txt/`

This should not happen as I see date instead of %2F
s3://<bucket>/<some_s3_path>/stdout_FP_mylog**2024-05-28**123**2024-05-28**output1.txt/

**Additional context**
I think this is because of date parsing like %Y %H. Ideally this should not affect the URL Encode Parameters like %2F (/) and %2E (.) etc.
