### ISSUE TITLE
Adding OpenTelemetry attributes to logs forwarded to output Loki

### ISSUE THREAD

**Issue by kelko** [fluent/fluent-bit#8910]
I have a FluentBit container receiving data from a Web API via `name: opentelemetry` input.
Using `name: stdout` output I see, that the log is added to FluentBit in the structured form (including attributes/properties/...whatever-you-want-to-call-it...), not only the pure message.

e.g.:
```
[2] opentelemetry.0: [[1717162605.894517831, {"EnvName"=>"Development", "{OriginalFormat}"=>"Hosting environment: {EnvName}"}], {"message"=>"Hosting environment: Development"}]
```

Note the `EnvName` in the first `[[`. Now I want that output to Loki target.
The fluent bit YAML I use:

```yaml
pipeline:
    inputs:
        - name: opentelemetry
          listen: 0.0.0.0

    outputs:
        - name: loki
          match: '*'
          host: host.docker.internal
          port: 3100
          labels: job=my
```

Loki is a different container on same host. The connection itself does work, but Loki only receives the last part, the `{"message"=>"Hosting environment: Development"}` without the attributes. But I do know Loki is able to handle structured logs (e.g. formatted as JSON), I did it in a different project (without OTel in between).

Now the question is:
How do I tell FluentBit to include the attributes it receives from OTel in the message it sends to Loki?
Or can the Loki output be extended to also include those attributes, not only the log message?

I thought about using a "Content Modifier" processor between input & output. But if I understand the document correctly I can modify either body or attributes. But it didn't seem like I can take over key-value pairs from attributes into body.

(Bonus point if someone can tell me which tags I need to use in above configuration as `match` for the Loki output. Neither `v1_logs`, as mentioned in FluentBit docs, nor `opentelemetry.proto.collector.log.v1.LogService_Export` works. I had to use `'*'` to get _anything_ matching. API sends OTel via gRPc)
