### ISSUE TITLE
Tail + Multi-line parser consumes more than 100% CPU

### ISSUE THREAD

**Issue by tieptoi** [fluent/fluent-bit#8925]
## Bug Report

**Describe the bug**
The Pod CPU usage keep raising until it reached it limit.
It does not happen with v1.9.x
The reason that i want to upgrade to v3.x is that it solve the MajorPageFault issue for us

**To Reproduce**
- Steps to reproduce the problem:
This is my configuration (i left only the relevant parts):
````
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On
        storage.path /var/log/flb-storage/
        storage.sync normal
        storage.checksum off
        storage.total_limit_size 500MB
        storage.pause_on_chunks_overlimit On
        storage.max_chunks_up 20
        storage.backlog.mem_limit 10MB
        storage.type filesystem
        storage.delete_irrecoverable_chunks On

  inputs: |
    [INPUT]
        Name tail
        Alias kube
        DB /var/log/flb_kube.db
        Path /var/log/containers/multiline-log-generator-*.log
        multiline.parser cri
        storage.type filesystem
        Tag kube.*
        Mem_Buf_Limit 5MB
        Static_Batch_Size 50MB
        Skip_Long_Lines On
        Inotify_Watcher True
        Refresh_Interval 10
        Rotate_Wait 60
        Buffer_Chunk_Size 32k

filters: |
    [FILTER]
        Name                  multiline
        Match                 kube.*
        multiline.parser      multiline-java
        multiline.key_content log
        emitter_mem_buf_limit 1MB
        emitter_storage.type  filesystem
        buffer                On
        flush_ms              1000
        mode                  parser
    [FILTER]
        Name                 parser
        Match                kube.*
        Key_Name             log
        Parser               javaspringboot
        Parser               javalog4j2
        Reserve_Data         On
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log            On
        Merge_Log_Key        data
        Keep_Log             On
        K8S-Logging.Parser   On
        K8S-Logging.Exclude  On
        Buffer_Size          64k
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes
        Add_prefix            kubernetes_
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes_labels
        Add_prefix            kubernetes_labels_
    [FILTER]
        Name                  nest
        Match                 kube.*
        Operation             lift
        Nested_under          kubernetes_annotations
        Add_prefix            kubernetes_annotations_     
    [FILTER]
        Name                  modify
        Match                 kube.*
        Rename                kubernetes_labels_app     app_name
    [FILTER]
        Name                  modify
        Match                 kube.*
        Rename                log                       message
        Rename                kubernetes_host           host
        Rename                kubernetes_pod_name       pod
        Rename                kubernetes_namespace_name namespace
        Rename                kubernetes_labels_env     env
        Rename                kubernetes_labels_app     app
        Rename                kubernetes_labels_build   build
        Rename                kubernetes_labels_model   model
        Hard_rename           time timestamp
        Remove                logtag
        Remove                stream
        Remove                _p
        Remove_wildcard       kubernetes

    [OUTPUT]
        Name Stdout
        Match kube.*
````
- Here is the deployment that i used to generate log
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiline-log-generator
spec:
  selector:
    matchLabels:
      app: multiline-log-generator
  replicas: 3
  template:
    metadata:
      labels:
        app: multiline-log-generator
    spec:
      containers:
      - name: multiline-log-generator
        image: busybox
        command: ["/bin/sh","-c"]
        # args: ["echo \"2024-05-31T02:31:38,925 [INFO] --- [1] i.f.k.c.d.i.AbstractWatchManager#logEndError : Watch connection error recieved 136654 times without progress, will reconnect if possible\"; while true; do echo \"io.fabric8.kubernetes.client.KubernetesClientException: Received 401 on websocket. Failure executing: GET at: https://50A83A7613136866C224BB3E0AFF6B61.gr7.ap-northeast-1.eks.amazonaws.com/api/v1/namespaces/jenkins/pods?resourceVersion=522500639&allowWatchBookmarks=true&watch=true. Message: Unauthorized.\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\";echo \"at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.requestFailure(OperationSupport.java:660)\"; sleep 1; done"]
        args: ["no=1;while true;do echo \"2024-06-06T22:57:16,270 [INFO ] --- [      Thread-98] c.w.d.s.AutoDrawService                  : 2024-06-06 22:57:16 彩票(LUCKYSB) [Draw] (53837690) 7,1,9,3,8,10,5,4,6,2 evict:[{key='[LUCKYSB]', deleted=0}, {key='[LUCKYSB_20240606]', deleted=0}, {key='resultsTodayCache[LUCKYSB]', deleted=0}, {key='resultsTodayCache[LUCKYSB_20240606]', deleted=0}]\";echo \"Line number $no\";no=$((no+1));sleep 0.1;done;tail -f /dev/null"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      tolerations:
      - operator: "Exists"
        effect: "NoSchedule"
```
**Expected behavior**
The CPU usage should remain stable throughout the period since the number of logs collected or throughput is the same.

I am not really sure what wrong with my configuration because the performance is day and night between these 2 versions
**Screenshots**
v3.0.6 Metrics
![image](https://github.com/fluent/fluent-bit/assets/5998656/2f886cb7-363e-44ed-b26a-499de4845f3a)

v1.9.10
![image](https://github.com/fluent/fluent-bit/assets/5998656/702b08ca-aae3-44e0-9a10-4e85a8a72f64)

**Your Environment**

* Version used: 3.0.6
* Environment name and version (e.g. Kubernetes? What version?): Kubernetes

**Additional context**
