### ISSUE TITLE
snapcraft: core22 support 

### ISSUE THREAD

**Issue by lupaulus** [fluent/fluent-bit#8954]
Feature
======

**Is your feature request related to a problem?**

I want to deploy fluent-bit inside a snap working on **core22**, the actual version in this repository is **core18**

**Describe the solution you'd like**

Update the snapcraft.yaml 

Notes 
====

I have tried to update it, here my work
Do you want a PR ? @edsiper 

```yaml
name: fluent-bit
base: core22
version: '3.0.7'
summary: High performance logs and stream processor
description: |
  Fluent Bit is a high performance log processor and stream processor for Linux.
  It provides a flexible pluggable architecture to collect, enrich and deliver
  logs or metrics to multiple databases or cloud providers.
license: 'Apache-2.0'
confinement: 'strict'
grade: 'stable'

plugs:
    read-config:
        interface: system-files
        read:
        - usr/local/etc/fluent-bit

apps:
  service:
    command: usr/local/bin/fluent-bit -c usr/local/etc/fluent-bit/fluent-bit.conf
    daemon: simple
    plugs:
      - network
      - network-bind
      - read-config
  fluent-bit:
    command: usr/local/bin/fluent-bit
    plugs:
      - network
      - network-bind

parts:
  fluent-bit:
    source: https://github.com/fluent/fluent-bit
    source-type: git
    plugin: cmake
    stage-packages:
        - libsasl2-2
        - libssl3
        - libpq5
    build-packages:
        - g++
        - make
        - libsasl2-dev
        - libsystemd-dev
        - flex
        - bison
        - valgrind
        - libssl-dev
        - libpq5
        - postgresql-server-dev-all
    cmake-parameters:
        - -DFLB_DEBUG=On
        - -DFLB_OUT_KAFKA=On
        - -DFLB_JEMALLOC=On
        - -DFLB_EXAMPLES=OFF
        - -DFLB_SHARED_LIB=Off
        - -DFLB_OUT_PGSQL=On
        - -DFLB_CONFIG_YAML=Off

```
