### ISSUE TITLE
[error] [config] section 'output' is missing the 'name' property

### ISSUE THREAD

**Issue by Tomas-Big-Z** [fluent/fluent-bit#9178]
## Bug Report

**Describe the bug**
Fluent Bit exits with an error at startup

**To Reproduce**

Create this basic config:

```
service:
  flush: 5
  log_level: debug

pipeline:
  inputs:
    - name: tail
      path: "C:\\Program Files\\fluent-bit\\sample_source.log"
      read_from_head: true
      tag: dmskrnl_raw
  outputs:
    - name: stdout
    - match: "*"
```
Save the config to YAML file and run:

`fluent-bit -c "C:\Program Files\fluent-bit\conf\fluent-bit.yaml"`

Error:
```
[2024/08/08 23:39:34] [error] [config] section 'output' is missing the 'name' property
[2024/08/08 23:39:34] [error] configuration file contains errors, aborting.
```

**Expected behavior**
Fluent Bit should output the contents of a source file to STDOUT

**Screenshots**
![image](https://github.com/user-attachments/assets/429982b1-749f-4398-9122-118ae3415308)

![image](https://github.com/user-attachments/assets/6c81fa0e-4f49-4169-bb12-25a32aee086e)

**Your Environment**

* Version used: Fluent Bit 3.1.4
* Configuration: default
* Environment name and version (e.g. Kubernetes? What version?): Windows
* Server type and version: Windows Server 2022
* Operating System and version: Version 21H2, OS Build 20348.2582
* Filters and plugins: default

**Additional context**
I made sure the YAML config file is properly indented (no mix of tabs & spaces)
I also tried to use classic .config format but always get the error "**undefined value - check config is in valid classic format**", even though the value was indeed provided. I think I will submit a separate bug report for this.
