### ISSUE TITLE
metrics in from prometheus_remote_write input plugin are missing a measurement name in influxdb output plugin

### ISSUE THREAD

**Issue by ejs-tgt** [fluent/fluent-bit#9238]
## Bug Report

**Describe the bug**

Metrics coming in from the prometheus_remote_write plugin fail to parse with a measurement name when exiting out of the influxdb output plugin

**To Reproduce**

Configuration:

```
service:
    flush: 1
    log_level: debug

pipeline:
    inputs:
        - name: prometheus_remote_write
          listen: <address>
          port: <port>
          uri: /api/prom/push
          tag_from_uri: false
          tag: collector_remote_write

    outputs:
        - name: influxdb
          match: collector_remote_write
          host: <influxdbhostname>
          database: '<databasename>'
          auto_tags: on # Automatically tag keys where value is string. This option takes a boolean value: True/False, On/Off.
```

Metrics coming in via remote write input can be confirmed in the stdout plugin to show like this

`
prometheus_tsdb_wal_truncations_failed_total{__name__="prometheus_tsdb_wal_truncations_failed_total",instance="localhost:9090",job="prometheus"} = 0
`

However when the influxdb plugin attempts to convert this to ILP format, the measurement name name ends up null or empty

`{"error":"unable to parse ',__name__=prometheus_tsdb_wal_truncations_failed_total,instance=localhost:9090,job=prometheus,
prometheus_tsdb_wal_truncations_failed_total=0 1723748979490000000': missing measurement\n}`

You can see the start of the line ",__name__=prometheus_tsdb_wal_truncations_failed_total" has a comma at the beginning.  Before that comma should be the measurement name, but it is empty.  This results in the payload being rejected.

I've tried to manipulate the data with filters but all I can seem to do is add additional tags to a payload that is still missing it's measurement name.

- Steps to reproduce the problem:

**Expected behavior**

Prometheus metrics come in via the remote_write plugin and are converted to ILP format and send to influxdb via the influxdb output plugin

**Your Environment**

* Version used:  Fluent Bit v3.0.7
* Configuration: 
```
service:
    flush: 1
    log_level: debug

pipeline:
    inputs:
        - name: prometheus_remote_write
          listen: <address>
          port: <port>
          uri: /api/prom/push
          tag_from_uri: false
          tag: collector_remote_write

    outputs:
        - name: influxdb
          match: collector_remote_write
          host: <influxdbhostname>
          database: '<databasename>'
          auto_tags: on # Automatically tag keys where value is string. This option takes a boolean value: True/False, On/Off.
```
* Environment name and version: docker container
* Server type and version: Linux
* Operating System and version: official v3.0.7 fluent-bit container image
* Filters and plugins:   prometheus_remote_write input, influxdb output

**Additional context**

I am trying to convert metrics from prometheus agents to ILP format and send them to influxdb
