### ISSUE TITLE
Support Parsers in YAML config format

### ISSUE THREAD

**Issue by allewell** [fluent/fluent-bit#9278]
**Is your feature request related to a problem? Please describe.**
Fluentbit's YAML format is awesome as it provides the ability to logically separate individual pipelines. In larger environments, this greatly aids maintainability:
```
flb/
    fluent-bit.yaml
    output.yaml
    filters-global.yaml
    pipelines/
              jira/
                   accesslog.yaml
                   applog.yaml
                   perflog.yaml
                   ...
```

These are brought together in fluent-bit.yaml:
```yaml
service:
  #SNIP
  parsers_file: /flb/atl/parsers.conf
includes:
  - /flb/atl/pipelines/*.yaml
  - /flb/atl/output.yaml
  - /flb/atl/filters-global.yaml
 ```

A sample pipeline looks like:
```yaml
pipeline:
  inputs:
    - name: tail
      tag: applog_raw
      path: /outbox/*/*/*/*/*/*atlassian-jira.log*  # https://github.com/fluent/fluent-bit/issues/2120
      path_key: filename
      read_from_head: true
      db: /flb/tmp/sincedb/jira-applog.db

  filters:
    - name: rewrite_tag
      match: applog_raw
      rule: '$log  "\[JIRA-STATS\] \[DBR\] \[RECEIVER\] snapshot stats period: "  dbr_receiver  false'
    - name: parser
      match: dbr_receiver
      key_name: log
      parser: dbr_receiver_json
      reserve_data: true
#SNIP
```

At present, parsers can't be defined in a YAML file, but need to be configured in a separate file, parsers.conf, in the CONF file format:

```
[PARSER]
    Name         dbr_receiver_json
    Format       regex
    Regex        ^(?<logdate>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:,\d+)?(?:Z|[+-]\d{4})) .+ \[DBR\] \[RECEIVER\] snapshot stats period: (?<period>PT\S+), data: (?<jsoncontent>.*)$
    Time_Key     logdate
    Time_Format  %Y-%m-%d %H:%M:%S,%L%z
    Decode_Field_As json jsoncontent

[PARSER]
...
```

This hurts maintainability that Fluent-bit's YAML system provides - parsers are removed from their originating pipeline file and are lumped in a single file with other non-related parsers. This makes it harder to maintain (two file formats, harder to identify which parsers belong to which pipelines, risks parsers being orphaned, and so on) 

**Describe the solution you'd like**
Support defining parsers in YAML files. For example:
```yaml
pipeline:
  inputs:
    #some input
  filters:
    #some filters
  parsers:
    - name: dbr_receiver_json
      format: regex
      regex: ...
```

**Describe alternatives you've considered**
`processor`s can be defined in the yaml file's input block, but we haven't explored it deeply. In any case, it's a different solution to the traditional filter/parser system and might not suit all use-cases. 

**Additional context**
From a dev-ops perspective, when defining and maintaining monitoring rules that are pushed to multiple or complex applications, and being maintained by different engineers, it helps greatly to logically group pipelines, so that their lifecycle can be better managed.

**Comment by edsiper** [comment]
@allewell this is coming for v3.2 release (end of october)

**Comment by allewell** [comment]
Amazing @edsiper , thank you! If you need a pre-release tester I'd be happy to help

**Comment by edsiper** [comment]
@allewell here I am tracking the Yaml work, parsers and multiline parsers are ready in case you want to try out that branch

https://github.com/fluent/fluent-bit/pull/9513

**Comment by allewell** [comment]
@edsiper thanks for your work on this. I built master and switched over our implementation to be fully YAML based, and I received identical output result for a test data set as the old version :) 

I went further and split the pipelines more and got the same expected output. For example, before we had jira-applog.yaml and parsers.conf, now we have:

`jira-applog.yaml`, containing the input and multiline_parsers:
```yaml
pipeline:
  inputs:
    - name: tail
      path: /outbox/*/*/*/*/*/*atlassian-jira.log*
      tag: applog_raw
      <SNIP>

multiline_parsers:
  - name: multiline_applog
    type: regex
    flush_timeout: 5000
    rules: 
      - state: start_state
        regex: '^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:,\d+)'
        next_state: while_state
      - state: while_state
        regex: '^(?!^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:,\d+))'
        next_state: while_state
```

And `jira-applog-stats.yaml` containing parts of the watched file to be tagged and parsed, along with the parsers to do so:
```yaml
pipeline:
  filters:
    - name: rewrite_tag
      match: applog_raw
      rule: '$log  "\[JIRA-STATS\] \[DBR\] \[RECEIVER\] snapshot stats period: "  dbr_receiver  false'
<SNIP>
    - name: parser
      match: dbr_receiver
      key_name: log
      parser: dbr_receiver_json
      reserve_data: true
<SNIP>

parsers:
  - name: dbr_receiver_json
    format: regex
    regex: '^(?<logdate>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}(?:,\d+)?)(Z|[+-]\d{4}){0,} [^\]]+\] \[DBR\] \[RECEIVER\] snapshot stats period: (?<period>PT\S+), data: (?<jsoncontent>.*)$'
    time_key: logdate
    time_format: "%Y-%m-%d %H:%M:%S,%L"
    decode_field_as: json jsoncontent

<SNIP>
```

this allows us to better logically separate handling different contents within a file. 

big thumbs up and big thank you!  🙇
