### ISSUE TITLE
YAML support for sequences not working in the SERVICE section

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#9508]
## Bug Report

**Describe the bug**

When using YAML sequences (lists) under the service stanza in a Fluent Bit configuration file, the parser throws an error and fails to process the configuration. This prevents users from specifying multiple values in certain keys that could benefit from list support (e.g., parser_file with multiple parser files).

The following configuration render invalid when sequences are set on the parser_file under the service stanza.

```
service:
  log_level: info
  http_server: on
  http_listen: 0.0.0.0
  http_port: 443
  parser_file:
    - 'parser--docker.yaml'
    - 'parser--syslog-rfc5424.yaml'

includes:
  - 'default--inclusion-test.yaml'

pipeline:
  inputs:
    - name: dummy
    - name: tail
      path: /var/log/docker.log
      parser: docker
  outputs:
    - name: stdout
      match: '*'

```

docker run -v $(pwd)/test.yaml:/config/fluent-bit.yaml ghcr.io/fluent/fluent-bit/unstable:latest-debug /fluent-bit/bin/fluent-bit -c /config/fluent-bit.yaml -vvvv
Fluent Bit v3.2.0 | NIGHTLY_BUILD=2024-10-21-06_06_27 - DO NOT USE IN PRODUCTION!
* Copyright (C) 2015-2024 The Fluent Bit Authors
* Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
* https://fluentbit.io/

______ _                  _    ______ _ _           _____  _____
|  ___| |                | |   | ___ (_) |         |____ |/ __  \
| |_  | |_   _  ___ _ __ | |_  | |_/ /_| |_  __   __   / /`' / /'
|  _| | | | | |/ _ \ '_ \| __| | ___ \ | __| \ \ / /   \ \  / /
| |   | | |_| |  __/ | | | |_  | |_/ / | |_   \ V /.___/ /./ /___
\_|   |_|\__,_|\___|_| |_|\__| \____/|_|\__|   \_/ \____(_)_____/

[2024/10/21 08:43:20] [error] [config] YAML error found in file "/config/fluent-bit.yaml", line 7, column 4: unexpected event 'sequence-start-event' (7) in state 'section-value' (5).

**Expected behavior**

Configuration is valid and parsed correctly.

**Your Environment**

Latest fluent-build master build.
