### ISSUE TITLE
Make delete action on content_modifier processors accept list of keys

### ISSUE THREAD

**Issue by anderssynstad** [fluent/fluent-bit#9526]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
```
processors:
  logs:
    - name: content_modifier
      action: delete
      key:
        - foo
        - bar
        - baz
```

**Describe alternatives you've considered**
N/A

**Additional context**
This would make the configuration a lot less bulky if one is removing a large amount of keys.
