### ISSUE TITLE
Input Prometheus Scrape doesn't honor the fluentbit chunk size

### ISSUE THREAD

**Issue by kazeborja** [fluent/fluent-bit#9653]
## Bug Report

**Describe the bug**
When using the input "prometheus scrape" on an endpoint with big number of metrics, fluentbit ends up generating a single chunk with all the metrics inside, which might make it unusable in further pieces of the pipeline (in our case the otlp output doesn't manage to work with big chunks)

**To Reproduce**
- Start a Prometheus metrics endpoint with a big number of metrics (we are trying with 200K one).
- Configure an input scrape to get metrics from the configured endpoint

**Expected behavior**
Fluentbit should split the gathered metrics in smaller chunks instead of producing a single big one

**Your Environment**

* Version used: 3.1.8
* Configuration: The relevant part here is that we increased the buffer_max_size of the input for it to be able to ingest the metrics
* Operating System and version: Alma9

**Additional context**
So far we are trying to use fluentbit as the forwarder agent for metrics to an otlp endpoint, the current situation is we have an exporter that exposes a big number of metrics and we are unable to use the input_scrape -> output_otlp flow to get the data out of the machine.

We have managed to do this setting a Prometheus in the middle which allows us to either split by querying in the metrics_path, we also tested to use the input_prometheus_remote_write and that seems to work also.

Please let me know if any more details are needed.

**Comment by yannick1608** [comment]
I believe I am experiencing a very similar issue. I have the Prometheus Node Exporter running as a container in my setup. Fluent Bit is configured to scrape the data from the Node Exporter using the `prometheus_scrape` input plugin and send it to an InfluxDB instance. However, I am encountering the following error message, which appears repeatedly as part of a JSON object in the output:

```json
{
  "code": "invalid",
  "message": "unable to parse 'node_disk,device=sda,major=8,minor=0,model=,path=,revision=,serial=,wwn= info=1 1733059149824492118': missing tag value\nunable to parse 'node_disk,device=sdb,maj
or=8,minor=16,model=,path=,revision=,serial=,wwn= info=1 1733059149824492118': missing tag value\nunable to parse 'node_disk,device=sdc,major=8,minor=32,model=,path=,revision=,serial=,wwn= info=1 1733059149824492118': missing t
ag value\n"
......
```

Here’s the Fluent Bit configuration in this case:

```yaml
pipeline:
  inputs:
    # Scrape metrics from Prometheus Node Exporter, which collects system metrics
    - name: prometheus_scrape
      host: node-exporter
      port: 9100
      tag: system_metrics

  outputs:
    - name: influxdb
      match: system_metrics
      host: influxdb
      port: 8086
      bucket: ${INFLUX_NODE_EXPORTER_METRICS_BUCKET}
      org: default
      http_token: ${SECRET_TOKEN}
```
