### ISSUE TITLE
Built-in multiline parser java adds newline to end of log statements

### ISSUE THREAD

**Issue by trallnag** [fluent/fluent-bit#9660]
## Bug Report

**Describe the bug**

Usually, Fluentbit removes newline at end of line. But with multiline parser java builtin trailing newline is kept.

**To Reproduce**

Place `fluent-bit-config.yaml`:

```yaml
pipeline:
  inputs:
    - name: tail
      path: /logs/output.log
      multiline.parser: java
  outputs:
    - name: stdout
      match: '*'
```

Place `docker-compose.yaml`:

```yaml
services:
  logger:
    image: alpine
    volumes:
      - ./logs:/logs
    command: sh -c "mkdir -p /logs && rm -rf /logs/output.log && while true; do echo 'Hello world' >> /logs/output.log; sleep 1; done"

  fluent-bit:
    image: fluent/fluent-bit:3.2.2
    volumes:
      - ./logs:/logs
      - ./fluent-bit-config.yaml:/fluent-bit/etc/config.yaml
    command: ["/fluent-bit/bin/fluent-bit", "-c", "/fluent-bit/etc/config.yaml"]
```

Start:

```sh
docker-compose up
```

Witness output:

```
fluent-bit-1  | [0] tail.0: [[1732788845.013237538, {}], {"log"=>"Hello world
fluent-bit-1  | "}]
fluent-bit-1  | [0] tail.0: [[1732788846.013852126, {}], {"log"=>"Hello world
fluent-bit-1  | "}]
fluent-bit-1  | [0] tail.0: [[1732788847.014272955, {}], {"log"=>"Hello world
fluent-bit-1  | "}]
fluent-bit-1  | [0] tail.0: [[1732788848.014791960, {}], {"log"=>"Hello world
fluent-bit-1  | "}]
```

Remove multiline parser from config and restart.

Witness output:

```
fluent-bit-1  | [0] tail.0: [[1732788807.423249739, {}], {"log"=>"Hello world"}]
fluent-bit-1  | [0] tail.0: [[1732788808.424172390, {}], {"log"=>"Hello world"}]
fluent-bit-1  | [0] tail.0: [[1732788809.425156077, {}], {"log"=>"Hello world"}]
fluent-bit-1  | [0] tail.0: [[1732788810.426713448, {}], {"log"=>"Hello world"}]
fluent-bit-1  | [0] tail.0: [[1732788811.428441948, {}], {"log"=>"Hello world"}]
fluent-bit-1  | [0] tail.0: [[1732788812.430047070, {}], {"log"=>"Hello world"}]
```

Related issues that were closed by creators:

- https://github.com/fluent/fluent-bit/issues/4227
- https://github.com/fluent/fluent-bit/issues/8914
