### ISSUE TITLE
Multiple options "Decode_Field_as" in Parser in YAML has invalid format

### ISSUE THREAD

**Issue by heejew** [fluent/fluent-bit#9725]
## Bug Report

I have a "classic mode" configuration  a parser with these two lines:
```
Decode_Field_as escaped message try_next
Decode_Field_as json message 
```
and I had a problem with converting this to YAML:
I tried to do this 
```yaml
      decode_field_as: 
      - type: escaped
        field: message
        action: try_next
      - type: json
        field: message
```
and that
```yaml
decode_field_as:
  - escaped message try_next
  - json message 

```
also,
```yaml
      rules: 
      - backend: decode_field_as
        type: escaped
        field: message
        action: try_next
      - backend: decode_field_as
        type: json
        field: message
```

BUT, it turns out, _working config_ in YAML look like as
```yaml
decode_field_as: escaped message try_next 
decode_field_as: json message 
```

And this is incorrect formating in YAML and i can't use autogeneration YAML, every tools when parsing lose one of the parameters.
Please, make it more correct everywhere.

* Version used: 3.2.2

**Comment by allewell** [comment]
I've noticed the same for `rewrite_tag` `rule`:

```
  filters:
    - name: rewrite_tag
      match: applog_temp
      rule: '$log  "java\.lang\.StackOverflowError"  critical_events  false'
      rule: '$log  "\[c\.a\.jira\.startup\.JiraStartupLogger\] Running Jira startup checks"  critical_events  false'
```

and `parser` `parser`
```
   - name: parser
      match: critical_events
      key_name: log
      reserve_data: true
      parser: stackoverflowerror
      parser: jira_start
```
