### ISSUE TITLE
SIGSEGV in Opentelemetry ouput plugin on termination

### ISSUE THREAD

**Issue by thchan** [fluent/fluent-bit#9839]
## Bug Report

**Describe the bug**

When Fluentbit is terminated while retries are pending in the opentelemetry output plugin, a segmentation fault may randomly occur.

This bug only seems to happen if the input plugins use filesystem storage.

**To Reproduce**

- Steps to reproduce the problem:

Run the following config: 

---------

```
service:
  log_level: debug
  dns.resolver: LEGACY
  flush: 3
  storage.path: /data1/workspace/storage/
  storage.max_chunks_up:    32
  scheduler.base: 2
  scheduler.cap: 200
  
pipeline:
  inputs:
    - name: dummy
      rate: 100000
      storage.type: filesystem

  outputs:
    - name : opentelemetry
      match: '*'
      host:  httpstat.us
      port:  443
      tls:   On
      tls.verify: On
      compress: gzip
      workers:    0
      logs_body_key: message
      logs_uri: /observability/v1/logs
      metrics_uri: /observability/v1/metrics
      traces_uri: /observability/v1/traces
      net.dns.resolver: LEGACY
      net.max_worker_connections:  32
      retry_limit: 10
      storage.total_limit_size: 50M
```

---------

The 404 errors are expected.

After a few minutes, terminate Fluent Bit with ctrl + c.

Fluentbit terminates with a SIGSEGV.

Note: The issue may require a few tries before the segmentation fault is seen.

**Expected behavior**

Fluentbit should gracefully shutdown every time

**Screenshots**

![Image](https://github.com/user-attachments/assets/d4e98c43-aebb-4668-92f6-e23b4f082dd9)

**Your Environment**

* Version used: 
  3.2.0

* Configuration: 
Configuration in reproduction steps.

* Environment name and version (e.g. Kubernetes? What version?):
N/A
* Server type and version:
N/A
* Operating System and version:
Ubuntu 22
* Filters and plugins:
Opentelemetry output plugin
