### ISSUE TITLE
Record Accessor does not support direct array access notation

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#9958]
## Bug Report

The Record Accessor API currently cannot handle direct array access patterns like $[0] or $array[0]. It requires the array to be nested within a map first, like $data.array[0].

```yaml
# This doesn't work
pipeline:
  inputs:
    - name: dummy
      dummy: '{"array": ["a", "b", "c"]}'
  outputs:
    - name: stdout
      match: "*"
      processors:
        logs:
          - name: calyptia
            actions:
              - type: put
                opts:
                  key: "worked"
                  value: "true"
                condition:
                  operator: AND
                  rules:
                    - field: "$array[0]"  # Returns empty
                      operator: eq
                      value: "a"

# This works
pipeline:
  inputs:
    - name: dummy
      dummy: '{"data": {"array": ["a", "b", "c"]}}'
  outputs:
    - name: stdout
      match: "*"
      processors:
        logs:
          - name: calyptia
            actions:
              - type: put
                opts:
                  key: "worked"
                  value: "true"
                condition:
                  operator: AND
                  rules:
                    - field: "$data.array[0]"  # Works correctly
                      operator: eq
                      value: "a"
```

The record accessor implementation in flb_ra_key_to_value requires a map lookup first through ra_key_val_id before handling any array access. This makes it impossible to access array elements directly without first having a map key.

### Proposed Solution:
Modify the record accessor code to:

1. Check if the root object is an array when direct array access is attempted
2. Add handling for array access without requiring an initial map lookup
3. Parse and validate array indices directly
