### ISSUE TITLE
[in_splunk] Memory corruption in splunk input plugin after buffer reallocation

### ISSUE THREAD

**Issue by niedbalski** [fluent/fluent-bit#9964]
## Issue description
The Splunk input plugin (in_splunk) crashes with a segmentation fault when processing HTTP/1.1 requests that require buffer reallocation. The crash occurs due to invalid memory references to HTTP headers after buffer reallocation.

## Reproduction steps
1. Configure Fluent Bit with the provided configuration
2. Build and run the test client 
3. Send HTTP/1.1 requests to trigger the crash

## Current behavior
When using HTTP/1.1 connections (http2: off), the process crashes with SIGSEGV when accessing header data. However, when using HTTP/2 (http2: on), the requests are processed successfully with 200 responses.

When the crash occurs, we see corrupted data in the logs before the segfault:

```
Error sending request: Post "http://localhost:9393/services/collector/event": EOF
C5��' IS NOT VALID. Size is: 26. fluentTag is: nil
full record:	{
  SPLUNK_HEC_TOKEN = "\0\26\0\0\0�\127\0\0\r\14C5�\127\0\0\5\0\0\0�\127\0\0\6",
  bytes = 26694,
  datetime = "06/Feb/2025:17:00:54 -0300",
  event_type = "web",
  host = "120.226.22.46",
  method = "PUT",
  protocol = "HTTP/1.0",
  referer = "http://www.forwardinnovate.org/back-end",
  request = "/platforms/e-business/e-commerce",
  status = 500,
  ["user-identifier"] = "emard6662"
}
```

The process then crashes with this stack trace:

```
[2025/02/20 10:06:11] [engine] caught signal (SIGSEGV)
#0  0x7d9b43            in  splunk_prot_handle() at plugins/in_splunk/splunk_prot.c:720
#1  0x7d3cfe            in  splunk_conn_event() at plugins/in_splunk/splunk_conn.c:98
#2  0x50d737            in  flb_engine_start() at src/flb_engine.c:1060
#3  0x4aa710            in  flb_lib_worker() at src/flb_lib.c:835
```

## Root cause
When the connection buffer requires reallocation to handle more data, the pointers to parsed HTTP headers become invalid as they reference memory locations in the old buffer. The current reallocation code doesn't properly handle updating these pointer references, leading to memory corruption when attempting to access header data.

## Impact
- Affects processing of HTTP/1.1 requests requiring buffer expansion
- Potential data loss due to incomplete request processing

### Fluent Bit configuration

```yaml
service:
  log_level: trace
pipeline:
  inputs:
    - name: splunk
      alias: splunk_hec
      listen: 0.0.0.0
      port: "9393"
      buffer_max_size: 15M
      buffer_chunk_size: 512K
      store_token_in_metadata: off
      splunk_token_key: "SPLUNK_HEC_TOKEN"
      splunk_token: 'AAAA-AAAA-AAAA-AAAA,aaaa-aaaa-aaaa-aaaa,12,21'
      tls.verify: "off"
      tls.debug: "1"
      tag: hec
      http2: off
  filters:
    - name: lua
      match: "hec"
      call: doit
      code: |
        local inspect = require('inspect')
        local tokenMap = {['AAAA-AAAA-AAAA-AAAA'] = 'logs.token1',['aaaa-aaaa-aaaa-aaaa'] = 'logs.token2',['12'] = 'logs.token3',['21'] = 'logs.token4',['111'] = 'logs.token3',['222'] = 'logs.token4',['133'] = 'logs.token3',['2444'] = 'logs.token4',['1555'] = 'logs.token3',['2666'] = 'logs.token4',['1777'] = 'logs.token3',['28888'] = 'logs.token4',['19999'] = 'logs.token3',['2212'] = 'logs.token4'}
        function doit(tag, ts, record, code)
            record['event_type'] = "web"
            record['fluentTag'] = tokenMap[string.sub(record.SPLUNK_HEC_TOKEN,8)]
            local test = string.sub(record.SPLUNK_HEC_TOKEN,1,6)
            if test ~= "Splunk" then
              print(string.format("ERROR Token='%s' IS NOT VALID. Size is: %s. fluentTag is: %s", record.SPLUNK_HEC_TOKEN, record.SPLUNK_HEC_TOKEN:len(), record.fluentTag))
              print("full record: ", inspect(record))
            end
            return 2, ts, record
        end
  outputs:
    - name: http
      alias: hec
      host: nohost
      port: "443"
      uri: /
      format: json_lines
      tls: true
      tls.verify: "on"
      tls.debug: "1"
      net.keepalive: true
      net.keepalive_idle_timeout: 30s
      net.connect_timeout: 10s
      net.connect_timeout_log_error: true
      net.keepalive_max_recycle: "2000"
      Match: logs.lastchance
```

### Test client

```go
package main
/*
Brendan Cooper
JDS Australia
version: 0.1
Last modified: 16 Sep 2024
License: Apache 2.0
*/
import (
    "bytes"
    "crypto/tls"
    "flag"
    "fmt"
    "net/http"
    "os"
    "sync"
    "time"
)

func main() {
    payloadFile := flag.String("payload", "", "Path to the JSON payload file")
    rps := flag.Int("rps", 1, "Number of requests per second")
    token := flag.String("token", "", "Bearer token for Authorization header")
    endpoint := flag.String("endpoint", "", "HTTP endpoint to send requests to")
    flag.Parse()

    if *payloadFile == "" || *rps <= 0 || *token == "" || *endpoint == "" {
       fmt.Println("Usage: go run main.go -payload=FILE -rps=NUMBER -token=TOKEN -endpoint=URL")
       return
    }

    payload, err := os.ReadFile(*payloadFile)
    if err != nil {
       fmt.Printf("Error reading payload file: %v\n", err)
       return
    }

    client := &http.Client{
       Transport: &http.Transport{
          TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
       },
    }

    var wg sync.WaitGroup
    ticker := time.NewTicker(time.Second / time.Duration(*rps))
    defer ticker.Stop()

    for {
       <-ticker.C
       wg.Add(*rps)
       for i := 0; i < *rps; i++ {
          go func() {
             defer wg.Done()
             req, err := http.NewRequest("POST", *endpoint, bytes.NewBuffer(payload))
             if err != nil {
                fmt.Printf("Error creating request: %v\n", err)
                return
             }
             req.Header.Set("Content-Type", "application/json")
             req.Header.Set("Authorization", "Splunk "+*token)
             resp, err := client.Do(req)
             if err != nil {
                fmt.Printf("Error sending request: %v\n", err)
             } else {
                fmt.Printf("Response was %v\n", resp.StatusCode)
             }
          }()
       }
       wg.Wait()
    }
}
```

### Steps to reproduce
1. Save the Fluent Bit configuration as `fluent-bit.conf`
2. Create a JSON payload file with test data
3. Build and run the test client:

```bash
go build main.go
./main -payload=payload.json -rps=1 -token=AAAA-AAAA-AAAA-AAAA -endpoint=http://localhost:9393/services/collector/event
```

4. The issue manifests with HTTP/1.1 (http2: off) but works with HTTP/2 (http2: on)

## Workaround
Currently, using HTTP/2 avoids the issue as seen in the test results.

## Additional notes
- The issue appears consistently reproducible with HTTP/1.1 requests
- The underlying issue may affect other plugins using the Monkey HTTP parser in similar ways
- A long-term fix might require modifications to the Monkey HTTP parser to use offsets instead of direct pointers

## References
N/A
