### ISSUE TITLE
Log lost when task_id is occupied

### ISSUE THREAD

**Issue by duj4** [fluent/fluent-bit#9997]
## Bug Report

**Describe the bug**
We have Loki deployed as the output of FluentBit and owning to the maintenance of K8S cluster, Loki stack was down as well (36 hours-ish). After bring Loki back online this morning, we found some of the logs were lost.

Below is the configuration in our environment:
```
service:
  storage.metrics: on
  storage.sync: normal
  storage.checksum: on
  storage.path: <path_to_data>
  **storage.max_chunks_up: 256**
  storage.backlog.mem_limit: 1G
  storage.delete_irrecoverable_chunks: on
  scheduler.base: 2
  scheduler.cap: 30

pipeline:
  inputs:
    - name: tail
       path: <path_to_file1>
      ...
      storage.type: filesystem
    - name: tail
       path: <path_to_file2>
      ...
      **storage.type: filesystem**   

  outputs:
    - name: loki
      ...
      **storage.total_limit_size: 5G**
      retry_limit: no_limits
```

Please correct me if there is any misunderstanding:
We noticed that the `task_id` stopped at 2047 though there was incoming chunks created, this should be by design: https://github.com/fluent/fluent-bit/blob/v3.2.6/include/fluent-bit/flb_config.h#L291. Each chunk will be processed by each task_id, taking the chunk size into consideration, the maximum buffered data should be:
2048 * 2MB = 4096MB/4G (or even smaller), though `storage.total_limit_size` is set as 5G or larger.

Similar issues:
https://github.com/fluent/fluent-bit/issues/8503
https://github.com/fluent/fluent-bit/issues/8395

**To Reproduce**
- Set storage.type as fileysystem
- Shutdown the output plugin service, Loki in our case
- Wait till the task_id goes to 2047
- Check if there is any log files missed after bring up output plugin

**Expected behavior**
FluentBit can buffer the log files as much as it can be per the setting in `storage.total_limit_size` while output service is down.

**Your Environment**

Version used: 3.2.6
Environment name and version (e.g. Kubernetes? What version?): Linux
Server type and version: Linux
Operating System and version: RHEL 8.0
